### ISSUE TITLE
Issue with time taken to execute a "reconnect"?

### ISSUE THREAD

**Issue by BrantApps** [GetStream/stream-chat-js#100]
Hi there,

I am currently trialing Stream Chat at work and have a working implementation using the `stream-chat-js` directly within our React Native project. I have a query surrounding when/how the SDK decides to perform the `_reconnect` action. Understanding this will help us avoid "dropping" messages when a user backgrounds the mobile app (i.e. the user can't see the app) but the backing web-socket connection is still available.

The problem flow goes a bit like this;

1) User 1 and User 2 are chatting as normal in a conversation
2) User 2 switches app/backgrounds their app/exits their app
3) User 1 soon (<10 seconds) after User 2 has backgrounded their app writes User 2 a new message
4) User 2 *does not* receive this message by way of a push notification.
5) Greater than 10 seconds later after the last activity in the channel User 1 writes another message and sends it
6) Since User 2's client has now "initiated the reconnect" and they receive a push message informing them of the ongoing conversation. However, they have missed a message in the middle.

It appears there maybe issues with the channel `stopWatching` API call. I can see User 1's client issue a `stopWatching` API call only for `typing.start` & `typing.stop` messages to continue to be received.

This `reconnect()` function appears to fix things but I'm not sure if this is a side-effect. Here are some annotated logs from User 1's  device to assist. Lines i've added start with a `>>`;

```
>> Start

>> User 1 is viewing their inbox of messages here:

08-14 17:59:00.533  6564  6851 I ReactNativeJS: 'info', 'client: post - Request - https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/query'
08-14 17:59:00.681  6564  6851 I ReactNativeJS: 'info', 'client:post - Response - url: https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/query > status 201'


>> User 1 and User 2 start chatting here:

08-14 17:59:00.748  6564  6851 I ReactNativeJS: 'info', 'channel:watch() - started watching channel messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:00.750  6564  6851 I ReactNativeJS: 'info', 'client: post - Request - https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/message'
08-14 17:59:00.836  6564  6851 I ReactNativeJS: 'info', 'client: post - Request - https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/event'
08-14 17:59:00.869  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:00.869  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.286  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:01.286  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.290  6564  6851 I ReactNativeJS: 'info', 'client:post - Response - url: https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/message > status 201'
08-14 17:59:01.293  6564  6851 I ReactNativeJS: 'info', 'client: get - Request - https://chat-us-east-1.stream-io-api.com/channels'
08-14 17:59:01.297  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:01.297  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.659  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:01.659  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.826  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:01.827  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.829  6564  6851 I ReactNativeJS: 'info', 'client:post - Response - url: https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/event > status 201'
08-14 17:59:01.831  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:01.831  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.831  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:01.831  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.832  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:01.832  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:01.843  6564  6851 I ReactNativeJS: 'info', 'client:get - Response - url: https://chat-us-east-1.stream-io-api.com/channels > status 200'
08-14 17:59:03.637  6564  6851 I ReactNativeJS: 'info', 'client: post - Request - https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/stop-watching'
08-14 17:59:03.781  6564  6851 I ReactNativeJS: 'info', 'client:post - Response - url: https://chat-us-east-1.stream-io-api.com/channels/messaging/classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351/stop-watching > status 201'


>> User 1 backgrounds their app here:

08-14 17:59:03.782  6564  6851 I ReactNativeJS: 'info', 'channel:watch() - stopped watching channel messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'


>> User 2 starts their response to User 1 here:

08-14 17:59:08.955  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.start }'
08-14 17:59:08.956  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.start } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:08.988  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.start }'
08-14 17:59:08.988  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.start } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:09.109  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.start }'
08-14 17:59:09.110  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.start } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:09.772  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:09.773  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:09.807  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:09.807  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:09.811  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:09.811  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.028  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:12.028  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.134  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { user.watching.start }'
08-14 17:59:12.134  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { user.watching.start } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.135  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:12.135  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.136  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { user.watching.start }'
08-14 17:59:12.136  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { user.watching.start } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.136  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { typing.stop }'
08-14 17:59:12.137  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { typing.stop } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.184  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { user.watching.start }'
08-14 17:59:12.184  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { user.watching.start } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'


>> User 1 gets a notification.message_new event here but the app is backgrounded so our app process does not respond:

08-14 17:59:12.186  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { notification.message_new }'
08-14 17:59:12.243  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { notification.message_new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.244  6564  6851 I ReactNativeJS: 'info', 'client: get - Request - https://chat-us-east-1.stream-io-api.com/channels'
08-14 17:59:12.251  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { notification.message_new }'
08-14 17:59:12.252  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:12.252  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.256  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:12.256  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.562  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.new }'
08-14 17:59:12.562  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.new } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:12.733  6564  6851 I ReactNativeJS: 'info', 'client:get - Response - url: https://chat-us-east-1.stream-io-api.com/channels > status 200'
08-14 17:59:19.704  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:19.704  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:19.707  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:19.708  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:19.710  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:19.710  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:26.055  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:26.056  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:26.059  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:26.059  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:26.063  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:26.063  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:32.301  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:32.301  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:32.304  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:32.305  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'
08-14 17:59:32.307  6564  6851 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { message.read }'
08-14 17:59:32.308  6564  6851 I ReactNativeJS: 'info', 'channel:_handleChannelEvent - Received event of type { message.read } on messaging:classifieds__41909b8e_805d_4920_bb4d_0b57ef70f2ce__4063__5351'


>> User 1's client issues a "reconnect" command here meaning that subsequent messages from User 2 will be delivered via Push:

08-14 17:59:34.567  6564  6851 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
08-14 17:59:34.602  6564  6851 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
```

**Comment by tschellenbach** [comment]
@jaapbakker88 and @vishalnarkhede see above

**Comment by vishalnarkhede** [comment]
Hey @BrantApps ,

How do you handle push notifications currently? I mean how do you decide whether to send a push or not?

**Comment by BrantApps** [comment]
Hi @vishalnarkhede - I don't feel like we are in control of that when it comes to Stream Chat. I have configured stream using the CLI with our Firebase push key and given it a template to send notifications with. It appears Stream side whether a push is attempted vs. a socket message delivery.

**Comment by BrantApps** [comment]
Hi again. I have recorded a short video to describe the steps listed above.

https://photos.app.goo.gl/NzgHp4rFu4CaCZvY8

Apologies for the quality. In the video, just before I focus on the `connection:_reconnect()` terminal output you'll notice I've sent a message "Hiii" (with 3 i's) and a push isn't received. I then (off camera admittedly! 🤦‍♂ ) write the same message having noted the `connection:_reconnect()` in the stream chat logs and lo and behold, I get a push message. The previous message is lost until the chat conversation is reloaded.

Does this shed any light?

**Comment by vishalnarkhede** [comment]
Hey @BrantApps 

Sorry for the delays (was stuck with some other tasks regarding react and react-native sdks). I understand the issue now. I will let you know once we have some resolution on our end. Thanks for the details :)

**Comment by tbarbugli** [comment]
@vishalnarkhede can't we solve this by closing the WS when the app goes to background?

**Comment by aniciom** [comment]
in that case (killing the ws in bg), the only way to get the incomming messages are via push notifications ?

**Comment by BrantApps** [comment]
That sounds good to me from the perspective of a mobile app consumer! If the app has been backgrounded then I'd like to be notified of changes via push message.

**Comment by aniciom** [comment]
yep

**Comment by vishalnarkhede** [comment]
@BrantApps @aniciom For now you will need to disconnect the ws connection manually once app goes in background. You can detect the background state of the app using [AppState](https://facebook.github.io/react-native/docs/appstate).

To disconnect the ws connection:

```
await client.wsConnection.disconnect();
```

And to reconnect once the app comes to foreground:

```
await client._setupConnection();
```

Soon this functionality will be added to our React Native sdk itself. Will keep you updated regarding that :)

**Comment by BrantApps** [comment]
Ok, just retested. We're using 1.0.4 of the client but the problem persists. Here are some more annotated logs;

```
>>> Backgrounded the app (this log line is from our code)
09-24 14:13:47.807 12904 13398 I ReactNativeJS: Attempting to force disconnect of the wsConnection
>>> Resulting action in StreamChat
09-24 14:13:47.808 12904 13398 I ReactNativeJS: 'info', 'connection:disconnect() - Closing the websocket connection for wsID 1'
09-24 14:13:47.922 12904 13398 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
>>> A test message i sent - notice the notification handler fired despite the wsConnection being disconnected.
09-24 14:13:57.194 12904 13398 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { notification.message_new }'
>>> The 20s or so later "thing" that this issue is about causing a reconnect.
09-24 14:14:13.478 12904 13398 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
09-24 14:14:13.482 12904 13398 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
>>> I sent another message here & it was received as a push
```

**Comment by aniciom** [comment]
I will try handling push notifications from my backend directly, since i have both of my certificates mapped at firebase, so i'll have more control over them.

**Comment by BrantApps** [comment]
@aniciom, not upgraded yet. We are moments away from launching a closed beta with the product so didn't want to risk doing it until this release is out. I did scan a diff between the 2 versions to see if there was a formal API for the disconnect in later builds. Couldn't see one. Will upgrade and retest after Friday (our release cut day)

**Comment by BrantApps** [comment]
Interested to know more about how you can decide to send push messages or not. Didn't seem to me that we as SDK consumers can control that at all?

**Comment by aniciom** [comment]
I think the default behaviour from getstream is to make the push when there's a new message, at least thats what i understand from the docs (its not very clear) in that scenario you don't have any kind of control, but you can hook the sending's process through your backend and decide when to send the notifications and the ppl whose are gonna recieve them, of course you will have to do a little bit of work for that but in that scenario you have total control over your notifications.

**Comment by vishalnarkhede** [comment]
We send the push notification only when there is no active web socket connection.

**Comment by vishalnarkhede** [comment]
@aniciom @BrantApps are there any more questions unanswered on this thread? If not, I would like to close it :)

**Comment by aniciom** [comment]
Not by my side

**Comment by vishalnarkhede** [comment]
Closing this ticket now!!

**Comment by BrantApps** [comment]
I was on holiday last week and just catching up with my tasks. So, the issue isn't resolved as I've detailed. @vishalnarkhede's last remark highlights the issue;

> We send the push notification only when there is no active web socket connection.

So there is an active web socket connection when a mobile app is backgrounded (not killed, just backgrounded like when the user taps the home button or multi-tasks away). The user experience past this point renders the chat useless since the user who has backgrounded the app no longer receives notifications about the messages being received. Stream sends the `notification.message_new` WS event but since the JS code in our react-native app is no longer being run (the listening component is unmounted) then the event is lost.

At the time of the app backgrounding I would expect a switch over to push messaging. This is how firebase messaging works. Failing that, some advice as to how to listen to WS events from a react-native app would be appreciated.

**Comment by BrantApps** [comment]
I think rather than creating a new ticket I will create a minimal app for replication that we can publish and reason about. It may help highlight the resolution route.

**Comment by tschellenbach** [comment]
Thanks, that will help us resolve this.

**Comment by vishalnarkhede** [comment]
> Ok, just retested. We're using 1.0.4 of the client but the problem persists. Here are some more annotated logs;
> 
> ```
> >>> Backgrounded the app (this log line is from our code)
> 09-24 14:13:47.807 12904 13398 I ReactNativeJS: Attempting to force disconnect of the wsConnection
> >>> Resulting action in StreamChat
> 09-24 14:13:47.808 12904 13398 I ReactNativeJS: 'info', 'connection:disconnect() - Closing the websocket connection for wsID 1'
> 09-24 14:13:47.922 12904 13398 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
> >>> A test message i sent - notice the notification handler fired despite the wsConnection being disconnected.
> 09-24 14:13:57.194 12904 13398 I ReactNativeJS: 'info', 'client:_handleClientEvent - Received event of type { notification.message_new }'
> >>> The 20s or so later "thing" that this issue is about causing a reconnect.
> 09-24 14:14:13.478 12904 13398 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
> 09-24 14:14:13.482 12904 13398 I ReactNativeJS: 'info', 'connection:_reconnect() - Initiating the reconnect'
> >>> I sent another message here & it was received as a push
> ```

@BrantApps Can you confirm if you consistently see this behaviour on every attempt? By behaviour, I mean if wsConnections gets reconnected automatically even after you forcefully disconnection the connection.

**Comment by cenzovit** [comment]
Also, building a react-native app with stream chat and am running into the same issues as described by @BrantApps with wsConnection and push notification switchover during AppState transitions.

**Comment by vishalnarkhede** [comment]
@cenzovit Did you try the following solution?

> @BrantApps @aniciom For now you will need to disconnect the ws connection manually once app goes in background. You can detect the background state of the app using [AppState](https://facebook.github.io/react-native/docs/appstate).
> 
> To disconnect the ws connection:
> 
> ```
> await client.wsConnection.disconnect();
> ```
> 
> And to reconnect once the app comes to foreground:
> 
> ```
> await client._setupConnection();
> ```
> 
> Soon this functionality will be added to our React Native sdk itself. Will keep you updated regarding that :)

**Comment by BrantApps** [comment]
Owing to a series of unexpected breakages whilst using the sdk direct we've opted to move over to the Stream maintained React Native chat components. Alas, the problem described here...also exists there (https://github.com/GetStream/stream-chat-react-native/issues/72).

As a chat application this needs to be resolved. We need to be able to notify users who aren't looking directly at their channel list/channel conversation that they have a message and not let the 30 or seconds pass between the client issuing this all important reconnect.

**Comment by lucasquinteiro** [comment]
I am having this issue too, has anyone found a workaround or something? Thanks!

**Comment by DobritoiuBogdan747** [comment]
> @cenzovit Did you try the following solution?
> 
> > @BrantApps @aniciom For now you will need to disconnect the ws connection manually once app goes in background. You can detect the background state of the app using [AppState](https://facebook.github.io/react-native/docs/appstate).
> > To disconnect the ws connection:
> > ```
> > await client.wsConnection.disconnect();
> > ```
> > 
> > 
> > And to reconnect once the app comes to foreground:
> > ```
> > await client._setupConnection();
> > ```
> > 
> > 
> > Soon this functionality will be added to our React Native sdk itself. Will keep you updated regarding that :)

I am having trouble with reconnecting the WebSocket.
client.wsConnection.disconnect() works but does _setupConnection() work? 
Or do I have to do something else to reconnect? can I find it in client object?

**Comment by DobritoiuBogdan747** [comment]
Fixed here by doing client.queryChannels() after reconnection, the UI will update correctly afterwards.
[https://github.com/GetStream/stream-chat-react-native/issues/184#issuecomment-643370234](url)

**Comment by BrantApps** [comment]
This isn't fixed.

**Comment by Ingibjorg** [comment]
@vishalnarkhede are there any plans to address this issue within the library? We just ran into this issue with our app and are implementing the web socket disconnection/reconnection workaround for now.

**Comment by mahboubii** [comment]
@BrantApps @Ingibjorg So when you call `client.wsConnection.disconnect()`, it forcefully tries to reconnect? I can't see this behavior in non react-native environments. 

Can you try this:

When app is pushed to background:
```
await client.wsConnection.disconnect();
client.connectionID = undefined;
```
When app is opened again:
```
await client.wsConnection.connect();
await client.recoverState()

```

**Comment by nhannah** [comment]
This issue is stale and there are changes to react-native to handle reconnect now. Please create a new issue if this arises again.
