### ISSUE TITLE
CreateDevice failed with error

### ISSUE THREAD

**Issue by alexander01202** [GetStream/stream-chat-js#1005]
Hello. I am trying to add a device to stream chat and it keeps giving this error:
`[Unhandled promise rejection: Error: StreamChat error code 4: CreateDevice failed with error: "push provider "" with type "firebase" not found"]`

I don't know what is happening. 

I am using android to test this out.

I also enabled firebase with the credentials.json in my dashboard.

This is how I implement it in my code:
```
const registerPushToken = async () => {
      const token = await messaging().getToken();
      await client.addDevice(token, 'firebase');
      console.log(token)

      unsubscribeTokenRefreshListener = messaging().onTokenRefresh(async newToken => {
        console.log("token")
        await client.addDevice(newToken, 'firebase');
        console.log("firebase")
      });
    };
```
It doesn't console.log anything because of the error. 

I am using expo custom managed workflow. 

I have rebuilt the app and everything.

I am surprised no one else has come across this error.

When I put in an incorrect string or value in the addDevice token, i.e `await client.addDevice(newToken, ['firebase']);`

I get the error:
`[Unhandled promise rejection: Error: StreamChat error code 4: CreateDevice failed with error: "expected string for field "push_provider" but got array"]`

When I put in a string value but not any of the correct push provider i.e `await client.addDevice(newToken, 'hey');`
I get the error:
`[Unhandled promise rejection: Error: StreamChat error code 4: CreateDevice failed with error: "push_provider must be one of [firebase apn huawei xiaomi]"]`

So I am confused what it is am doing wrong. I am doing everything the [docs](https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#registering-a-device-with-stream) says.

I have also found some code errors in the docs, and I can't but only wonder whether it's an error in the doc or sth.

**Comment by ferhatelmas** [comment]
If  you add a provider in dashboard, then you provided a name and enable multi-bundle. Then you need to specify its name as below to associate your device to your provider since there can be multiple providers.

```js
// last parameter is the name you used in dashboard
client.addDevice(token, pushProviderType, userID || null, pushProviderName)
```

**Comment by alexander01202** [comment]
Please what is userID? Is this the id of the user of my app ?

**Comment by ferhatelmas** [comment]
It's required if you're using server side auth (node), otherwise pass null since client will identify itself from connection.

**Comment by alexander01202** [comment]
Thank you it works!!!

**Comment by alexander01202** [comment]
@ferhatelmas Please could you look at my new [issue](https://github.com/GetStream/stream-chat-js/issues/1006)

**Comment by MaxAst** [comment]
ran into the same issue, followed the exact same steps as described in the [docs](https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#registering-a-device-with-stream). I managed to fix it by adding the `push_provider_name` with the name of the config I created in the dashboard, but it's suboptimal that I even run into this issue. This should definitely be mentioned in the docs @ferhatelmas
