### ISSUE TITLE
UpdateApp failed with error

### ISSUE THREAD

**Issue by alexander01202** [GetStream/stream-chat-js#1006]
Hello. I an error:
`Error: StreamChat error code 4:Unhandled Rejection Error: StreamChat error code 4: UpdateApp failed with error: "firebase credentials are invalid"`

I am not migrating from any version. Just trying to call:
```
const serverClient = StreamChat.getInstance( api_key, api_secret);
const apn_template = `{
    "aps": {
        "content-available": 1
    }
  }`;
  
  serverClient.updateAppSettings({
    firebase_config: {
      apn_template,
    }
  });
```

This all according to the [docs](https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#make-ios-payload-data-only)

I have set the firebase credentials in the dashboard. I also implemented some code in my front end which need firebase intergration and they all work but on my backend (node js). It doesn't work. It keeps giving me this error.

**Comment by alexander01202** [comment]
I was able to solve this by setting it like this
```
serverClient.updateAppSettings({
    firebase_config: {
        credentials_json:fs.readFileSync(
            '../firebase-adminsdk.json',
            'utf-8',
        ),
      apn_template,
    }
  });
```

But I wonder, if I set it in the dashboard, shouldn't it be able to read it automatically without me calling the api again?

**Comment by ferhatelmas** [comment]
Problem is that you are mixing non-multi bundle (updateAppSettings endpoint) and multi bundle settings (upsertPushProvider endpoint). Dashboard uses latter by default to support multi bundle so when you made this call, you used the former which should be valid but actually there was no creds and not valid. When you add it too, then it works.

I will improve docs a bit to clarify this distinction.

**Comment by ferhatelmas** [comment]
It's the json file contents you will get from firebase for your service account that can use your account to send messages.

You have an example [here](https://getstream.io/chat/docs/react/push_introduction/?language=javascript#firebase) to see how it looks like.

**Comment by alexander01202** [comment]
So it's still the same thing as the first step for `non multi-bundle`. I still need to link my firebase credentials file even though it's uploaded on the dashboard?

**Comment by ferhatelmas** [comment]
If you are updating already existing one, you don't need to do. Uniqueness is checked by type (firebase) and name (you specify).
If you change them, you're creating a new one so credentials are needed.

**Comment by alexander01202** [comment]
Alright thank you. I appreciate it
