### ISSUE TITLE
Can't create channel from backend (serialization issue?)

### ISSUE THREAD

**Issue by filipeGuerreiro** [GetStream/stream-chat-js#1020]
We are getting the following error in our backend when we attempt to create a channel between two users:

```
GetOrCreateChannel failed with error: "data.members[0].user.id is not a valid user id. a-z, 0-9, @, _ and - are allowed., data.members[1].user.id is not a valid user id. a-z, 0-9, @, _ and - are allowed."
```

Error response log we see in datadog:
```
{"data":{"name":"Mz���cE���[��&�\u0013-���\u0015Q�K\"��h_f�9","members":["TXr7pudjRcGNzlur1iaVEw==","u+HmFVH9SyKrzmhfZvGzOQ=="]},"state":false,"watch":false,"presence":false}
```

data.name seems to be utf-8 encoded, while data.members seems to be base64?

This is the way we are creating our channel:
```
  const channel = client.channel('messaging', {
    name: `${streamId1}-${streamId2}`,
    members: [streamId1, streamId2]
  })
  await channel.create()
```

Package version: `"stream-chat": "^5.1.2"`

Did we misconfigure something? Any help would be appreciated!

**Comment by AnatolyRugalev** [comment]
Hey @filipeGuerreiro 

It seems that you are providing uint8 arrays instead of strings to this function. Try decoding them into strings before sending to the StreamChat client.

Here's how you use TextDecoder to do this: https://stackoverflow.com/questions/8936984/uint8array-to-string-in-javascript

Please let me know how it goes :)

**Comment by filipeGuerreiro** [comment]
Hey @AnatolyRugalev, thanks for the quick reply. Your reply got us on the right track. Turns out we were passing in `streamId` as a mongo UUID type (which I guess is a binary array). Totally our fault.

Closing this issue, thanks again!
