### ISSUE TITLE
Request to join channel feature request

### ISSUE THREAD

**Issue by rohanvasishth** [GetStream/stream-chat-js#1022]
So I understand that an invite members framework exits. However, I am looking to implement the reverse of this. As in a user on my app would be able to see the list of channels and then send requests to join them depending on which channel the user wanted to join. On the other end, channel members would be able to accept or deny the request to join them.

In my reading of the docs, I don't think this is currently achievable but please do let me know if it is and how I can do it. Thanks!

**Comment by miagilepner** [comment]
Thanks for reporting this. This is a good idea and we've added this as a feature request to our backlog.

In the meantime, because this issue describes a backend feature and is not specific to the javascript SDK, I'm going to close this issue.

**Comment by JuI3s** [comment]
Is there any update on this?
