### ISSUE TITLE
How to make every user connect to a specific channel?

### ISSUE THREAD

**Issue by alexander01202** [GetStream/stream-chat-js#1025]
Hello. Is it possible to create like a customer support channel? Every users complaint would be private to only us and them. Would I connect them the exact same way I connect other channels?

**Comment by luisgereda** [comment]
Hi Alex, we have left the issues report on our GH repositories exclusive for bug reporting. 
Please send us your question to support@getstream.io, we will be happy to help you through our support channel.

Regards,
Luis
