### ISSUE TITLE
Filter last message by user

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-js#103]
Is there any way from the sdk to filter (using queryChannels's method or query's method) the last message  using a specific user id that created that message?

I mean i want to get the last message according to the user that's making the reques,t but the sdk is retrieving the last message no matter what user is making the request, that makes sense, but i would like to filter by a specific user id or using the inverse condition those messages whose don't belong to the user who's making the request, is there any way to accomplish this? 

I couldn't see any examples in the test suite or the doc page using this use case.
Thanks

**Comment by vishalnarkhede** [comment]
@aniciom  Currently there is no method for this (to get last message for particulate user id) ... @thesyncim correct me if I am wrong here. 

But all messages are available in channel state (`channel.state.messages`), so you can always filter out the current user's last message by iterating over messages and checking the comparing against user of that message (message.user.id).

**Comment by aniciom** [comment]
thanks
