### ISSUE TITLE
How can I filter the chat list excepting for items which inviting member request is rejected?

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-js#1050]
Hello,

My application has 2 tabs - `Inbox` and `Message Request`.

- Filter for Inbox:
```
    type: `messaging`,
    members: { $in: [user?.id] },
    last_message_at: { $lt: new Date() },
    member_count: { $eq: 2 },
    joined: { $eq: true }
```

- Filter for Message Request
```
    type: `messaging`,
    members: { $in: [user?.id] },
    last_message_at: { $lt: new Date() },
    member_count: { $eq: 2 },
    joined: { $eq: false },
    invite: { $eq: `pending` },
```

It works well now. But the problem happens when **rejecting** the pending message request.
For example, 
If `User A` requests a message to `User B`, then this message will display in `Inbox` from `User A`, and `Message Request` from `User B`.
If `User B` accepts `User A`'s request, then the conversation will be started on Both `Inbox`.
If `User B` rejects `User A`'s request, then the pending item from `User B`'s Message request will be disappeared.
At the same time, the message from `User A`'s side will be disappeared as well.

So I am gonna implement this feature by using filtering.
So if inviting member is rejected, then it will be filtered in Inbox filter.
How can I do it?

Regards.

**Comment by ferhatelmas** [comment]
Adding `"invited": "rejected"` will do the trick from the invited point of view.

However, other side is difficult because invites don't track where an invite comes from. You can simply remove joined from the inviter side to show all channels and on the client side, you can treat channels that aren't joined differently. 

If you can explain more about your approach for filtering, we can provide more details for you.

**Comment by vanGalilea** [comment]
@cleandevcode Let us know if it worked for you. In the meanwhile, I'll be closing this issue for now. Please don't hesitate to contact us in the future if this issue or any questions arise.

**Comment by cleandevcode** [comment]
@vanGalilea Yes, that worked for me.
Thanks for your support.
