### ISSUE TITLE
Can't revoke channel permissions

### ISSUE THREAD

**Issue by apa512** [GetStream/stream-chat-js#1059]
```
  const streamClient = new StreamChat(streamApiKey, streamApiSecret);
  const channel = streamClient.channel("team", "my-channel");
  const x = await channel.updatePartial({
    set: {
      config_overrides: {
        grants: {
          user: ["ban-channel-members"],
        },
      },
    },
  });
```

1. I have a channel where users are not allowed to ban channel members
2. I run the above code
3. Users can now ban channel members
4. I run the above code but with "!ban-channel-members" instead of "ban-channel-members"
5. Users are still allowed to ban channel members

So it seems that the revoking is just silently ignored without any error messages.

This is on 8.0.0.

Any idea what could be wrong?

**Comment by ffenix113** [comment]
Hello @apa512 ,

In this case grant name should be `ban-channel-member`, whithout `s` in the end.

Please see list of available grants here: https://getstream.io/chat/docs/node/permissions_reference/?language=javascript

Feel free to re-open the issue if this will not solve the issue.
