### ISSUE TITLE
Unread count reset after reconect

### ISSUE THREAD

**Issue by prochorz** [GetStream/stream-chat-js#1061]
I have just connect
```js
this.client = StreamChat.getInstance(this.config.userKey);
        const name = this.config.userName;

        this.user = await this.client.connectUser(
            {
                name,
                id: this.config.userId,
                image: `https://getstream.io/random_svg/?name=${name}`
            },
            this.config.userToken
        );
```

And I try get unreadCounter
```js
    function getChannelsCount() {
        setChannelsCount(channels.current.reduce((acc, chanel) => {
            acc[chanel.cid] = chanel.countUnread();
            return acc;
        }, {}));
    }

   channels.current = await instance.client.queryChannels({}, {}, { state: false });

   getChannelsCount();
```
It's always return 0

If I will write to some chanel message. I will get a new counter by socket

```js
channels.current.forEach(chanel => {
    chanel.on(getChannelsCount);
});
```
So now, for example I have 4 new message. All works fine. But if I refresh page, I will get 0.
Why do my unread messages become read?

**Comment by vanGalilea** [comment]
@prochorz thanks for reaching out.
We're currently trying to reproduce this bug on our side, we will get back to you if additional info is needed.

Please follow this issue for further updates

**Comment by vanGalilea** [comment]
@prochorz I have managed to reproduce this issue on my machine, stay tuned for more updates!

**Comment by vanGalilea** [comment]
@prochorz, we are curious to hear more about your use case and what you are trying to achieve. These are our questions to try and clarify things:

- In addition to `stream-chat` are you using one of our UI SDKs (React/React Native)?
- When a user sends a message, why do you expect the unread count to increase? The unread count consists of messages from other users that have not been read yet by the logged-in user.
- To gain a better understanding, can you please share a loom/screen recording with us?

**Comment by vanGalilea** [comment]
@prochorz, thanks for reaching out. I'll be closing this issue for now due to inactivity.

Please don't hesitate to contact us if this issue or any questions arise.
