### ISSUE TITLE
bug: queryChannels doesn't always return full channel list

### ISSUE THREAD

**Issue by joelpierre** [GetStream/stream-chat-js#1078]
We are using the `queryChannels` function and it doesn't always return the users full list of channel Ids.

As you can see from the video below on subsequent reloads the user sees different sets of data. Is this a caching issue on your end? I have seen this with setups that use a horizontally scaled elastic cache setup that don't keep instances in sync?

Curious to hear your thoughts

`"stream-chat": "8.1.3"`

https://user-images.githubusercontent.com/8969851/208166523-93f44e92-b212-47d9-bda0-caa73ab84b19.mov

**Comment by vanGalilea** [comment]
@joelpierre thanks for reaching out. Can you please share your implementation via a [code sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv) to get us started with triaging?

**Comment by joelpierre** [comment]
Hey @vanGalilea will sort something out soon. I don't want to expose any keys here, but I will see about using your demo key at least 👍🏽

**Comment by joelpierre** [comment]
@vanGalilea - If it helps this is the client request id for the faulty fetch: `fc08f088-d1b1-4afe-a8a5-04aa984c2077` and this is the request id for the fetch that returned all channels: `d86df867-b467-402e-aa34-e1244fcff41c`.

I tried to replicate... but I can't with the sandbox 🤷🏽  but I have put the fetch in that we are using via your client https://codesandbox.io/s/inspiring-breeze-mcnffb?file=/src/App.tsx

**Comment by joelpierre** [comment]
@vanGalilea any update? We also tried using the `usePaginatedChannels` hook from the react SDK and have the same issue which highlights to me its a stream issue IMO. There are no signs of rate limiting etc either.

**Comment by vanGalilea** [comment]
Hi @joelpierre we're still investigating the matter. Not being able to reproduce the issue makes things a bit more challenging for us.

**Comment by joelpierre** [comment]
@vanGalilea I would be happy to jump on a call, give you a test account etc to test it?

**Comment by ferhatelmas** [comment]
If an application is old, we filter channels a user can't access. If newer application, this returns an error with the explanation. This is the case for backward compatibility.

Your filters are too generic, it might be matching to these channels. Try to replace `$nin` with `$in` of `type` of what you care. Increasing specificity of filters should be the first direction.

**Comment by joelpierre** [comment]
Thanks @ferhatelmas , we will try this and get back to you

**Comment by joelpierre** [comment]
@speediac FYI

**Comment by joelpierre** [comment]
Update on the above guys @vanGalilea & @ferhatelmas - We have an app release scheduled for today to test in production the changes to the filters you suggested. Will update if the issue is resolved 👍🏽

**Comment by joelpierre** [comment]
@vanGalilea @ferhatelmas  - It appears that being more specific with the filters we use has indeed helped and our channels are returning as expected now. I would still say this is a bug however as I would expect a simple filter to work, just as well if not better than a more complex filter.
