### ISSUE TITLE
Is it possible to send typing events server side?

### ISSUE THREAD

**Issue by pzmudzinski** [GetStream/stream-chat-js#1100]
Little bit of context: we are using `stream-chat-js` in server side for generating responses as a chatbot.
We want to generate typing indicators like "Chatbot starts typing...." but I am not sure if API supports it. 
I don't see any option to pass `user_id` of user who started typing with `keystroke` method. Does it work client side only?

**Comment by einarhorn** [comment]
I have a similar usecase - would be great if this could be supported!

**Comment by einarhorn** [comment]
Not ideal, but I was able to get around this tentatively by constructing a client-side client on the server-side, and calling the `keystroke` method. However, I get warning messages in the console about this approach.

**Comment by pzmudzinski** [comment]
I figured it out - I am using `sendEvent` API with `typing.start` or `typing.stop` events, like that:
```typescript
  await channel.sendEvent({
    type: 'typing.start',
  });
```

**Comment by vanGalilea** [comment]
@pzmudzinski, that should be the best way to tackle this, I will be closing this issue for now
