### ISSUE TITLE
Bug: Cannot get unread count per channel

### ISSUE THREAD

**Issue by MaxAst** [GetStream/stream-chat-js#1104]
I have a list where each list item component has the following useEffect:

```
useEffect(() => {
    const channel = chatClient.channel("messaging", id);
    setUnread(channel.countUnread())
    const listener = channel.on((event) => {
      if (event.type === "notification.message_new" && event.unread_count) {
        setUnreads(event.unread_count);
      }
    });
    return () => {
      listener.unsubscribe();
    };
}, [id]);
```

When another channel member sends a message into the given channel, `channel.countUnread()` returns 0 and the event listener contains the user's total unreads on both fields, `total_unread_count` and `unread_count`. I would have expected the latter to be the unread count for only the given channel. So I guess two things are broken:
1. `channel.countUnread()` always returns 0 when the list item component mounts, even when the `total_unread_count` and `unread_count` are greater than 0 (I also verified that it can't be 0 by logging this at the beginning of the useEffect body: `console.log(JSON.stringify(chatClient.user, null, 2));`, which returned `total_unread_count` and `unread_count` greater than 0)
2. `total_unread_count` and `unread_count` both return the unread count across all channels instead of `unread_count` only returning the unread of the given channel

**Comment by sterlingwes** [comment]
I logged a similar issue recently if maintainers see this https://github.com/GetStream/stream-chat-js/issues/1103

(Thank you for sharing your workaround)

**Comment by sterlingwes** [comment]
@MaxAst do you mind sharing your `stream-chat` version number? I've tried your code above and `const me = state.read` is always undefined for me, not sure how you're getting the initial count

**Comment by MaxAst** [comment]
`"stream-chat": "^8.4.1"` with `"stream-chat-expo": "^5.11.2"`

I'm a bit worried as to why there hasn't been a reaction by the maintainers yet.. considering it's a core feature of a paid product 🤷

**Comment by MaxAst** [comment]
@santhoshvai  `channel.countRead()` works for me now, but now `streamClient.user.total_unread_count`, `streamClient.user.total_unread_count`, and `streamClient.user.unread_channels` are all 0, while `channel.countRead()` returns the correct value

**Comment by vanGalilea** [comment]
Closing this in favour of #1119
