### ISSUE TITLE
Pagination - how to get total number of channels from a query?

### ISSUE THREAD

**Issue by pzmudzinski** [GetStream/stream-chat-js#1106]
Assuming we want to use _limit_/_offset_ pagination API like here:
```javascript
await authClient.queryChannels(filter, sort, {
    limit: 20, offset: 10
});
```
And use pagination component like here:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/1887653/226449871-c8d6a454-2c12-4ca1-9539-eadc41d36be7.png">

It seems impossible right now since we do not know how many channels are in total.
Is there any extra API I am missing?

**Comment by luisgereda** [comment]
Hi we have left GH issue only for bugs report.

Please send your support request through our help center:
https://getstream.io/contact/support/

One of our support engineers will be happy to help you.

Thanks,
Luis
