### ISSUE TITLE
Uncaught TypeError: Cannot read property 'FormData' of undefined

### ISSUE THREAD

**Issue by liuchanglongs** [GetStream/stream-chat-js#1114]
eportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'FormData' of undefined

**Comment by vanGalilea** [comment]
@liuchanglongs can you please elaborate, what's going wrong?

**Comment by liuchanglongs** [comment]
> 
uniapp 使用 JavaScript sdk，打包后生成app，运行出现
eportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'FormData' of undefined

在浏览器上面运行没有问题

**Comment by liuchanglongs** [comment]
> @liuchanglongs can you please elaborate, what's going wrong?

Uniapp uses JavaScript SDK, but there is an error when packaging and generating the app。

error：FormData is undefined。
FormData used in JavaScript sdk。below：

**Comment by vanGalilea** [comment]
@liuchanglongs, thanks for the info.
Can you please elaborate more on how you're integrating our SDK? 
- Is it via the web (own implem.) or our react/react native SDKs?
- Please specify some relevant code so we will be able to reproduce your issue.

In the meanwhile, we strongly advise you to upgrade our SDK to its latest version (v8.6.0). The version you're using was release almost 2 years ago.

**Comment by liuchanglongs** [comment]
> @liuchanglongs, thanks for the info. Can you please elaborate more on how you're integrating our SDK?
> 
> * Is it via the web (own implem.) or our react/react native SDKs?
> * Please specify some relevant code so we will be able to reproduce your issue.
> 
> In the meanwhile, we strongly advise you to upgrade our SDK to its latest version (v8.6.0). The version you're using was release almost 2 years ago.
Developing an app using stream（"stream-chat": "^7.1.0"） chat using uniapp。
firstly: 
import { StreamChat } from 'stream-chat';
secondly:
console.log(StreamChat);
thirdly:
Enabling Real Machine Debugging for Uniapp,or,Package and **generate an app** using uniapp and run it on your phone。
Finally, a white screen and an error message will appear。
**ERROR:** Uncaught TypeError: Cannot read property 'FormData' of undefined

If I don't use and introduce StreamChat, the app won't report an **error。**

**Comment by OutdatedGuy** [comment]
@liuchanglongs, Yo, if you are using typescript, can you try adding `"esModuleInterop": true` under the `"compilerOptions"` inside `tsconfig.json` file.

Like:
```json
{
  "compilerOptions": {
    "esModuleInterop": true
  },
}
```

**Comment by vanGalilea** [comment]
> In the meanwhile, we strongly advise you to upgrade our SDK to its latest version (v8.6.0). The version you're using was released almost 2 years ago.

@liuchanglongs if the error persists after you upgrade, I'd kindly advise you to submit a repo with clear steps on how to reproduce this issue.

**Comment by vanGalilea** [comment]
I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
