### ISSUE TITLE
Unmute action doesn't send "notification.mutes_updated" event

### ISSUE THREAD

**Issue by BrantApps** [GetStream/stream-chat-js#112]
We have been trying out some of the chat moderation controls whilst assessing the suitability of Stream Chat for our application and encountered an issue with the mute/unmute action.

To replicate
1. Mute a user in a chat
2. Receive `notification.mutes_updated` event
3. Unmute the same user in a chat

Expected result
* We receive a `notification.mutes_updated` event

Actual result
* No event is received

Is this expected? If so how do we go about listening for unmute changes without leveraging the `mutes_updated` event?

Thank you in advance.

**Comment by tbarbugli** [comment]
thank you for reporting this; we're going to look into this and update this issue asap

**Comment by tbarbugli** [comment]
we are doing QA on the change today, we should get this live today or during the weekend

**Comment by BrantApps** [comment]
Great. I am planning on coming back to this on Wednesday this week so I'll ping you back then! Thank you for your work to date.

**Comment by Bogdan-D** [comment]
@BrantApps unmute event was fixed, please reopen the issue if you will have any problems.
Thank you for reporting

**Comment by BrantApps** [comment]
Thank you. I can see the unmute action causes the event to fire 👍
