### ISSUE TITLE
Undread status for multiple channels (Question, Issue)

### ISSUE THREAD

**Issue by AndriiSiuta** [GetStream/stream-chat-js#1125]
* I have multiple conversations ( multiple channels)
* I have created a context menu with 2 options - markAsRead, markAsUndread 
* Mark as read Works Fine. For those options, we have back-end API, similar to StreamChatJs have for Read Unread with POST. But after I mark them as Undread 0 events from the WS of the library, with read - better situation I got an event. 

Expect some event for the unread channel to get it instant, not after reloading the page.
What we have: we have that undread status work only after reloading the page.

**Comment by MartinCupela** [comment]
Hey @AndriiSiuta ,

do I understand it well, that when you call `channel.markUnread()` you do not receive `notification.mark_unread` event? Is this issue still relevant?

**Comment by MartinCupela** [comment]
@AndriiSiuta feel free to re-open the issue if still relevant.
