### ISSUE TITLE
Server-side ban action not working

### ISSUE THREAD

**Issue by BrantApps** [GetStream/stream-chat-js#113]
Following on from #112 we've been testing how the "ban"/"unban" functionality is meant to operate. Unfortunately, we've encountered more issues with the server-side node approach or the (stream-cli)[https://github.com/GetStream/stream-cli/blob/master/docs/chat.md#stream-chatuserban] `stream:chat:ban` approach yielding errors. Here is a short gif of the actions I'm taking resulting in the below noted exception;

![stream-ban-user](https://user-images.githubusercontent.com/1109992/64624256-467a4a80-d3e2-11e9-91ea-17dc2684ecbf.gif)

```
Error: StreamChat error code 4: Ban failed with error: "either user or user_id must be provided when using server side auth."
    at StreamChat.errorFromResponse (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/dist/index.js:4124:15)
    at StreamChat.handleResponse (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/dist/index.js:4138:20)
    at StreamChat._callee8$ (/usr/local/lib/node_modules/getstream-cli/node_modules/stream-chat/dist/index.js:3923:56)
    at tryCatch (/usr/local/lib/node_modules/getstream-cli/node_modules/regenerator-runtime/runtime.js:45:40)
```

We're a little perturbed as to what is going on for everything not to be working. I understand the `stream-chat-js` client has only just reached 1.0.0. We are running stream-cli at `getstream-cli/0.0.12 darwin-x64 node-v12.8.0` and `stream-chat-js` at 1.0.1.

We are going to upgrade to 1.0.4 and retry but both this ticket and #112 don't appear to be client issues.

**Comment by nparsons08** [comment]
@BrantApps This is likely an issue with the Stream CLI. I'll personally look into this and follow up. Stay tuned.

**Comment by BrantApps** [comment]
Thank you for the fast follow up @nparsons08 - sorry for all the issues. The moderation controls is a dealbreaker for us so wanted to report them rather than wait for a fix.

**Comment by tanuck** [comment]
@nparsons08 we've replicated the same problem with the cli and `stream-chat` library.

**Comment by nparsons08** [comment]
@tanuck @BrantApps I'm assuming you ran `$stream config:set` first, right?

**Comment by tanuck** [comment]
Yes

**Comment by nparsons08** [comment]
Just pushed a fix for the CLI – `getstream-cli@0.0.13`.

As for using the `stream-chat-js` SDK, you need to provide a `user_id` in the payload of the user who is banning the other user. For example, if user `A` is being banned, you would add user `B` to the payload as follows:

```js
const payload = {
    reason: flags.reason,
    user_id: 'CLI',
};
```

And call it like so:

```js
await client .channel(type, id) .banUser(flags.user, payload);
```

Can you please upgrade and verify that the CLI is passing back the correct information? Thank you.

**Comment by BrantApps** [comment]
Thanks @nparsons08 - I'm confused. Now I receive this from the CLI;
```
Error: StreamChat error code 16: Ban failed with error: "the user CLI does not exist"
```
🤔

**Comment by nparsons08** [comment]
Can you shoot me an email at nick@getstream.io with your emails? I'd like to get you added to our public chat on Slack.

**Comment by tschellenbach** [comment]
following up here, has this been resolved?

**Comment by BrantApps** [comment]
with 0.0.14 of the stream cli we were able to ban a user. We didn't try again via the stream client with @nparsons08 describing the payload we'll need to send to use the API in conjunction with server-side auth.

**Comment by nparsons08** [comment]
This has been resolved.  The CLI or server side calls require that you pass a user_id of then person who is creating the ban. A new version of the CLI is now available with a fix in place.

**Comment by tanuck** [comment]
The docs need to be updated to reflect that user/user_id is required in the payload.

https://getstream.io/chat/docs/#moderation
