### ISSUE TITLE
Issue with fetching pinned messages in DESC order and not receiving newly pinned messages (or All pinned messages)

### ISSUE THREAD

**Issue by toey-sup** [GetStream/stream-chat-js#1132]
# Overview:
When using the channel.getPinnedMessages() function in Getstream.io to fetch pinned messages, the behavior is not as expected. The function is supposed to retrieve all (or according to limit parameter) pinned messages in descending order, but when a new message is pinned and the function is called again, the newly pinned message is not returned.

# Steps to reproduce:
1. Call channel.getPinnedMessages() with the following parameters: { limit: 50 }, { pinned_at: -1 }.
2. Observe the returned pinned messages in descending order.
3. Pin some more messages
4. Call channel.getPinnedMessages() with the following parameters: { limit: 50 }, { pinned_at: -1 } again.
5. Observe the returned pinned messages

# Expected behavior:
The channel.getPinnedMessages() function should return the pinned messages in descending order, including any newly pinned messages that have been added since the last call.

# Actual behavior:
The function returns the pinned messages in descending order initially, but when a new message is pinned, calling the function again does not include the newly pinned message in the result.

# Screenshots or code snippets:
## with `pinned_at: -1`
<img width="366" alt="Screenshot 2566-06-01 at 14 09 12" src="https://github.com/GetStream/stream-chat-js/assets/31316439/97bb2996-ca4b-496f-a3e5-9aee3fd630e9">
<img width="654" alt="Screenshot 2566-06-01 at 14 09 52" src="https://github.com/GetStream/stream-chat-js/assets/31316439/1a846b03-a50e-48bc-89ce-a4a0ac4c072d">

## with `pinned_at: 1` or not providing sort option at all
<img width="451" alt="Screenshot 2566-06-01 at 14 10 59" src="https://github.com/GetStream/stream-chat-js/assets/31316439/725eecc7-11f5-4bdf-9ed0-ee2245830f03">
<img width="671" alt="Screenshot 2566-06-01 at 14 11 15" src="https://github.com/GetStream/stream-chat-js/assets/31316439/068ffd70-c897-4a38-9ae0-9fbf60618248">

### it return all 29 messages

# Environment:
Getstream.io version: `stream-chat: 8.8.0` `stream-chat-react: 10.8.1`
Operating system: Mac OS
Programming language: Typescript, React
Other relevant details: on Chrome

**Comment by tbarbugli** [comment]
thank you for reporting this problem and provide so much useful information, we are going to look into this and let you know as soon as possible
