### ISSUE TITLE
Channel `updated_at` property not updated live

### ISSUE THREAD

**Issue by rchl** [GetStream/stream-chat-js#1139]
Channel object returned from `queryChannels` API contains a `channel.data.updated_at` property but this value is not updated live on sending new message to the channel for example.

I would expect either this value to be reactive or another one exposed in `channel.state.updated_at` (for example)  that is reactive (similarly to existing `channel.state.last_message_at`).

**Comment by rchl** [comment]
Some additional justification:
The [queryChannels API](https://getstream.io/chat/docs/node/query_channels/?language=javascript#channel-queryable-built-in-fields) supports the `updated_at` query parameter. So it's possible to sort channels by it initially but it's not possible to update channels order at runtime without re-querying all channels.

(I suppose setting up a `channel.updated` event might help here somewhat but that feels overkill for this purpose and just providing that value in the channel state would IMO make a lot of sense)

**Comment by MartinCupela** [comment]
Hello @rchl , channel `updated_at` timestamp is not updated when a message is sent. It is updated when one of the properties in `channel.data` is updated. You should listen to message.new event, for example, to update the order of channels. Or use the [`stream-chat-react` library](https://github.com/GetStream/stream-chat-react) that takes care of this out of the box.
