### ISSUE TITLE
Channel wise online status of a user 

### ISSUE THREAD

**Issue by NiteshKumar14** [GetStream/stream-chat-js#1140]
It would be better I we can see if the user is currently using a channel or not and show their online presence

Right now I came across watcher count and watchers property in channel but it does not shows the realtime watches to all the users , I don't know why is that the case

**Comment by MartinCupela** [comment]
Hello @NiteshKumar14 , the user online presence is updated via `user.watching.start` websocket event. Also you can access the list of users watching a given channel and their online state via `channel.state.watchers`. You can learn more about user presence in a [dedicated documentation article](https://getstream.io/chat/docs/react/presence_format/?q=.watchers).
