### ISSUE TITLE
Fix tests so that travis is clean for new changes

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-js#115]
For example, #108 is a simple change but travis test fails and then gives wrong impression and makes new contribution harder.

**Comment by tbarbugli** [comment]
Yes let's do this!

**Comment by tbarbugli** [comment]
I also suggest that we split our tests in unit tests and integration tests (and add a lot of unit tests)

**Comment by ferhatelmas** [comment]
SGTM
