### ISSUE TITLE
how to connect to a chat from server side for Bot app?

### ISSUE THREAD

**Issue by dcsan** [GetStream/stream-chat-js#1150]
how do i connect to a chat from server side to implement a bot? I want to listen/read and send/write messages.

I tried this

```
    await chatClient.connectUser(
      {
        id: AppConfig.ADMIN_BOT_ID,
        allowServerSideConnect: true,
      },
      userToken
    );

```

but get a warning

> Please do not use connectUser server side. connectUser impacts MAU and concurrent connection usage and thus your bill. If you have a valid use-case, add "allowServerSideConnect: true" to the client options to disable this warning.

is this the wrong way to do a server side connection? It seems to work.
how do I add to the 'client options' ?

If I don't `connectUser` I get this error:

> Error: StreamChat error code 4: QueryChannels failed with error: "Watch or ChatPresence requires an active websocket connection, please make sure to include your websocket connection_id"

**Comment by MartinCupela** [comment]
Hello @dcsan , [this blog](https://getstream.io/blog/implement-chatgpt/) article describes an example of how to forward the replies from an AI bot (in this case Chat-GPT) to the Stream's API.

We have also a dedicated website for the use-case: https://getstream.io/chat/solutions/ai-integration/
