### ISSUE TITLE
Persistent 'initial WS connection' Error on Client Side

### ISSUE THREAD

**Issue by gustiando** [GetStream/stream-chat-js#1156]
Hi,

I've recently been diving into a project involving Stream Chat where some of our users face challenges initiating chats. This issue has persisted over time, and despite various investigative efforts, the root cause remains difficult to track.

The consistent client-side error we encounter is:
```
{"code":"","StatusCode":"","message":"initial WS connection could not be established","isWSFailure":true}
```

The chat UI fails to render, and our attempts to reproduce this error haven't been successful yet.

We've speculated that the cause might be related to an ad-blocker, a firewall, or specific settings on the users' iOS mobile devices, but we're still in the dark about whether it's an environment-specific issue or something on our side.

Has anyone else come across this or have suggestions on how to best troubleshoot this?

Happy to provide more info if needed. Thanks in advance for any guidance.

**Comment by MartinCupela** [comment]
Hello, please check [this blog](https://support.getstream.io/hc/en-us/articles/16849509097367-Troubleshooting-initial-WS-connection-could-not-be-established-error) article that could apply to your setup.
