### ISSUE TITLE
Proposal: run lint as a part of travis

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-js#116]
To ensure it's always followed.

**Comment by tbarbugli** [comment]
good point; running `yarn run lint` should be enough since we already have this set up (probably good to return a nice error in Travis if $? != 0)

**Comment by ferhatelmas** [comment]
Sounds good. After #114 is merged,I will add it so that it could be run without any issues.

**Comment by ferhatelmas** [comment]
This is being done by now.
