### ISSUE TITLE
Pending Messages not Deleting

### ISSUE THREAD

**Issue by fbester** [GetStream/stream-chat-js#1168]
Hi there

I'm currently using the stream-chat API on the server side. 

When I call streamClient.deleteMessage(message_id, true) (Doing a hard delete here), after that, if I query the same channel the message was on, it's still in the channel state's pending_messages array. It's not even marked as deleted.

Funny enough, the response I get from deleteMessage shows the message as deletes (i.e.: it's type shows as 'deleted' and it even has a deleted_at timestamp). 

The only way I can actually get the channel to refresh is to completely disconnect from stream and to reconnect. 

Is this a caching issue maybe? I have triple checked that it's not a local state issue.

Regards.

**Comment by MartinCupela** [comment]
Hello @fbester , does the issue still persist? I could not replicate it. Seems similar to this one: https://github.com/GetStream/stream-chat-js/issues/1303
