### ISSUE TITLE
updateUser does not update client.user

### ISSUE THREAD

**Issue by earthlingstd** [GetStream/stream-chat-js#122]
I update user profile picture using the following snippet, but the updated info does not reflect in client.user
```
export async function updateUser(user) {
  // if (chatClient.user)
  const res = await chatClient.updateUser({
    id: user.uid,
    name: user.displayName,
    image: user.photoURL,
  })
}
```

**Comment by vishalnarkhede** [comment]
Duplicate of https://github.com/GetStream/stream-chat-js/issues/133 . Its in progress :)

**Comment by vishalnarkhede** [comment]
Hey @earthlingstd ,

This issue has been fixed. Once the user receives `user.updated` event, you will see the updated information in client.user object.

**Comment by vishalnarkhede** [comment]
Closing this issue now!! Please reopen if its not working for you!
