### ISSUE TITLE
Upload image for user

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-js#124]
Refer to this StackOverflow questions (and comments below it) https://stackoverflow.com/questions/57868440/how-to-upload-custom-image-when-create-new-channel?noredirect=1#comment102432706_57868440

The problem is that right now I cannot upload image without channel context. And because of it, I cannot upload image for user's avatar

**Comment by nhannah** [comment]
`client.sendFile` can be used to upload an image. For React Native as the initial question seems to ask you should look at the variety of libraries dealing with image access, our implementation can be found here: https://github.com/GetStream/stream-chat-react-native/blob/develop/package/native-package/src/index.js .
