### ISSUE TITLE
API calls to chat messages is skipping today. We cannot get last 24 hrs messages in GetStream service /search.

### ISSUE THREAD

**Issue by billnbell2** [GetStream/stream-chat-js#1297]
REST call even does not return today's messages.

curl --location --globoff 'https://chat.stream-io-api.com/search?user_id=svodotyka&connection_id=6638e11d-0a05-1777-0200-000000d25d55&api_key=XXXXXXXXX&payload={%22limit%22%3A100%2C%20%22filter_conditions%22%3A%20{%22id%22%3A%20%22t-003UG000007X0y5YAC-c-0057V00000AMZUUQA5%22%20}%2C%20%22message_filter_conditions%22%3A%20{%22created_at%22%3A%20{%20%22%24gt%22%3A%20%222024-05-09T23%3A00%3A00.048083Z%22%20}%20}}' \
--header 'Authorization: JUBK.eyJ1c2VyX2lkIjoic3ZvZG90eWthIn0.5dRsAriz0tzjWaJVBZXgIkpmi3JyRj_nN9XPTXzGuOU' \
--header 'Stream-Auth-Type: jwt'

“filter_conditions”: {“id”: “t-003UG000007X0y5YAC-c-0057V00000AMZUUQA5” }, “message_filter_conditions”: {“created_at”: { “$gt”: “2024-05-09T23:00:00.048083Z” } }}

Exclusive Resorts account.

This started happening on May 9.

**Comment by billnbell2** [comment]
We. cannot get the last 24 hrs of messages using /search. this started happening on 5/9, and each day we can get up to 24 hrs before now.


It is really difficult to get a response to get someone to chat with me/zoom with me, or anyone. The support ticket is not getting any resolutions.

For us this is a SEV1. Why? Because we rely on calling /search to get messages that are not responded to by our Concierge so we can escalate. Now we ar escalating all messages, since we cannot find any response - although they are there. Just /search returns [].

**Comment by MartinCupela** [comment]
Hello @billnbell2, Github issues is not the right place to report sev 1 issues. Please contact our customer support over the dedicated channel: https://getstream.io/contact/support/.
