### ISSUE TITLE
Create JWT error null

### ISSUE THREAD

**Issue by helveden** [GetStream/stream-chat-js#1299]
Hello i search to create token 

I try this : 
const serverClient = StreamChat.getInstance( apiKey, api_secret);  < **error here**
const token = serverClient.createToken(us); 

const client = new StreamVideoClient({ apiKey, user, token });
const call = client.call('default', callId);

but i have error here :

![image](https://github.com/GetStream/stream-chat-js/assets/6437218/233fc79f-3f50-4c00-bd99-856eb85226bd)

**Comment by helveden** [comment]
![image](https://github.com/GetStream/stream-chat-js/assets/6437218/7bbdc2fd-750b-4c5d-85a5-fb5761a2989a)

**Comment by helveden** [comment]
![image](https://github.com/GetStream/stream-chat-js/assets/6437218/772e9825-091f-4b17-8a48-1adcf5fbf891)

**Comment by szuperaz** [comment]
Hi,

Based on your screenshot you're trying to create a stream chat server client in a browser environment. This is a security problem, you should never put your API secret in a client application. The following code will only work in a Node.js environment:

```typescript
const serverClient = StreamChat.getInstance( apiKey, api_secret); < error here
const token = serverClient.createToken(us);
```

Your client application should receive the token from your own backend. This is the typical flow:
- Users log in to your application using your own login method, and then they receive a token they can use to call your application backend
- Your application backend has a protected endpoint that can issue Stream tokens
- You can create Stream tokens on the backend with the `createToken` method.

A sidenote: I can see that you're using our React Video SDK. For server-side video integrations you can use [our new node SDK](https://getstream.io/video/docs/api/#installation) which has support for both chat and video products.

I'm going to close this ticket, but feel free to reopen it if you have further questions.

**Comment by szuperaz** [comment]
If you don't yet have such backend, you can use Stream's static token generator: https://getstream.io/chat/docs/react/token_generator/ while in development mode. But you should never use static tokens in your production application, these are for testing only.

**Comment by helveden** [comment]
i use token in application on dashboard, and this token is available with
what the doc suggests. Am I wrong ?
Because in my case, it is a js error or jwt never has its object, it is
obvious when we compile the code during a yarn build.

Cordialy

Le jeu. 16 mai 2024 à 09:07, Zita Szupera ***@***.***> a
écrit :

**Comment by szuperaz** [comment]
Yes, you're doing what the [documentation suggests](https://getstream.io/chat/docs/javascript/tokens_and_authentication/?language=nodejs#generating-tokens), but in the wrong environment. Based on your screenshot you're running the token generation code in a browser, but it should be run in Node.js.

![Screenshot 2024-05-16 at 09 38 56](https://github.com/GetStream/stream-chat-js/assets/6690098/314d2ca9-9c0c-4eb1-9586-db66a22b8062)

Let me know if I missed something, and your application isn't a browser application.

**Comment by helveden** [comment]
I don't understand the report, I have to run a nodejs server outside of my
react code to have a video conference?
Maybe like a socket.io, only to make a token? I want to do it but I doubt
it will solve this problem. Maybe I can find a new solution to generate a
jwt (I lack experience on this subject by the way) in xhr from my react
client then initialize the object `new StreamVideoClient({ apiKey, user,
token }); `


Le jeu. 16 mai 2024 à 09:41, Zita Szupera ***@***.***> a
écrit :

**Comment by helveden** [comment]
Yes but the createToken method I can't reach it because the previous line
`const serverClient = StreamChat.getInstance(apiKey, api_secret);` contains
the error.

I will see for an alternative of creating jwt in my api php and sending it
to `new StreamVideoClient({ apiKey, user, token }); `



Le jeu. 16 mai 2024 à 11:08, Zita Szupera ***@***.***> a
écrit :

**Comment by szuperaz** [comment]
If you have a PHP backend, we have a PHP SDK for token generation: https://getstream.io/chat/docs/php/?language=php
