### ISSUE TITLE
Hard delete request fails but message is still deleted

### ISSUE THREAD

**Issue by joeporpeglia** [GetStream/stream-chat-js#1303]
Steps to reproduce:
1. Send a message in a channel
2. After the new message comes back over the websocket, delete it via `client.deleteMessage(..., true)`

The `DELETE` request takes a while (~8-10 seconds) and then fails with a 400 response including the error message `DeleteMessage failed with error: "Message with id ... doesn't exist""`. If I refetch the messages from the channel I see that the message was actually deleted, but no `message.deleted` event is sent to clients watching the channel.

**Comment by MartinCupela** [comment]
Hey @joeporpeglia ,

I have tested the behavior by rendering the below component as a child of `Chat` component:

```
const A = () => {
  const { client } = useChatContext();
  useEffect(() => {
    const { unsubscribe } = client.on('message.new', (e) => {
      if (e.message?.id) client.deleteMessage(e.message?.id, true);
    });

    return unsubscribe;
  }, [client]);

  return null;
};
```

What I observed was that the message was sent immediately without delay and the event also received without delay and subsequently hard-deleted.

Feel free to reopen the issue with a reproduction in a forked sandbox:

https://codesandbox.io/p/devbox/priceless-forest-g64slj

**Comment by joeporpeglia** [comment]
@MartinCupela this is still not working for us. The DELETE request is exactly the same as in your sandbox too. Is it possible that there's something configured differently with our account compared to the test sandbox you sent?

**Comment by MartinCupela** [comment]
@joeporpeglia please contact our support team to verify this. The best way to initiate the contact is via: https://getstream.io/contact/support/
