### ISSUE TITLE
How to get the list of channels user invited to

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-js#131]
Hi,

I need to display the list of channels user participate in (easy -> using channels query, with filter)

But how to get the list channels user invited to? There is not built-in query here https://getstream.io/chat/docs/#query_channels for it. It says I can filter by any custom fields but it's unclear how to do.

**Comment by EJohnF** [comment]
What's the timeline for a proper invite system? It's been a month already

**Comment by tbarbugli** [comment]
querying invites was added yesteday; @thesyncim can you point to an example?

**Comment by thesyncim** [comment]
hi @EJohnF,
you can now query channels by pending|accepted|rejected invites.
eg
```
let pendindInvitesChannels = await client.queryChannels({
			invite: 'pending',
		});
let aceptedInvitesChannels = await client.queryChannels({
			invite: 'accepted',
		});
let rejectedInvitesChannels = await client.queryChannels({
			invite: 'rejected',
		});
```

**Comment by EJohnF** [comment]
Great to hear! Thanks!

**Comment by EJohnF** [comment]
Still, invite system is not working 
That's how I create a new 1-1 channel:

```
const participantsId = [chatClient.user.id, partner.id].sort();
  const channelId = participantsId.join('-').slice(0, 63);
  const options = {
    name: 'Founder Chat',
    members: [chatClient.user.id],
    invites: [partner.id],
  }
  const newChannel = chatClient.channel('messaging', channelId, options);
  await newChannel.create();
```

on the partner account 
1) event `notification.invite` is not fires
2) All these arrays are empty
```
let pendindInvitesChannels = await client.queryChannels({
			invite: 'pending',
		});
let aceptedInvitesChannels = await client.queryChannels({
			invite: 'accepted',
		});
let rejectedInvitesChannels = await client.queryChannels({
			invite: 'rejected',
		});
```

**Comment by thesyncim** [comment]
@EJohnF are you setting the current user to `partner.id` in the client?

**Comment by EJohnF** [comment]
@thesyncim `partner.id` (for example `ab285a71-84d9-44ca-9040-4f85f73fbdd2`) - is the id of the other, I want to invite to created channel.
Current user is `chatClient.user.id` (for example `c5e0feda-2c30-4d16-9dac-67dcef78b65d `)

**Comment by thesyncim** [comment]
you need to add the invited user also as a member.
```
const participantsId = [chatClient.user.id, partner.id].sort();
  const channelId = participantsId.join('-').slice(0, 63);
  const options = {
    name: 'Founder Chat',
    members: [chatClient.user.id,partner.id],
    invites: [partner.id],
  }
  const newChannel = chatClient.channel('messaging', channelId, options);
  await newChannel.create();```

**Comment by EJohnF** [comment]
yes, now I receive notification and get the channel in pending array

**Comment by thesyncim** [comment]
closing this issue. feel free to reopen if you have any questions

**Comment by EJohnF** [comment]
yes, thanks for the help! 
Btw, it worth to update docs I think - otherwise, someone else might be stuck with the same problem. From the docs perspective, we don't need to send invited persons inside members list. https://getstream.io/chat/docs/#channel_invites

**Comment by EJohnF** [comment]
@thesyncim can you pls assist me - how to invite users later? 
In docs I see that I can add members `channel.addMembers` - but what to do when I need to trigger invites workflow (accept/reject etc)
