### ISSUE TITLE
user information does not update even if client.updateUser() executed successfully in client side

### ISSUE THREAD

**Issue by sharifMedici** [GetStream/stream-chat-js#133]
Hi i am facing a problem in getstram api (chat). when I update user information, i see **client.updateUser()**  executed successfully. but we do not get update user information in client.user. It remain previous old information. right now i am trying to update image url. It remains the old info until we reload the whole application (_cmd+R in ios, RR android simulator)_. but channel update work when we update channel information. 

Could you please tell me what is the reason for this ?

**Comment by vishalnarkhede** [comment]
Hey @sharifMedici This has been fixed in v1.1.5

So once you make a call to `updateUser` function, client will reflect the changes as soon as ` `user.updated` event is received.

**Comment by tschellenbach** [comment]
Android will handle this elegantly in the next release as well. (There is
an open pull request for this)

**Comment by sharifMedici** [comment]
[image: Screenshot 2019-10-10 at 16.09.51.png]

hi Thank you for your update but see heree screenshot, there is field
description:  see the value before update now string and after again
description still old,

Could you please check it ?

best regards
Sharif Hossain

**Comment by vishalnarkhede** [comment]
Hey @sharifMedici ,

So client will have the updated value once it receives `user.updated` event. 

```
client.updateUser({ id: 'user_id', description: 'New description' });
client.on('user.updated', () => {
    console.log(client.user.description); // 'New description'
})
```

Can you check if that works for you?

**Comment by sharifMedici** [comment]
we have talked already in slacked .Thank you.
