### ISSUE TITLE
[Feature request] Need "POST /channels" to support filter by members info

### ISSUE THREAD

**Issue by bdtren** [GetStream/stream-chat-js#1375]
At first, thanks guys for the great sdk, it helps me reduce a lot of time to implement chat feature!

I'm currently using the `stream-chat-react-native` to implement stream-chat to my app and stuck in an issue. My app have one search box to search chat by member name or chat name, so I need to use the `channelRenderFilterFn` to filter members:
```
  const customChannelFilterFunction = useCallback((channels: Channel<DefaultStreamChatGenerics>[]) => {
    return channels
    ?.filter(it => {
      return Object.values(it?.state?.members ?? {})
        ?.some(it => it?.user?.name?.toLowerCase()?.includes(query?.toLowerCase()));
    });
  }, [query]);


<ChannelList
          channelRenderFilterFn={customChannelFilterFunction}
...
/>

```
It is working just fine until user have a big list of chat channels with paging and the function only filter the fetched data.

So I create this feature request just to ask if you guy can support the channel filter to filter by member, just something like:

```
  const filters = {
      members: {
           name: {
              '$autocomplete': query
           }
      }
  }
```
I see a similar query in `channel.queryMembers` which is working, and after take a deep look I found the `POST /channels` request with the`filter_conditions` in this repo, so I think the update should be done from here.

Thank you for checking this feature request!

Best regards

**Comment by szuperaz** [comment]
Hi,

The `POST /channels` request already supports this usecase, this is the `filter_conditions` you can provide to it:
```
const query = '<search term>'
{
  type: 'messaging',
  $or: [
    { name: { $autocomplete: query } },
    { 'member.user.name': { $autocomplete: query } },
  ],
}
```

[Docs for reference](https://getstream.io/chat/docs/javascript/query_channels/?language=javascript#channel-queryable-built-in-fields)

I'm going to close this ticket, but feel free to reopen it if this is not what you had in mind.

Zita
