### ISSUE TITLE
[Enhancement/Feature Request] We should be able to update message custom properties using partiallyUpdateMessage

### ISSUE THREAD

**Issue by keshav-c** [GetStream/stream-chat-js#1376]
```
const updated = await client.partialUpdateMessage(originalMessage.id, {
    set: {
        custom: {
           prop1: 'val something'
        }
    }
});
```
The current behaviour is that, making the call `PUT /messages/{id}` from my server with this body, returns a 403 error 
```
{ 
  "code":17, 
  "message": "UpdateMessagePartial failed with error: \"field `custom` is reserved and cannot be updated \""
}
```
Once the message is sent, I am performing some calculations in my server and want to asynchronously update the custom tags. Please tell me if this behaviour can be changed. If not please point me to a workaround.

**Comment by keshav-c** [comment]
Hi. Thanks for your help earlier.
I need to clarify something else. Does the custom property need to exist on a message when partially updating? What about nested properties?

**Comment by szuperaz** [comment]
Hi,

This code snippet shows how to update a nested property (`message.custom.prop1`):
```
client.partialUpdateMessage(messageId, {set: {'custom.prop1': 'val something'}});
```

The above code example requires `message.custom` to already exist.
