### ISSUE TITLE
The userId argument is missing from the removeDevice method in types/stream-chat/index.d.ts.

### ISSUE THREAD

**Issue by sang2087** [GetStream/stream-chat-js#145]
Hi. I'm developing using Typescript.

I use addDevice and removeDevice methods for push notification, but I can't put userId in removeDevice method.
The userId argument is missing from the removeDevice method in types/stream-chat/index.d.ts.

The current code is shown below. 
`removeDevice(deviceId: string): Promise<APIResponse>;`
(types/stream-chat/index.d.ts, line 214)

I think it should change as follows.
` removeDevice(deviceId: string, userId: string | undefined): Promise<APIResponse>;`

please check this code.

**Comment by sang2087** [comment]
Hi, @vishalnarkhede ! thanks that you checked this issue.

I want to know when this issue will be merged.

**Comment by vishalnarkhede** [comment]
Hey @sang2087 ,

We will publish latest within next couple of days for sure. I will keep you posted :)

**Comment by vishalnarkhede** [comment]
Hey @sang2087 ,

Our ts declaration file has been fixed in v1.1.6. Please check and let us know if its resolved :)

**Comment by sang2087** [comment]
thanks a lot. this issue is resolved!!!
