### ISSUE TITLE
Issues when Caching Client Object (Server Side) - Converting circular structure to JSON 

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-js#150]
Hello people, i'm having an issue maybe its fixeable maybe not, the situation is the next, to avoid unnesesary calls to the getstream's api every time i need to instantiate a client from the sdk (server-side) i'm caching the object that results from new StreamChat and then setUser from the client (the fully connected client), the problem what i'm dealing with is the circular references inside the main client object, so i can cache it on my backend's memory but when i'm dealing with many clusters and doing process communications, i'm not able to send that object among them because it tries to stringify the json and the Converting circular structure to JSON error is thrown, is there any fix to this? I think replacing the circular references by my side wouldn't be the right way because i can screw up the whole library doing this, but maybe there's some patch by design to deal with this, because i want to avoid the latency gap everytime that the client connects to my backend and i make an instance for him to use in subsecuents requests, hence its more performant for me cache that object per client once and avoiding calling it multiple times, but it seems to work only with a in memory flat cache due to the nature of the error.

Remember i'm dealing with it backend side. 

I know this issue might be a bit outside of the scope of the library but given the need to cache it to avoid latency from backend side and also avoid hitting many times getstream's servers, maybe there's some workaround that brings light to my problem.

I hope the problem is understood.

Thanks again.

**Comment by tschellenbach** [comment]
Why would you need to cache the client object?

**Comment by aniciom** [comment]
I'm handling some operations from backend side, and i want to avoid the gap latency that brings me doing a new connection everytime I need to connect a client from my backend. Lets say i need to create a channel or add or remove a moderator or change permissions from my backend to a certain client instance, it adds me around 1s to the response plus the other actions i do in the db, so to avoid this matter i'm caching the client's object, its faster to me grab the client's instance from the cache than making a new connection to the getstream's servers.

**Comment by tbarbugli** [comment]
The initialization of the JS client takes microseconds; what is probably expensive is the first HTTP request since it creates the TCP connection + does TLS handshaking. For obvious reasons, you can't serialize a TCP connection to JSON :)

I am surprised it that creating the client every time adds 1s in your case. Where are your servers located?

I created a ticket #151 to get keep-alive for the same instance and to allow passing an httpsAgent as client option (this way you only need to initialize an httpsAgent and re-use it every time you create an API client)

**Comment by aniciom** [comment]
Thanks for the concern guys, Oh i see @tbarbugli why i can't stringify it. Look i've been doing some refactoring to the code i think it was my bad, i was doing some subtles but heavy operations hashing the passwords and doing an extra query to the db, i'm using nginx as reverse proxy and i didn't implement ssl yet, without the creation of the client the api's response maintains an average time among 150-250ms, adding the creation it goes up to 550-700ms (inside the app), in a standalone .js file using node from console it takes around 300-330ms.

Answering your question i'm currently testing it in a DO's droplet located in san francisco. It would have a better response time using EC2 at amazon?

Thanks

**Comment by tbarbugli** [comment]
the closest you are to AWS us-east the better performance you will get. I am going to close this issue for now.
