### ISSUE TITLE
Add support for Keep-Alive (Node)

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-chat-js#151]
Keep-Alive and connection pooling are both very useful (TLS handshake is expensive)

We should create an instance of axios and make sure it has decent keep-alive settings. Users of the library should be able to pass an http and https agent so that they can tweak things as they please (ie. connection pool settings, keep-alive TTL)

Note: last time I checked, Node.js would default to unlimited connection pools and without setting a fixed limit keep-alive was totally useless. Because TLS handshake is so slow, it should be very simple to validate that keep-alive and connection pooling is working.

See: https://github.com/axios/axios/issues/1846

**Comment by Bogdan-D** [comment]
@tbarbugli isn't it it already there? https://github.com/GetStream/stream-chat-js/blob/7aa2cf7677b5b895eb2528209a88681d7c920a2e/src/client.js#L75

**Comment by SloCompTech** [comment]
@tbarbugli Here I found possible [solution](https://gist.github.com/ccnokes/94576dc38225936a3ca892b989c9d0c6) using [agentkeepalive](https://www.npmjs.com/package/agentkeepalive) package
