### ISSUE TITLE
How to invite users to previously created channel

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-js#152]
In docs I see that I can add members `channel.addMembers` - but what to do when I need to trigger invites workflow (accept/reject etc)

**Comment by vishalnarkhede** [comment]
Hey @EJohnF ,

Does this help - https://getstream.io/chat/docs/#channel_invites

**Comment by EJohnF** [comment]
no, bcs this is invitation during channel creation. 
My question is when Channel was created sometime before, and I want to invite new users.

**Comment by vishalnarkhede** [comment]
@EJohnF We have an endpoint for adding members after channel creation - https://getstream.io/chat/docs/#channel_members

Is this what you are looking for?

**Comment by EJohnF** [comment]
As I wrote in the first message, I'm looking for `invite` member, not add him. It refers to this issue/resolution https://github.com/GetStream/stream-chat-js/issues/131

**Comment by vishalnarkhede** [comment]
Ohh ok. Pardon me for the confusion !! 

@thesyncim ??

**Comment by thesyncim** [comment]
@EJohnF we have this task in our backlog, should be implemented soon(probably this week),
i will ping you when is live

**Comment by EJohnF** [comment]
Hi @thesyncim any news about implementation?

**Comment by thesyncim** [comment]
hi @EJohnF this is now implemented in our backend.
take a look at the client tests https://github.com/GetStream/stream-chat-js/blob/2d25b55e0d19c7fca35db0f823f2ba48856c3c02/test/invites.js#L386.
Closing this issue. (feel free to reopen if you have issues)
