### ISSUE TITLE
Do you have any plans to support locale?

### ISSUE THREAD

**Issue by sang2087** [GetStream/stream-chat-js#156]
My service provides Korean, Taiwanese, Japanese, Chinese, etc. However, we cannot provide locale support only in stream-chat. I hope locale support is available as soon as possible.

Do you have any plans to support locale?

**Comment by mahboubii** [comment]
hey @sang2087, we do support locale in our UI SDKs, including our [React](https://github.com/GetStream/stream-chat-react#internationalisation) & [React-Native](https://github.com/GetStream/stream-chat-react-native#internationalisation) components.
We have also a [Translation](https://getstream.io/chat/docs/translation/?language=js) feature explained in the docs.
Please let us know if you are asking for something specific, will close the issue for the purpose of house cleaning.
