### ISSUE TITLE
Search for users

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-js#176]
I need to implement search functionality for users
I read the section for quiry users, especially filtering. 
But I don't see the way how I can implement "like" operator

Found a question in StackOverflow - https://stackoverflow.com/questions/43729199/how-i-can-use-like-operator-on-mongoose

How to call something like that in client-side?

**Comment by Bogdan-D** [comment]
Hi @EJohnF, 

We are not using mongodb, so the amount of operators are limited.
This is also because of performance reason, `LIKE` operator isn't fast, especially on large amount of users.
Can you provide usage example why it's required?

**Comment by EJohnF** [comment]
Hi @Bogdan-D 

Yes, I need to implement search functionality for users (I want to allow to user to chat with anyone else)
And I want to update user's list along with user typing (nice UX experience), plus user may not know the exact name

**Comment by Bogdan-D** [comment]
@EJohnF 
for this kind of functionality we have `$autocomplete` operator.

So you can try to use `{name: {$autocomplete: "name"}}`. 
Also currently it's allowed to use autocomplete only for one field. (so you should chose will it be `name` or `username`).
