### ISSUE TITLE
Can't resolve isomorphic-ws 

### ISSUE THREAD

**Issue by leibowitz** [GetStream/stream-chat-js#179]
Apologies if this is not the right place, but I'm trying to understand why I'm getting this error when running tests (via karma/puppeteer/chromium)

```
ERROR in ./node_modules/stream-chat/dist/browser.es.js
--
153 | Module not found: Error: Can't resolve 'isomorphic-ws' in 'node_modules/stream-chat/dist'
```

The code simply import `stream-chat`.
```
import { StreamChat } from 'stream-chat';
```

This works fine when running in the browser on local dev, i.e. webpack-dev-server.

Adding `isomorphic-ws` explicitly to my `package.json` seems to fix the issue. But I fail to understand why I need to add it, since it's already included because it's specified in `stream-chat-js` dependencies ([package.json](https://github.com/GetStream/stream-chat-js/blob/923347588ea07ce1a195a77ebefdde64bbb4769f/package.json#L42) and [yarn.lock](https://github.com/GetStream/stream-chat-js/blob/47d5a40630fe96f243e8b7fc786f858002a9bba3/yarn.lock#L3271))

Is it because it's defined as an [externalPackage](https://github.com/GetStream/stream-chat-js/blob/dc91e086e8a0a9fcab9ac4763989d697668378e8/rollup.config.js#L22) in rollup? and since the browser version is basically not using the dist/compiled, it builds everything and that resolves isomorphic-ws just fine? 

That's the only reasonable explanation I have, that something is wrong in the built version of stream-chat

**Comment by mahboubii** [comment]
Thanks for reporting this, this is most likely an issue with your dependency manager. `isomorphic-ws` is not a [devDependency](https://github.com/GetStream/stream-chat-js/blob/master/package.json#L46) and should be installed automatically when you install the `stream-chat` from npm, make sure you clean the node_modules folder and install a fresh version of the package. 
Let us know if you still had any issues.

**Comment by leibowitz** [comment]
Maybe you failed to read the entire message, but my problem isn't with the package not being installed, but rather with the built version of `stream-chat-js`, aka with the `dist/browser.es.js`
And again, this is only an issue when running tests

**Comment by mahboubii** [comment]
@leibowitz do you have a small set up for us to reproduce this issue locally?

**Comment by leibowitz** [comment]
This is from a year ago @mahboubii, so I'm afraid I won't be able to give any more details

**Comment by leibowitz** [comment]
The only thing I can say, is that I only have this issue with `yarn` (v1.17.3)

When installing via `yarn`, the `node_modules` is missing the package `isomorphic-wc`, but it is present inside `node_modules/stream-chat/node_modules`

I also tried with the latest v1.22.10, but same issue.

Whereas when using `npm` v6.14.4, `isomorphic-wc` is installed in the main project `node_modules` directory, and everything works as expected.

**Comment by mahboubii** [comment]
can you try with the latest version of the yarn? I just did a fresh install with yarn `v1.22.5` and I can see the `isomorphic-ws` is present under `node_modules` and `node_modules/stream-chat` is empty.

**Comment by leibowitz** [comment]
I mentioned I tried with v1.22.10, so yes, I already tried with the latest.

Though at the time (and that is the version I am trying here) `stream-chat` version was on 1.1.7. Not sure if that matters, to be honest

**Comment by leibowitz** [comment]
yeah even when trying with `stream-chat` v2.4.0, the issue remains

**Comment by leibowitz** [comment]
Anyway, I guess I'm just wasting your time. As I said, this is from a year ago, and my solution was to specify the `isomorphic-wc` dependency explicitly, which was a good enough workaround. I just created the issue in here in case someone else was facing the same problem. And since you've already closed the issue, I guess this is it.

**Comment by mahboubii** [comment]
This is an interesting issue, I don't see any specific problem with rollup configuration. The fact that installing the lib using `npm` resolves it means that either our `yarn.lock` file is not generated correctly or this is an issue with `yarn` itself. 
anyway, I will regenerate the `yarn.lock` and make a new release, hopefully, this fixes the issue.

Thank you again for fast responses on this one and apologies for not addressing this sooner.

**Comment by leibowitz** [comment]
Yeah, I cannot explain it either. I tried removing the `yarn.lock` file in the project and run yarn again, and it seems to have done the trick. Even though `isomorphic-ws` was specified in it, and that hasn't changed. Of course removing the yarn.lock results in all the packages being updated. So it would be impossible to know what package and version specifically was causing this.

**Comment by leibowitz** [comment]
also the fact that using the version compiled via webpack locally didn't seem to result in this error, but when running the tests via karma it did.

**Comment by mahboubii** [comment]
This is indeed a weird case. Do you use the same webpack configuration for Karma?

**Comment by leibowitz** [comment]
Not really. In karma things are configured slightly differently. There is a webpack section in it, re-using some of the webpack config, but yeah it's complicated to explain.
Anyway, as I said, no need to investigate further. It's probably due to something particular to my setup. And since I found a workaround, I didn't really spend too much time trying to figure this one out

**Comment by interfaith** [comment]
i got it also Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'isomorphic-ws' imported from

**Comment by ilyakonrad** [comment]
Having the same issue with `pnpm`. Worked fine with `yarn` v1 and v4. Adding the package to the `package.json` helps.

<img width="874" height="581" alt="Image" src="https://github.com/user-attachments/assets/92a9b89a-617b-444b-96bc-4b4dba908f0b" />
