### ISSUE TITLE
Can‘t find variable:Buffer

### ISSUE THREAD

**Issue by barczaG** [GetStream/stream-chat-js#183]
I'm using expo. For some reason the `Buffer` polyfill wasn't included in the build.  I was able to fix it by installing `buffer` and adding the following line to `node_modules/stream-chat/dist/browser.js` 
`global.Buffer = global.Buffer || require('buffer').Buffer`

**Comment by vishalnarkhede** [comment]
Hey @barczaG , this will be fixed soon. Moving this issue to `stream-chat-js`, its coming from js client.

**Comment by capacitivellc** [comment]
My temporary workaround.

```yarn add buffer```

add
 
```global.Buffer = global.Buffer || require('buffer').Buffer```

to the top of the root app index.js
