### ISSUE TITLE
Does stream support iOS 13 push notifications?

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-js#191]
Push notifications were working on friday. Today morning we updated testing phone to iOS 13+ and push notifications stops working:
seems to be related to https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc

In the dashboard I see that push notification claims to be delivered, but I don't see them on the phone

**Comment by tbarbugli** [comment]
perhaps better if you move this to the React Native or the Swift SDK Github (this one is the core JS client repo)
