### ISSUE TITLE
Missing types for partialUpdateUser/partialUpdateUsers

### ISSUE THREAD

**Issue by type** [GetStream/stream-chat-js#210]
There are no ts typings for the partialUpdateUser and partialUpdateUsers methods

**Comment by type** [comment]
Additionally, there is an invalid typing https://github.com/GetStream/stream-chat-js/blob/master/types/stream-chat/index.d.ts#L345 (`bool` should be `boolean`)

**Comment by shodgetts** [comment]
Hi! Thanks for bringing this to our attention. We'll get someone to address these issues shortly.

**Comment by tbarbugli** [comment]
@vishalnarkhede looks like an easy one to fix, can you have a look?

**Comment by shodgetts** [comment]
Bool/boolean issue is fixed by was the TS typings fixed?

**Comment by ferhatelmas** [comment]
@shodgetts yes, with #213. Unfortunately, @vishalnarkhede didn't split fixes.

@type it's fixed and released as `v1.2.3`, let us know if all is good.
