### ISSUE TITLE
Invalid type "bool" set as the return type for function

### ISSUE THREAD

**Issue by pmbanugo** [GetStream/stream-chat-js#216]
https://github.com/GetStream/stream-chat-js/blob/e1f994fb4295ece73fa033357b270df3646c7853/types/stream-chat/index.d.ts#L345

The line above is causing my code not to compile. It expects boolean as type and not bool. I see there's a mix of using boolean and bool type in this file.

Also making reference the links below. 

1. https://github.com/pmbanugo/angular-conversational-ui-tutorial/blob/1fac384de42373035101a6acf5151f286a6ac585/src/app/app.component.ts#L66  

2. https://github.com/pmbanugo/angular-conversational-ui-tutorial/blob/1fac384de42373035101a6acf5151f286a6ac585/src/app/app.component.ts#L68   

The first one is an optional object but the way it is Typescript expects me to pass a third argument for  `chatClient.channel("commerce", "conversational-ui");`.

The second one in the docs doesn't say that it requires parameters but typescript wants me to put a value for that. I can pass empty objects to make them work but the main blocker for me is the bool type used in the fyour type script definition

**Comment by ferhatelmas** [comment]
Related to https://github.com/GetStream/stream-chat-js/issues/210#issuecomment-569816169

**Comment by tbarbugli** [comment]
this is fixed on master branch; we are going to release a new version today which includes other improvements to typescript

**Comment by pmbanugo** [comment]
awesome!
