### ISSUE TITLE
Documentation for queryUsers doesn't match

### ISSUE THREAD

**Issue by AgusRdz** [GetStream/stream-chat-js#218]
Currently the documentation related to `queryUsers` indicates that `presence` by default is `false` but reviewing the source code I found that the real value is `true`.

For reference:
https://github.com/GetStream/stream-chat-js/blob/master/src/client.js#L809
https://github.com/GetStream/stream-chat-js/blob/master/src/client.js#L822

https://getstream.io/chat/docs/js/#query_users

![image](https://user-images.githubusercontent.com/6268687/71999032-4c543100-3206-11ea-912e-5c791a0829ff.png)

**Comment by tbarbugli** [comment]
@tschellenbach what do you think makes more sense to fix? default client behaviour or docs?

**Comment by tschellenbach** [comment]
what's the default for queryChannels? I think they should probably both default to false since most people won't use the user presence events.

**Comment by ferhatelmas** [comment]
It's false for `queryChannels` so updated via #233.
