### ISSUE TITLE
client.disconnect doesn't always return a promise

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-js#235]
![image](https://user-images.githubusercontent.com/265409/72546229-a2008d00-3847-11ea-9d3d-62d53f5d4312.png)

client.disconnect doesn't return a promise if wsConnection is not defined...

**Comment by tschellenbach** [comment]
2 more issues...

![image](https://user-images.githubusercontent.com/265409/72546776-9e213a80-3848-11ea-9882-50061c45f3b2.png)

**Comment by tschellenbach** [comment]
wsConnection.disconnect also doesn't seem entirely correct. I think the onClose event isn't fired if the socket is already closed... That might explain why Kane gets the above error

![image](https://user-images.githubusercontent.com/265409/72547046-17b92880-3849-11ea-9071-a759dd6be1af.png)

**Comment by kanekv** [comment]
Also, awaiting on `client.disconnect` is timing out.

**Comment by kanekv** [comment]
Some additional info: this happens in node.js every time.
