### ISSUE TITLE
typescript typing for .sendFile and .sendImage only accepts string

### ISSUE THREAD

**Issue by kanekv** [GetStream/stream-chat-js#237]
Right now typescript definitions for `.sendFile` and `.sendImage` only accept strings.

**Comment by tbarbugli** [comment]
@jaapbakker88 is working on this https://github.com/GetStream/stream-chat-js/pull/238

**Comment by jaapbakker88** [comment]
@kanekv I have updated the types to also accept a Buffer as the only argument.
