### ISSUE TITLE
File Upload API doesn't work in node.js

### ISSUE THREAD

**Issue by kanekv** [GetStream/stream-chat-js#239]
There are multiple problems in this piece of code: https://github.com/GetStream/stream-chat-js/blob/master/src/client.js#L564-L579.

1. Buffer check doesn't work properly for buffers created other than fs.createReadStream
2. It's using `File` which doesn't exist in node.js
3. To accept buffers `data.append('file', fileField);` should accept mimetype as 3rd argument.

**Comment by kanekv** [comment]
@ferhatelmas , @jaapbakker88 suggested that you would be the best person to check these issues.

**Comment by ferhatelmas** [comment]
@kanekv thanks for the great details, we will check with @jaapbakker88 soon.
