### ISSUE TITLE
Direct Message: how to display the message receiver's name as channel name

### ISSUE THREAD

**Issue by yyan1998** [GetStream/stream-chat-js#248]
I am currently creating the direct messaging feature using GetStream's One to One conversation. Right now I can only set a single name for the direct message channel. For example, A sent a message to B and the created channel between A and B is initially named to B. If, when A and B both enter the channel, I want A to see the channel name as B and B sees the channel name as A, how can I implement this?

**Comment by vishalnarkhede** [comment]
@yyan1998 you have members list available in `Channel`. On UI side, you can use this array and current user of app (chatClient.user) to decide what name to display for channel.

**Comment by vishalnarkhede** [comment]
@yyan1998 closing this for now. Please reopen or get in touch with our support if you have any more questions!

**Comment by rakeshmsuthar** [comment]
> 

I want to show the user name on ChannelList. How do I get the members list in ChannelList

**Comment by devth** [comment]
Came here with the same question. Looks like it's still unanswered!

**Comment by vongohren** [comment]
I guess this is given that you have given the user a name in the member sync itself? If not it shows the ID. Which you might be able to use to show the name if you have that data available other places.
