### ISSUE TITLE
Trivial TS issue with StreamChat Constructor

### ISSUE THREAD

**Issue by fbartho** [GetStream/stream-chat-js#250]
https://github.com/GetStream/stream-chat-js/blob/64e9fbb48bc3188b0db91cd0aa0852fd0521129a/types/stream-chat/index.d.ts#L156

I believe that line should instead read:
```diff
- constructor(key: string, secretOrOptions?: string, options?: StreamChatOptions);
+ constructor(key: string, secretOrOptions?: string | StreamChatOptions);
+ constructor(key: string, secretOrOptions?: string, options?: StreamChatOptions);
```

I haven't tested it in that format (method overloads), but I'd be equally happy with:
```typescript
constructor(key: string, secretOrOptions?: string | StreamChatOptions, options?: StreamChatOptions);
``` 
This is simpler, and engineers should be able to figure out that they're not supposed to pass the options twice, but I guess it's not as explicit.

**Comment by vishalnarkhede** [comment]
@fbartho fixed in `v1.6.0`
