### ISSUE TITLE
I'm getting error when using the SDK in the browser

### ISSUE THREAD

**Issue by dongido001** [GetStream/stream-chat-js#259]
I'm getting error when using the SDK in the browser. 

When I use the SDK in the script tag:

<script src="https://cdn.jsdelivr.net/npm/stream-chat"></script>

I get the following error on the console:

<img width="658" alt="Screenshot 2020-02-14 at 5 57 16 PM" src="https://user-images.githubusercontent.com/18917158/74551462-82967600-4f53-11ea-9f7a-5cfc56e0787e.png">

I have also tried using: "https://cdn.jsdelivr.net/npm/stream-chat/dist/browser.full-bundle.min.js" but then I get another error message on the console:

<img width="688" alt="Screenshot 2020-02-14 at 5 59 44 PM" src="https://user-images.githubusercontent.com/18917158/74551631-d5702d80-4f53-11ea-982c-665efb8248f5.png">

Let me know what I am doing wrong, thanks! @tbarbugli @pterk ...

**Comment by pterk** [comment]
@dongido001 look into https://requirejs.org/ or check out a more highlevel tutorial here: https://getstream.io/chat/react-chat/tutorial/

**Comment by tbarbugli** [comment]
@pterk this is an actual bug; the browser full bundle should be `umd` and not depend on require.

**Comment by tbarbugli** [comment]
@vishalnarkhede @jaapbakker88 we used to support this. ie. https://cdn.jsdelivr.net/npm/stream-chat@1.3.2/dist/browser.full-bundle.min.js works just fine

**Comment by tbarbugli** [comment]
@dongido001 in the meantime you can use an older version of the SDK (https://cdn.jsdelivr.net/npm/stream-chat@1.3.2/dist/browser.full-bundle.min.js)

**Comment by tbarbugli** [comment]
1.2.3 seems to be the first release with this problem

**Comment by dongido001** [comment]
Thanks @tbarbugli ! works for me now

**Comment by vishalnarkhede** [comment]
@dongido001 browser bundle has been fixed. now in `v1.3.3`.
