### ISSUE TITLE
couple of TS issues

### ISSUE THREAD

**Issue by davinchee** [GetStream/stream-chat-js#281]
- activeChannels does not exist in the typings file, but exists on the ChatContextValue's client.
- users does not exist in the typings file, but exists on the ChatContextValue's client.state. Here are the properties on a user:
```
export interface IClientStateUser {
  readonly banned: boolean;
  readonly created_at: string;
  readonly id: string;
  readonly image: string;
  readonly last_active: string;
  readonly name: string;
  readonly online: boolean;
  readonly role: string;
  readonly updated_at: string;
}
```

You may want to account for the functions on the user, as well as indicating that more properties can be added (or at least add instructions for how => extending from the Stream User, e.g. interface ICustomUser extends IStreamUser).
- setActiveChannel on ChatContextValue expects an `event: React.SyntheticEvent<Element, Event>` as its second parameter, but it works as expected without it. Should probably make this a optional (?) param.

**Comment by vishalnarkhede** [comment]
THanks @davinchee for bringing this up. I will look into it and update ts file if needed.

**Comment by mahboubii** [comment]
hey, @davinchee, the library is now fully rewritten in Typescript so the missing types should be fixed, we also have generics which allows you to extend the types based on your data. 
Going to close this issue, let us know in case your issue still exists.
