### ISSUE TITLE
Channels query filters

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-js#286]
Hello,

In our application we want to add a reach variety of options to filter and search channels. 
By investigating docs and trying to implement some of them I stuck and need your help to proceed.

1 - How can I do partial search by channel field?

I need to query channels by `name` field using partial search. How can I achieve this?

Query operators provided in [docs](https://getstream.io/chat/docs/query_syntax/?language=js) doesn't mention any relevant operator.

Currently I only managed to achieve search by total equality with query string: 
`const filter = { members: { $in: [<memberId>] }, name: <query> };`

2 - How can I filter channels by member name, instead of id?

Thanks in advance

**Comment by thesyncim** [comment]
hi @khanilov,

we are about to introduce `{name:{"$q":"partialMatch"}}`

I will try to get this change live tomorrow.(i will keep you in the loop)

**Comment by khanilov** [comment]
Any updates on this?

**Comment by khanilov** [comment]
Hey @thesyncim , I see that `$q` operator accepted by API. But I receive next error:
```
{
    "code":4,
    "message":"QueryChannels failed with error: \"search is not enabled for field channels.name.\"", 
    "StatusCode":400,
    "duration":"0.00ms"
}
```

My filter conditions:
```
{
   "members": {
      "$in": [ "931c62ba-59c7-41a4-905a-68443f2cd467" ]
   },
   "name": { "$q": "te" } 
}
```

Is there any timetable on this feature?

**Comment by vishalnarkhede** [comment]
@khanilov do you still need help with this?

**Comment by khanilov** [comment]
@vishalnarkhede Yes. Native SDK's support for filtering channels by channel name and members names would be awesome.

**Comment by vishalnarkhede** [comment]
Hi @khanilov ,

Sorry for delayed response. You use following filter condition for your usecase:

```js
{
   "members": {
      "$in": [ "931c62ba-59c7-41a4-905a-68443f2cd467" ]
   },
   "name": { "$autocomplete": "te" } 
}
```

**Comment by thesyncim** [comment]
@khanilov it's also possible to search members by name.

```js
channel.queryMembers({name:$autocomplete:'bob'},{created_at:-1},limit:10,offset:0)
```

**Comment by khanilov** [comment]
@vishalnarkhede Works like a charm, thanks.

**Comment by khanilov** [comment]
@thesyncim Thanks for the info!
