### ISSUE TITLE
Push token not removing 

### ISSUE THREAD

**Issue by kusalshrestha** [GetStream/stream-chat-js#297]
The delete request returns success but does not remove the token from the stream.
```
await client.removeDevice(
    TOKEN, 
    ID
)
```

```
Request URL: https://chat-us-east-1.stream-io-api.com/devices?user_id=xxx&id=xxx&api_key=xxx
Request Method: DELETE
Status Code: 200 OK
```

**Comment by bogdan-getstream** [comment]
@kusalshrestha can you tell us `app id`, `user id`, `device id` for debugging please?

**Comment by vishalnarkhede** [comment]
@kusalshrestha do you still need help with this? If yes, please reopen the ticket!!
