### ISSUE TITLE
Newbie need some help

### ISSUE THREAD

**Issue by JasonBenichou** [GetStream/stream-chat-js#306]
Hello everyone,

I am a little lost, sorry if this is not the right place to ask this, but I would like to know if someone would have the capacity (and the good will) to explain to me or to give me some advice for them. following points.

Currently, I develop the authentication of my users thanks to firebase, I store all the data thanks to firestore. I now find myself blocked.

1) What is the correct methodology for creating a getStream user on the server side during authentication? or at another time? On the application side?
2) Does anyone know how to find all of the user information directly from the server side (via the firebase functions)?

If someone has the patience to help me via the forum or via Whatsapp, it would be really nice of them and I will be very grateful!

**Comment by jhetuts** [comment]
Checkout the blog section. I used to check some implementations there. Here's the [link](https://getstream.io/blog)
