### ISSUE TITLE
Not possible to leave a group chat when using .removeMembers()

### ISSUE THREAD

**Issue by kgstaley** [GetStream/stream-chat-js#311]
When creating our chat app, we allow for users to create distinct channels wherein we do not pass a channel_id upon channel creation to allow for unique cids. However, we also want to give users the ability to leave a group chat, as well. After running await channel.removeMembers([memberIds]), I get the error of 
```
, [Error: StreamChat error code 4: UpdateChannel failed with error: "cannot add or remove members in a distinct channel, please create a new distinct channel with the desired members"]
```

And after looking through the testing files of the repo, it appears as though leaving / removing members of distinct channels is not allowed at all, is this correct? See: https://github.com/GetStream/stream-chat-js/blob/813f4fc15ee0f1179ab84df5fa71369fb1a2d2d0/test/channels.js 

If so, how would you recommend we go about allowing users to leave channels / have the ability to add people to channels. Does this mean that we will be required to pass our own generated ID to the creation of channels in order to be able to perform .addMembers and .removeMembers? Thanks.

**Comment by WitleyInc** [comment]
I'm having the same problem as well. It returns the error, ```Error: StreamChat error code 4: UpdateChannel failed with error: "cannot add or remove members in a distinct channel, please create a new distinct channel with the desired members"```

**Comment by WitleyInc** [comment]
My app also creates the channel without passing our own generated ID. I wonder why adding or removing members are not allowed in a distinct channel (assuming that the definition of a distinct channel is creating a channel using stream's generated IDs)

**Comment by tbarbugli** [comment]
@walberty if you use distinct channels the list of members is the identifier of the channel, changing the list would be the same as changing its identity. 

You should use distinct channels (channels without IDs) if you want to ensure one conversation for a set of users; if you expect the list of members to change then the recommended approach is to give the channel an ID from your end (ie. uuid4 is a good choice).

Note: you can use `channel.hide()` to hide a channel for a member.

**Comment by vishalnarkhede** [comment]
@WitleyInc @kgstaley closing this for now. Please reopen if you still need help with this!!
