### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by M1chaelChen** [GetStream/stream-chat-js#320]
In the documentation (https://getstream.io/chat/docs/tokens_and_authentication/?language=js#token-expiration), I'm not able to find an example for token expiration for JavaScript. Is there an API included for that in this library?

**Comment by ferhatelmas** [comment]
:eagle: eyes - #319 is addressing it. Stay tuned.

**Comment by ferhatelmas** [comment]
@vishalnarkhede assigned to you since your PR handles it.

**Comment by vishalnarkhede** [comment]
@M1chaelChen please use `1.10.0` for token refresh functionality - https://github.com/GetStream/stream-chat-js/blob/master/docs/userToken.md
