### ISSUE TITLE
Get full channel's unread messages count

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-js#336]
[Docs](https://getstream.io/chat/docs/unread_channel/?language=js#unread-messages-per-channel) suggest to use channel.countUnread() to retrieve the number of unread messages in particular channel.

But in reality this method only count unread messages from fetched ones: there may be more. 
https://github.com/GetStream/stream-chat-js/blob/fe91fdf4d89a993f9cd32da3fd6d236682431567/src/channel.js#L652-L673

Is there any way to get real channel's unread count?
Thanks.

**Comment by vishalnarkhede** [comment]
Hey @khanilov we are yet to update this method. We recently added unread count as part of api response for query channel. The number that you are looking for is already present at `channel.state.read[user_id].unread_messages`

**Comment by khanilov** [comment]
Should this field update through the time? Because it seems not.
Or it's only for initialising purposes?
