### ISSUE TITLE
Are BuiltinPermissions outdated?

### ISSUE THREAD

**Issue by rubenvereecken** [GetStream/stream-chat-js#362]
Because the permission objects that contain those seem to be ignored by Stream. I suppose perhaps they're an old version, the difference between eg `UpdateAnyMessage` and `UpdateOwnMessage` now handled by the `Permission.owner` flag? Replacing values from this enum with raw strings stolen from the default permissions of pre-defined channel types did the trick for me.

If so, I might be able to chip in.

**Comment by shodgetts** [comment]
Hello, we've had considerable work done on our permissions system since this ticket was submitted. Can you let us know if you're still experiencing issues here? If so, support@getstream.io would love to hear from you! 
-Big Steve
