### ISSUE TITLE
StreamChat.off method has duplicated incorrect types

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-js#367]
I think this line should be removed as its returning the wrong types https://github.com/GetStream/stream-chat-js/blob/c596a3d83849f681f0f83f50d73a6ff224038379/types/stream-chat/index.d.ts#L230

Correct types in the line underneath

cc @tbarbugli

**Comment by SuvidhaKapse** [comment]
hello, i want to use this code. and i am not able to run this code in visual code.
i followed below steps : 
install node js, visual code,
clone code in folder
npm install stream-chat

but its not working.. please guide me how should i run this code. i have never run pure js code. i am working in .net. but i want to learn getStream in js

**Comment by jaapbakker88** [comment]
@alexlopezit these types are both correct, you can either send a callback as the only param, or a string and callback.  Are you running into an issue because of this?

**Comment by alexlopezit** [comment]
@jaapbakker88  I am using a custom version of [this](https://github.com/GetStream/stream-chat-react/blob/v1.2.5/src/components/ChannelList/hooks/useNotificationRemovedFromChannelListener.js) to override some functionality and Typescript is not happy about it.

This is the Typescript version of the hook

```
import React from 'react'
import { Channel, Event } from 'stream-chat'

import { MessagingContext } from '@Contexts/Messaging'

export const useNotificationRemovedFromChannelListener = (
  setChannels: React.Dispatch<React.SetStateAction<Channel[]>>
) => {
  const { client } = React.useContext(MessagingContext)

  React.useEffect(() => {
    const handleEvent = (e: Event) => {
      setChannels(channels => channels.filter(channel => channel.cid !== e.channel.cid))
    }

    client.on('notification.removed_from_channel', event => handleEvent(event))

    return () => {
      client.off('notification.removed_from_channel')
    }
  }, [])
}
```

And this is that client.off is expecting
![image](https://user-images.githubusercontent.com/1654135/86978773-0717b880-c1c3-11ea-9ee3-9f8289a47dd7.png)

Therefore I am getting this error

![image](https://user-images.githubusercontent.com/1654135/86978830-2878a480-c1c3-11ea-9a8d-9ff8b564196b.png)

**Comment by alexlopezit** [comment]
Actually, just tried this and it seems to work better
```client.off('notification.removed_from_channel', null)```

Passing `null` as the second argument, would this be a valid implementation for the `client.off`?

**Comment by vishalnarkhede** [comment]
Hi Alex,

This is a wrong syntax actually, which are currently fixing in this PR - https://github.com/GetStream/stream-chat-react/pull/396

Ideally it should be as following:

```
import React from 'react'
import { Channel, Event } from 'stream-chat'

import { MessagingContext } from '@Contexts/Messaging'

export const useNotificationRemovedFromChannelListener = (
  setChannels: React.Dispatch<React.SetStateAction<Channel[]>>
) => {
  const { client } = React.useContext(MessagingContext)

  React.useEffect(() => {
    const handleEvent = (e: Event) => {
      setChannels(channels => channels.filter(channel => channel.cid !== e.channel.cid))
    }

    client.on('notification.removed_from_channel', handleEvent)

    return () => {
      client.off('notification.removed_from_channel', handleEvent)
    }
  }, [])
}
```

**Comment by vishalnarkhede** [comment]
@alexlopezit ^^

**Comment by alexlopezit** [comment]
Thanks for that @vishalnarkhede, I'll update my code.
