### ISSUE TITLE
Cannot npm install from GitHub

### ISSUE THREAD

**Issue by rubenvereecken** [GetStream/stream-chat-js#395]
I need to be able to install from my fork on GitHub because it contains patches that are being merged too slowly in this repository.

```
npm i GetStream/stream-chat-js
```

fails with the following:
```
npm ERR! prepareGitDep npm ERR! code E404
npm ERR! prepareGitDep npm ERR! 404 Not Found - GET https://registry.npmjs.org/@samverschueren%2fstream-to-observable - Not found
npm ERR! prepareGitDep npm ERR! 404 
npm ERR! prepareGitDep npm ERR! 404  '@samverschueren/stream-to-observable@^0.3.0' is not in the npm registry.
npm ERR! prepareGitDep npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! prepareGitDep npm ERR! 404 It was specified as a dependency of 'listr'
npm ERR! prepareGitDep npm ERR! 404 
npm ERR! prepareGitDep npm ERR! 404 Note that you can also install from a
npm ERR! prepareGitDep npm ERR! 404 tarball, folder, http url, or git url.
```

I haven't been able to work around it. Any advice?

**Comment by tbarbugli** [comment]
we just noticed the same on our CI, we are looking into a solution (might also be a temporary issue with yarn/npm)

**Comment by tbarbugli** [comment]
npm is broken atm, looks like they are working on a fix so this should go away pretty quickly

![image](https://user-images.githubusercontent.com/88735/89525145-0edc7400-d7e6-11ea-804b-4c6a6cb1291e.png)

**Comment by rubenvereecken** [comment]
Actually that's what it did look like to me from the error message -- I should have mentioned. The package definitely seemed to exist. Then again, I could still install the usual way (`npm install stream-chat`) so I wasn't sure. Let's wait this one out for a bit then.

**Comment by tbarbugli** [comment]
works now
