### ISSUE TITLE
queryMembers does not retreive the creator of the channel?

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-js#396]
# Description

Hello, nice refact! (The react one, btw there was breaking changes in minor releases) 
Not sure it's the best place but apparently, queryMembers does not retreive the first user/creator/owner/moderator (I don't remember the role name) of the channel, I have all other users & initial presences but this one (it's not depending of the current user). 
(right now I use client.queryUsers with his id to get his initial presence)
Or did I miss something? Thank you! 

gz#5199

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5199'>Zendesk ticket #5199</a>:<br><br>It will return the channel creator if you add them as a member. Are you doing so?

**Comment by lr-mjaouen** [comment]
I will check thank you, we handle it on our side so probably not. 
You don't add it at the creation? A reason?

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5199'>Zendesk ticket #5199</a>:<br><br>We don't, it's just not default behavior of the API. We give you the flexibility to add the channel_creator as a member or not. There are use cases that require both.

- Stream Support

**Comment by lr-mjaouen** [comment]
ok thank you, I will take a look.
