### ISSUE TITLE
Chat is not enabled for organization with id 49529

### ISSUE THREAD

**Issue by Himanshu-addweb** [GetStream/stream-chat-js#400]
I am facing this error while creating messaging channel

StreamChat error code 2: GetOrCreateChannel failed with error: \"Chat is not enabled for organization with id 49529

Please let me know where I am wrong or is anything I am missing from my end

gz#5288

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/5288'>Zendesk ticket #5288</a>:<br><br>Hi,

This app is associated with an organization without any Chat plan or trial.
One of these two should be active for the Chat to be enabled on this app.

Regards,

**Comment by Himanshu-addweb** [comment]
Hi @shodgetts 
Thanks for the reply.

So what should exactly I do to overcome this problem please let me know step by step in code

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/5288'>Zendesk ticket #5288</a>:<br><br>You cannot overcome this issue as it is not a technical but an account question.
You need to contact your team's admin that owns your Stream organization (Gaston) and ask him to either start the Chat trial or upgrade a Chat plan and then add you to the organization.

Regards,

**Comment by Himanshu-addweb** [comment]
Thanks @shodgetts ,
issue fixed.

but getting this error while adding new member to channel 
'could not find user Priya from add_members'

can you please help me with this?

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5288'>Zendesk ticket #5288</a>:<br><br>What is the appID please? Are you sure that Priya is a registered user on the app?

**Comment by kjr247** [comment]
Hi @shodgetts ,
> Agent comment from Séni Gueye in [Zendesk ticket #5288](https://getstream.zendesk.com/agent/tickets/5288):
> 
> You cannot overcome this issue as it is not a technical but an account question.
> You need to contact your team's admin that owns your Stream organization (Gaston) and ask him to either start the Chat trial or upgrade a Chat plan and then add you to the organization.
> 
> Regards,

I'm currently receiving this error. I am the Admin on the current account, but I do not see a way to activate chat.
