### ISSUE TITLE
Can't handle 'notification.added_to_channel' event

### ISSUE THREAD

**Issue by jonatassales** [GetStream/stream-chat-js#410]
Hi everyone.

I'm building a custom ChannelList component to my company's React frontend but my client can't handle the 'notification.added_to_channel' event which I would use to fetch new channels with new members.

Our stack is Mobile (Flutter) -> Backend (Go) -> Frontend (React)

Here's how we're handling it in React:

```
export default function useMessageListener(
  chat: ChatStore,
  operator: Operator
): void {
  const { client } = React.useContext(ChatContext)

  const handleQueryChannels = React.useCallback(
    async (): Promise<void> => {
      await chat.loadChannelsEnrolled(operator)
      await chat.loadChannelsOthers(operator)
    },
    [operator, chat]
  )

  React.useEffect(() => {
    client.on('notification.added_to_channel', handleQueryChannels)
    
    return () => {
      client.off('notification.added_to_channel', handleQueryChannels)
    }
  }, [handleQueryChannels, client])
}
```

It works with other events such as

`channel.on('message.new', handleSetUnread)`

Or

`client.on('message.new', handleQueryChannels)`

Do you guys have any clue of what problem is going on here? 

gz#5610

**Comment by vishalnarkhede** [comment]
Hey @jonatassales do you mean you never receive the event `notification.added_to_channel`?

**Comment by jonatassales** [comment]
yes

**Comment by jonatassales** [comment]
Do you guys have any update on this? I've tested with the `stream-chat-react` V2.2.2 and it seems not to be working with your component as well

**Comment by jaapbakker88** [comment]
Testing this right now with the JS sdk this works fine with our react components. Can you eleborate a bit more. You say:`I would use to fetch new channels with new members`

Do you expect to get this notification when other members are added to the channel, because you only receive this notification for yourself.

**Comment by jonatassales** [comment]
When a new user access our app and start a conversation in the chat, a new channel gets created. But my client in the frontend portal can only update with this new channel if I make a request to get this new channel. What I understood about the 'notification.added_to_channel' event is that I'm notified every time a member is added to the channel members array on a channel that's not being watched from my client. Am I seeing this correctly?

**Comment by jaapbakker88** [comment]
@jonatassales you will only receive this event if you are added to the channel. Same goes for all `notification.*` events. You will get an `channel.updated` event if a members is added and you're watching the channel.

**Comment by jonatassales** [comment]
I think I got confused on this. What I really need is: I want to my frontend client gets notified when the mobile user creates a channel, even if my frontend user is not in that channel. Is that even possible? Which event should I use?

**Comment by jaapbakker88** [comment]
@jonatassales if the frontend users gets added as a member to the channel, it will receive `notification.added_to_channel`. We don't send a general event for every channel created, as this could turn in to a lot of events that are not meant for the connected client. What's your use case for this? In my experience you only want people to know a channel is created when they're actually a member of it.

**Comment by jonatassales** [comment]
I see... We're building a help desk system in our frontend. So every help desk operator should be notified of a new channel created in our use cases. I understand why you guys don't support it though, it makes sense. We'll probably create our own events then. Thanks for the support @jaapbakker88 @vishalnarkhede .
