### ISSUE TITLE
Cannot invite users to channel

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#415]
I have a custom channel type, 'call' to be used for managing calls via Voxeet, created as follows - 

`await client.createChannelType({ name: CustomChannelTypes.call }); //CustomChannelTypes.call = 'call'`

When trying to call another user, I was able to add them directly to the call by - 

```
await client.channel(CustomChannelTypes.call, channelId, {
        members: [myId, otherUserId],
        created_by: { id: myId },
      }).create();
```

which I was able to get a handle on the 'notification.added_to_channel' event.  However I want to now change the logic slightly that I am inviting the user to call, allowing them to reject the call, so I have changed to the following - 

```
await client.channel(CustomChannelTypes.call, channelId, {
        members: [myId],
        invites: [otherUserId],
        created_by: { id: myId },
      }).create();
```

logging out what is being passed as the 3rd arg to `client.channel()` I see - 

```
{
  members: [ '5f22d9dea96cef0037ea0267' ],
  invites: [ '5f229e0d5403080038208773' ],
  created_by: { id: '5f22d9dea96cef0037ea0267' }
}
```

but with this I get no event ('notification.invited') fired for the other user, and when I log the result of the `create()` call above I see only already added members details (me).  Looking at the `ChannelResponse` interface I should also see the `invites` array, but its not there in the response.  Any idea what's going on?

gz#5738

**Comment by veloware** [comment]
Apologies, found the issue, my invited id also needed to part of the members array - 

```
...
members: [myId, otherUserId],
invites: [otherUserId],
...
```

**Comment by mfbx9da4** [comment]
AFICS this is not documented so thanks for working out the API!
