### ISSUE TITLE
Detecting when a user rejects an invite to a channel

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#416]
When a user gets invited to a stream channel - 

```
const data = {
      members: [createdBy, ...invites],
      invites,
      created_by: { id: createdBy },
};
await this.client.channel(CustomChannelTypes.call, channelId, data).create();
```

I am watching for events - 

```
client.on((event) => {
   console.log(event)
})
```

an event is fired - `notification.invited` and similarly when the invitation has been accepted - `notification.invite_accepted`, however there is no specific event for when rejecting an invite, when I do - 

```
channel.rejectInvite()
```

instead, two events are fired - `channel.updated` and `member.updated`. Both of these event contain data about the fact that a user has an `invite_rejected_at` timestamp, however I believe so will any subsequent `channel.updated` and `member.updated` events, that were not caused by rejecting an invite. Therefore simply checking if an update event contains details of a user having an `invite_rejected_at` timestamp wouldn't be enough, as it may of happened in a previous `channel.updated` / `member.updated` event that was not when the user rejected.

Without a `notification.invite_rejected`, how can I detect when an invite has been rejected straight away?

gz#5775

**Comment by veloware** [comment]
any help on this, this seems like a fairly trivial use case?

**Comment by keyneston** [comment]
HI @veloware I just took a look and can confirm we don't currently have an invite_rejected event, only an `invited` and `invite_accepted`. I've opened a ticket internally and we hope to have this added in the near future.

**Comment by mahboubii** [comment]
@veloware in the meantime, in order to catch the rejected invite event, you can rely on `member.updated` event. this event includes a `member` attribute which corresponds only to the changed user, in your case the use who rejected the invite. In case the `invite_rejected_at` is there, you can consider this event the same as `notification.invite_rejected`. This event will not be fired again unless you add or invite the user to channel, which removes the `invite_rejected_at` field.

```
  type: 'member.updated',
  cid: 'messaging:af5fec1d-1db6-4678-b1af-44ae7ffe3ad2',
  channel_id: 'af5fec1d-1db6-4678-b1af-44ae7ffe3ad2',
  channel_type: 'messaging',
  member: {
    user_id: 'nick',
    user: {
      id: 'nick',
      role: 'user',
      created_at: '2020-10-05T10:13:05.181679Z',
      updated_at: '2020-10-05T11:03:36.880842Z',
      last_active: '2020-10-05T11:03:36.880842Z',
      banned: false,
      online: true
    },
    invited: true,
    invite_rejected_at: '2020-10-05T11:05:33.948916Z',
    created_at: '2020-10-05T11:05:33.828265Z',
    updated_at: '2020-10-05T11:05:33.949022Z'
  }
```
