### ISSUE TITLE
Type definitions for devdependencies

### ISSUE THREAD

**Issue by DamonOehlman** [GetStream/stream-chat-js#417]
Hey folks,

Just wondering if the various `@types/*` packages that have been included for working with various dev dependencies can be moved to devdependencies also, e.g. those related to mocha, chai, prettier, etc.

The `@types/mocha` is a particular pain point because if another package brings in a dependency on `@types/jasmine` then errors like the following arise during typescript transpilation:

```
../../node_modules/@types/jasmine/ts3.1/index.d.ts(29,18): error TS2300: Duplicate identifier 'describe'.
../../node_modules/@types/jasmine/ts3.1/index.d.ts(43,18): error TS2300: Duplicate identifier 'xdescribe'.
../../node_modules/@types/jasmine/ts3.1/index.d.ts(52,18): error TS2300: Duplicate identifier 'it'.
../../node_modules/@types/jasmine/ts3.1/index.d.ts(68,18): error TS2300: Duplicate identifier 'xit'.
../../node_modules/@types/jasmine/ts3.1/index.d.ts(82,18): error TS2300: Duplicate identifier 'beforeEach'.
../../node_modules/@types/jasmine/ts3.1/index.d.ts(89,18): error TS2300: Duplicate identifier 'afterEach'.
../../node_modules/@types/mocha/index.d.ts(2680,13): error TS2300: Duplicate identifier 'beforeEach'.
../../node_modules/@types/mocha/index.d.ts(2698,13): error TS2300: Duplicate identifier 'afterEach'.
../../node_modules/@types/mocha/index.d.ts(2714,13): error TS2300: Duplicate identifier 'describe'.
../../node_modules/@types/mocha/index.d.ts(2735,13): error TS2300: Duplicate identifier 'xdescribe'.
../../node_modules/@types/mocha/index.d.ts(2749,13): error TS2300: Duplicate identifier 'it'.
../../node_modules/@types/mocha/index.d.ts(2770,13): error TS2300: Duplicate identifier 'xit'.
```

gz#5805

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5805'>Zendesk ticket #5805</a>:<br><br>Hi Damon

Thanks for reaching out to us.
Are you using jasmine and mocha at the same time? This duplicate identifier issue is mainly because of jasmine and mocha declaring the same global variables.
I will check with our Engineering team and let you know.

Cheers
Seetha

**Comment by DamonOehlman** [comment]
Yes, `@types/jasmine` is something we require as a a dev dependency ourselves for one of our other packages in our monorepo style project, which is why the conflict arises.  I can say with 99% certainty that all your testing related type definition packages (as mentioned - mocha, chai, etc) can be moved to `devDependencies` rather than `dependencies` which will allow consumers of the `stream-chat` package to safely use `@types/jasmine` if they so choose without having the conflict occur.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5805'>Zendesk ticket #5805</a>:<br><br>Hi Damon

Thanks for the update.
I am checking with our Engineering team. We will provide an update once we hear from them. The engineering team works during EU hours.

Thanks for your patience.

Cheers
Seetha
