### ISSUE TITLE
Inviting a Moderator

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#424]
Is it possible to Invite a user to a channel, that when accepted, they would be a moderator?

I have tried the following - 

```
const data = {
      members: [createdBy, ...invites],
      invites,
      created_by: { id: createdBy },
};
const channel = this.client.channel(
      CustomChannelTypes.call,
      channelId,
      data,
);
await channel.create()
await channel.addModerators(invites)
```

Whilst it adds the users as a moderator, it doesn't look like they are invitations anymore.  I no longer see `invited: true` on the `user` object?

gz#5910

**Comment by mahboubii** [comment]
@veloware at the moment it's not possible to automatically promote an invited user to a moderator. The workaround is to leverage our webhook system, you can promote a user once they accept the invite using the [`member.added`](https://getstream.io/chat/docs/webhook_events/?language=js#webhook-event-types) event.

**Comment by veloware** [comment]
Ok thanks
