### ISSUE TITLE
Listening/catching flagged messages

### ISSUE THREAD

**Issue by jhetuts** [GetStream/stream-chat-js#426]
Someone already asked this but the [https://github.com/GetStream/stream-chat-js/issues/98#issuecomment-574245483](answer) is not clear to me. Found an event under webhooks `message.flagged` but it needs to setup webhooks first. Is there a better way to listen or catch this particular event on a client/front-end side?

gz#6002

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6002'>Zendesk ticket #6002</a>:<br><br>Hello, currently there isn't a way to listen to this event client side, it is a webhook only event.

**Comment by jhetuts** [comment]
Thanks for the prompt response @shodgetts. With that, it doesn't matter if the user is a moderator or admin right? I'm currently creating **CHAT MODERATION** just like you have in the dashboard, so I'm stuck.

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6002'>Zendesk ticket #6002</a>:<br><br>Hello, Yes, the webhook events are delivered to a URL, so they are not client side events at all and aren't delivered to any particular user type (user, moderator, admin, etc).
