### ISSUE TITLE
Ban User, Response data is insufficient. (More of improvement less an issue)

### ISSUE THREAD

**Issue by jhetuts** [GetStream/stream-chat-js#427]
![image](https://user-images.githubusercontent.com/32116471/93295142-f452dd00-f81e-11ea-8b2d-a34bff96c915.png)

`const banUser = async (user) => {
      try {
        const res = await channel.banUser(user.id, {
            timeout: 2,
            reason: 'banned for one 2 minutes',
        });
      } catch (error) {
        console.log(error)
      }
    }`

Response:
`{"duration":"10.21ms"}`

I guess you need to add more details on response. Considering above response a successful, but still need more details.

Plus `user` under `channel.state.messages` should also update.

gz#6025

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6025'>Zendesk ticket #6025</a>:<br><br>Hi

Thanks for reporting this out to us.
We will get this checked for you.

Cheers
Seetha

**Comment by tbarbugli** [comment]
@jhetuts the ban endpoint does not need to return more than a 2xx, there is nothing more than the user input to return here. What would you expect this endpoint to return?

**Comment by jhetuts** [comment]
> @jhetuts the ban endpoint does not need to return more than a 2xx, there is nothing more than the user input to return here. What would you expect this endpoint to return?

Hi @tbarbugli, `user` under `channel.state.message` should update upon banning that `user` just like when you delete a message, from type `regular` to `deleted`. Since it's not, I would like to query that specific user using that response and change the property value of `banned` from `false` to `true`. I have to hide **ban** `button` and display **un-ban** `button` dynamically

**Comment by tbarbugli** [comment]
@jhetuts I dont think having a different API response will make any difference but I see your point about updating the state of the banned user. The ID of the user is provided as the parameter for ban/unban functions so you can use that to change the user as well when the call is completed.
