### ISSUE TITLE
Query all Flagged messages/ Deleted messages

### ISSUE THREAD

**Issue by jhetuts** [GetStream/stream-chat-js#428]
Hi, I'm currently creating a moderator dashboard so that they don't have to go through with the dashboard getstream has. I wanted to query all flagged messages, and query all deleted messages, just like you have on your dashboard. How do I do that, no documentation for that apparently. Thanks

gz#6027

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/6027'>Zendesk ticket #6027</a>:<br><br>you aren't able to query for these types of messages, however, you can set up a webhook to listen for both of these events to be triggered and handle them however you see fit. You can find this documentation here.
