### ISSUE TITLE
Query channels with only members $in array and no others

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#434]
Is it possible to write a query to get the channels that have the members within an array of IDs, but only those members.

e.g. (channel `id` - [`userId`, ...]

channel 1 - [**2,3**]
channel 2 - [1,**2,3**]
channel 3 = [**2,3**,4]

where querying for channels with users 2 and 3 would only bring back channel 1, but **not** channels 2 and 3?

gz#6099

**Comment by veloware** [comment]
actually, I just realised that the $in operator will match against `any` of the items in the array.

Is it even possible to currently write a query that would solve for matching against multiple items in the array as an `and`?

**Comment by shodgetts** [comment]
Hello, we reproduced the issue and were able to resolve it using the following query
  const query = await client.queryChannels({
    members: { $**eq**: [id1, id2] },
  });

**Comment by veloware** [comment]
After upgrading to 

```
"stream-chat": "2.5.0",
"stream-chat-react": "3.0.0",
```
The following fails - 
```
const query = await client.queryChannels({
   members: { $eq: [id1, id2] },
});
```

with the following TS error - 

<img width="658" alt="Screenshot 2020-10-05 at 12 25 57" src="https://user-images.githubusercontent.com/61578546/95075026-68d6b880-0707-11eb-9b56-229389f96f2b.png">

I tried to revert to using something like - 

```
const filter = {
      type: ChannelTypes.messaging,
      $and: [{ members: { $in: [id1] } }, { members: { $in: [id2] } }],
    };
```

and it gives the following TS error - 

<img width="658" alt="Screenshot 2020-10-05 at 12 25 57" src="https://user-images.githubusercontent.com/61578546/95075165-a89da000-0707-11eb-9b8d-24975d856d74.png">

Any help is appreciated, thanks!
