### ISSUE TITLE
updating channel with new information removes previous data properties

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#436]
I have added a custom field on to a channel when creating the channel, `isGroup` - 

_server side_

```
await this.client
      .channel('messaging', channelId, {
        created_by_id: profileId,
        members: [profileId, ...connectionProfileIds],
        isGroup: true,
      })
      .create();
```
I can see the `isGroup: true` in the newly created channel when queried on the front end.

I then later wish to update the name for a group on the front end - 

_client side_

```
await props.channel?.update({
          name: value,
        });
```

however it seems that although `name` is updated, I lose the `isGroup` property.

I have also tried to spread the existing data - 

```
await props.channel?.update({
        ...props.channel.data,
        name: value,
      });
```
 however I get the following TS errors -

<img width="623" alt="Screenshot 2020-09-22 at 11 18 53" src="https://user-images.githubusercontent.com/61578546/93870652-729efb80-fcc5-11ea-8884-a081e2f5cf05.png">

I have noticed this across all data properties, e.g. changing the `name` property by passing only the `name` property, removes the likes of `image` etc.  

Any help on how to update channel data without removing old channel data?  I shouldnt need to pass all channel data properties into each `.update()` call.

Thanks

gz#6161

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6161'>Zendesk ticket #6161</a>:<br><br>Thanks for the report... investigating.

**Comment by vishalnarkhede** [comment]
Hey @veloware ,

We are aware of the issue that you mentioned. For channel.update, you will need to send all the properties manually everytime:

```js
channel.update({
  isGroup: channel.data.isGroup
  name: value,
})
```

**Comment by veloware** [comment]
This seems to still giving an error for properties on the user/member of the channel - 

```
data.members[0].user.created_at is a reserved field, data.members[0].user.last_active is a reserved field, data.members[0].user.online is a reserved field, data.members[0].user.updated_at is a reserved field
```

**Comment by gumuz** [comment]
@vishalnarkhede you think we should exclude `members` as well or is this a different problem?

**Comment by veloware** [comment]
any thoughts on the above?  The above error stops you from using the solution of spreading in the existing channel data as done in the unit tests.  Not sure if this is because the test data may not have a proper representation of a member object, containing `user` with a `created_at` etc
