### ISSUE TITLE
Unable to search for channel using partial matches, or case insensitive matches.

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#438]
I have named my channels where they represent a group, for example 'Sales Team', 'Product Team' etc.

I don't see a way on how I can search for these channels by their name other than supplying a perfect, case sensitive match.

I have been using the following filter - 

```
{ name: { $eq: value } }
```

Is there a way I can match against partial strings, e.g. searching for 'Product' would bring me back my 'Product Team'?

If not, would there be an appetite to have the likes of a `$contains` filter condition?

Similarly, `$eq` currently expects the case to be the same, therefore 'product team' would not match against 'Product Team'.  Would there be an appetite for a non case sensitive version of `$eq` ?

gz#6191

**Comment by vishalnarkhede** [comment]
@veloware you can do do the following:

```js

name: {
    $autocomplete: 'product'
}
```

**Comment by veloware** [comment]
Thank you, that seems to work.  You may want to update https://getstream.io/chat/docs/query_syntax/?language=js with that (and any others that are not documented?)

Thanks!
