### ISSUE TITLE
Docs feedback on Chat Bots > Chat Bots

### ISSUE THREAD

**Issue by shodgetts** [GetStream/stream-chat-js#443]
***This ticket was escalated from Zendesk by Stephen Hodgetts:***

  **Ticket:** [#6210](https://getstream.zendesk.com/agent/tickets/6210)
  **Type:** Question
  **Priority:** Normal
  **Requester:** urenarafael
  **Organization:** -
  **Assignee:** Anders Lund
***

I cannot get attachments working from the server SDK - TS Error gz#6210

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6210'>Zendesk ticket #6210</a>:<br><br>Hi Rafael,

Thanks for all of the details. You're talking to us currently through our support platform and our TypeScript devs aren't actually able to access this. For this reason, I'm going to close this ticket and open one on our Github Issues for the JS SDK. I'll send you a link to this shortly over this email thread.

-Stephen

**Comment by shodgetts** [comment]
I have the following code from your samples in the docs:

```
const message = {
      text: 'Which account was affected by this issue?',
      attachments: [
        {
          type: 'form',
          title: 'Select your account',
          actions: [
            {
              name: 'account',
              text: 'Checking',
              style: 'primary',
              type: 'button',
              value: 'checking',
            },
            {
              name: 'account',
              text: 'Saving',
              style: 'default',
              type: 'button',
              value: 'saving',
            },
            {
              name: 'account',
              text: 'Cancel',
              style: 'default',
              type: 'button',
              value: 'cancel',
            },
          ],
        },
      ],
    };
    const response = await channel.sendMessage(message);
```



Which produces the following errors: 

Argument of type '{ text: string; attachments: { type: string; title: string; actions: { name: string; text: string; style: string; type: string; value: string; }[]; }[]; }' is not assignable to parameter of type 'Message'.
  Types of property 'attachments' are incompatible.
    Type '{ type: string; title: string; actions: { name: string; text: string; style: string; type: string; value: string; }[]; }[]' is not assignable to type 'Attachment[]'.
      Type '{ type: string; title: string; actions: { name: string; text: string; style: string; type: string; value: string; }[]; }' is not assignable to type 'Attachment'.
        Types of property 'actions' are incompatible.
          Type '{ name: string; text: string; style: string; type: string; value: string; }[]' is not assignable to type 'Action[]'.
            Type '{ name: string; text: string; style: string; type: string; value: string; }' is not assignable to type 'Action'.
              Types of property 'style' are incompatible.
                Type 'string' is not assignable to type '"primary" | "default" | "danger"'.
  const response = await channel.sendMessage(message); 

Which is really weird because I'm using the same example from the docs (https://getstream.io/chat/docs/chat_bots/?language=js#step_3_-_attachment,_fields_and_actions). This is on a Node server and a react native front end.

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/6210'>Zendesk ticket #6210</a>:<br><br>Hey Rafael,

Could you please tell what version of stream-chat and stream-chat-react-native are you using (from your yarn.lock file)?

Thanks,
Vishal

**Comment by nhannah** [comment]
I would suggest updating to a newer version of our client, the string union `"primary" | "default" | "danger"` is from version 1.x and the major change in 2.x was a full typescript conversion. `style` is typed as `string` in 2.x, but for reference what is happening in 1.x is when you create your message object typescript infers the type of `style` as `string` then when it is used and compared to the expected string union the type does not match. There are 3 ways to fix this off the top of my head, one is to cast style inline, i.e. `style: 'default' as 'primary' | 'default' | 'danger'`. The second is to import the Message type from stream-chat-js, i.e. `const message: Message = { ... }`, this would be the correct way in my opinion. The last is to create the object in place when you are sending it, not a clean solution imho, but it allows the TS compiler to compare the string directly to the union and not infer it's type so it would work.
