### ISSUE TITLE
Update Existing User ID

### ISSUE THREAD

**Issue by aleksvidak** [GetStream/stream-chat-js#450]
Is it possible to update existing user id?

Or if not, some kind of creating new user and copying data over from the old user to the new one?

gz#6346

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/6346'>Zendesk ticket #6346</a>:<br><br>No, this is not possible. user ID's are immutable. This is for security and compliance.

**Comment by aleksvidak** [comment]
And what about copying messages from one user to another?

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6346'>Zendesk ticket #6346</a>:<br><br>Also not going to be possible to change the sender of a message. Also for security purposes, as you can imagine.
