### ISSUE TITLE
Not receiving channel.deleted event for other members of the channel

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#453]
Im creating a channel and inviting members.  When the other users get the invites I am watching the channel for further events, such as the channel getting deleted.  If the channel gets deleted on the server side, I would like to remove invitations etc so invited users can no longer accept the invites and try and join the channel.

watching for invites -
```
client.on('notification.invited',(event) => {
      const channels = await client.queryChannels({ id: event?.channel?.id }, {}, {});
      if (channels?.length) {
          const channel = channels[0];
          await channel.watch();
          setInvitedChannel(channel) // <-- useState hook
      }
})
```

setting up further watches for the channel events - 

```
useEffect(() => {
   if (invitedChannel) {
      const handler = (event) => {
         console.log('event', event) // <-- here I would like to catch when the channel gets deleted on the server side 
         // remove invitation modal etc
      }
      invitedChannel.on('channel.deleted', handler)
      return () => {
          invitedChannel.off('channel.deleted', handler)
      }
   }
}, [invitedChannel])
```

however I never receive the 'channel.deleted' event for any users other that the one who created the channel in the first place.

gz#6390

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6390'>Zendesk ticket #6390</a>:<br><br>Thanks for the submission. We'll address this shortly.

**Comment by veloware** [comment]
thank you, if you don't mind as well - could you clarify this from the docs please? I though it was maybe related?

"Channel events are events sent to all users watching a channel **where the event originated**"

**Comment by ath92** [comment]
Hey @veloware , I had a look at this. I can confirm that invited members do not receive the `channel.deleted` event, or some other way of finding out if a channel that your user was invited to has been deleted. One workaround might be to first call `removeMembers` on the channel before removing the channel server-side, so the client would receive a `notification.removed_from_channel` event.

In the meantime, I'll create a ticket internally about notifying invited users about channels being deleted, so we can add this functionality.

As to your second question - that sentence can be rephrased as "When an event is triggered on a channel, it is sent to all users watching that channel".

**Comment by veloware** [comment]
Thanks, I was able to remove the members first and use the notification event as described.  Thanks
