### ISSUE TITLE
Types  for created_by_id / created_by.id don't match data

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#460]
I noticed since upgrading to the newer version that the type definitions have changed around the created_by.id and created_by_id when creating a channel.  But they don't seem to match up with what actually gets returned in channel data.

I believe there used to be an `id` property on the `created_by` object on `ChannelResponse`, which doesn't seem to be there anymore - 

```
export type UserResponse<T = UnknownType> = User<T> & {
  banned?: boolean;
  created_at?: string;
  deactivated_at?: string;
  deleted_at?: string;
  last_active?: string;
  online?: boolean;
  updated_at?: string;
};
```

however there is a `created_by_id` property on the ChannelResponse type - 

```
created_by?: UserResponse<UserType> | null;
created_by_id?: string;
```

however on the actual channel data object, the `id` is on the `created_by` object and there is no `created_by_id` property?

<img width="305" alt="Screenshot 2020-10-07 at 11 16 24" src="https://user-images.githubusercontent.com/61578546/95318568-aa45a000-088e-11eb-805e-a6ee913228aa.png">

gz#6502

**Comment by mahboubii** [comment]
@veloware As you can see both `created_by` and `created_by_id` are optional fields which means there are some cases that they might be undefined, usually you should rely on `created_by` to get necessary data about the channel owner.
`UserResponse` type extends the `User` [type](https://github.com/GetStream/stream-chat-js/blob/master/src/types.ts#L1476
) which has the `id` attribute present in its type:

`export type UserResponse<T = UnknownType> = User<T> & {...}` 
and
```
export type User<T = UnknownType> = T & {
  id: string;
  anon?: boolean;
  name?: string;
  role?: string;
  teams?: string[];
  username?: string;
};```

What is the error you get from typescript compiler?

**Comment by veloware** [comment]
Thanks, I missed the extension of `User`.  However, I get the following TS error - 

<img width="631" alt="Screenshot 2020-10-07 at 15 26 36" src="https://user-images.githubusercontent.com/61578546/95344535-a70fdb80-08b1-11eb-8e32-70d42cf9bc6c.png">

**Comment by mahboubii** [comment]
Where is the `data` coming from? which function are you using that leads to this issue?

**Comment by veloware** [comment]
`incomingCallChannel` is a result of calling

```
const channels = await client.queryChannels({ id: event?.channel?.id }, {}, {});
const incomingCallChannel = channels[0]
```

**Comment by veloware** [comment]
OK thanks
