### ISSUE TITLE
self signed certificate in certificate chain while calling channel functions

### ISSUE THREAD

**Issue by danishshaikh42** [GetStream/stream-chat-js#463]
Hello,

While executing the below code:

        const client = new StreamChat('myApiKey', 'mySecretKey');
        const token = client.createToken('myUserId');

        await client.setUser(
            {
                id: 'myUserId',
                name: 'myName',
                image: 'https://i.imgur.com/fR9Jz14.png',
            },
            token,
        );

        const channel = client.channel('messaging', 'travel', {
            name: 'Awesome channel about traveling',
        });

        const state = await channel.watch();

**I am getting error at**        
const state = await channel.watch();

Same thing is happening while calling other functions of channel like  channel.sendImage() etc.

Kindly help
Thanks

gz#6524

**Comment by mahboubii** [comment]
Hey @danishshaikh42, what is the exact error you're getting?

**Comment by danishshaikh42** [comment]
> Hey @danishshaikh42, what is the exact error you're getting?

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:120:14)'

**Comment by mahboubii** [comment]
@danishshaikh42 do you get an SSL error opening this [link](https://chat-us-east-1.stream-io-api.com/) in your browser? 
Which region is your app located?
Looks like you have a bad certificate in your keychain, do you have issue accessing stream website or other URLs?

**Comment by danishshaikh42** [comment]
@mahboubii I get NOT FOUND message when I access the link you shared : https://chat-us-east-1.stream-io-api.com/

**Comment by mahboubii** [comment]
@danishshaikh42 Sounds good, what about your app region?
can you try running your code in a different Machine or OS?

**Comment by danishshaikh42** [comment]
Running code on Windows 10 from Maharashtra, India

**Comment by mahboubii** [comment]
@danishshaikh42 This is most likely not related to the SDK itself, you might have a bad certificate in your keychain causing this issue. Try testing your code with a VPN, OR on a different OS/Machine, OR you can simply disable Nodejs SSL check following this link in [stackoverflow](https://stackoverflow.com/a/58800300).

**Comment by mahboubii** [comment]
hey @danishshaikh42, going to close the issue for housekeeping, let us know if you still needed help.
