### ISSUE TITLE
Webhook - Notifications payload gets truncated for channels with more than 3 people

### ISSUE THREAD

**Issue by nosmirck** [GetStream/stream-chat-js#468]
I don't really know where to put this issue, I guess here is as good as any.

So, using webhooks for chat events we get a truncated payload (the json is not complete) if the channel has more than 3 users, which is totally useless.

We're using webhooks to customize the push notifications to our app, it works fine for one-to-one conversations but any group channel gives a broken payload that can't be used (unless I read as string and parse it manually, yet, the information is not complete)

Is there any way to customize these events before they are sent to the webhook? like decide exactly which events to send, what information to send, etc?

We'd like to customize it in a way were we just get "messages.new" events with channel ID, channel name, message text and attachments type, sender id and name and members' ids in the channel, we really don't need anything else since we sue the same IDs in our database and we can query locally anything else we need to to the modifications we need on the push notifications and filter whatever we need.

The truncated payload tries tos end so much information that is not necessary (at least for us and maybe most use cases) and having a way to minimize this payload as well as customizing it would be great.

gz#6603

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/6603'>Zendesk ticket #6603</a>:<br><br>Hi there,

We'd like to dig into this issue a bit further and to do so we'll need some information on your app. To keep your information confidential, would you mind reaching out to support@getstream.io?

Thanks in advance

**Comment by nosmirck** [comment]
@shodgetts Well, all of the sudden, it started working again! Thanks anyways for your response! I'm closing this issue now.
