### ISSUE TITLE
How do I delete users?

### ISSUE THREAD

**Issue by agaace** [GetStream/stream-chat-js#474]
I want to permanently delete users via the Stream API. I cannot seem to find the documentation on how to do it?

gz#6791

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/6791'>Zendesk ticket #6791</a>:<br><br>Hi,

You can find more information about our GDPR endpoint including more detail on how to delete. users here in the following docs section : https://getstream.io/chat/docs/gdpr/?language=js#delete-a-user

Best regards,

**Comment by mahboubii** [comment]
@agaace this should do the trick if you are looking for a hard delete, adjust the options accordingly:
```
client.deleteUser(USER_ID, {
    mark_messages_deleted: true,
    hard_delete: true,
});
```
