### ISSUE TITLE
Is the `id` on message now required?

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-js#480]
https://github.com/GetStream/stream-chat-js/blob/8efa2272be22331f51bcc7b54cb256e52b95c43f/src/types.ts#L1354

Typescript 
![image](https://user-images.githubusercontent.com/1654135/97400013-11a8ba00-193a-11eb-8458-58533f0e2fbe.png)

According with the documentation here https://getstream.io/chat/docs/silent_messages/?language=js we should be able to send a message without and `id`.

![image](https://user-images.githubusercontent.com/1654135/97399860-bf679900-1939-11eb-9d7e-3d0e7b5d52a5.png)

If it is now required can we use a random uuid for this?

cc @tbarbugli 

gz#6914

**Comment by mahboubii** [comment]
@alexlopezit `id` is not required when sending a new message, we will push a fix for it soon.

**Comment by mahboubii** [comment]
fixed in v2.7.2
