### ISSUE TITLE
Stop Live Event for  Channel

### ISSUE THREAD

**Issue by nal-ws-001** [GetStream/stream-chat-js#495]
When i receive notification.removed_from_channel in a group chat, I want to stop live events for that channel. Which method is suit for that case?

gz#7218

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7218'>Zendesk ticket #7218</a>:<br><br>Hello, can you try to unwatch the channel when you receive this event?https://getstream.io/chat/docs/watch_channel/?language=js#unwatching

**Comment by nal-ws-001** [comment]
Thanks. I got it by using channel.stopWatching
