### ISSUE TITLE
If token refresh promise fails the channel list keeps refreshing

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-js#530]
On the latest version (v2.0.2) when the userTokenOrProvider is provided to the setUser method: if the user refreshes and the token refresh promise fails for any reason the list keeps refreshing indefinitely with no way to make it stop.

gz#7390

**Comment by vishalnarkhede** [comment]
@amardeepranu could you please try upgrading to latest `stream-chat` version?

**Comment by vishalnarkhede** [comment]
Fyi, this has been fixed in latest versions.
