### ISSUE TITLE
Query on messages

### ISSUE THREAD

**Issue by jonatassales** [GetStream/stream-chat-js#537]
How can I query channels with more than zero messages like `{ 'messages.length': { $gt: 0 }}`

I've tried everything and nothing works =(

gz#7863

**Comment by shodgetts** [comment]
Hello, yes, this isn't immediately obvious. You can add a filter such as this

```js
const filter = { type: "messaging", 
member: { $in: [userID] },
last_message_at: { $gt: "2020-10-10T16:01:49.27673Z" },
}
```

Where the timestamp is some time in the past.
