### ISSUE TITLE
Unread channel doesn't count when user replay in thread

### ISSUE THREAD

**Issue by tranlehaiquan** [GetStream/stream-chat-js#538]
As title issue. When the user replay to a thread `unread_channels` doesn't trigger. So users don't know the new message coming.

gz#7893

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/7893'>Zendesk ticket #7893</a>:<br><br>Hi,

By design, our API only increases/updates unread counts/unread channels for messages with type `regular`.

**Comment by tranlehaiquan** [comment]
@shodgetts 

So no way to know if the user has an unread message from replay?

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7893'>Zendesk ticket #7893</a>:<br><br>Not by default, sorry.

**Comment by tranlehaiquan** [comment]
It ok @shodgetts, I just want to confirm it doesn't support
