### ISSUE TITLE
How to get number of users online across ALL channels within a team?

### ISSUE THREAD

**Issue by agaace** [GetStream/stream-chat-js#554]
Hello, currently we do this:

```js
    let channels = await streamApi.queryChannels({ id: channelId, team: teamId }, {}, {});
    let totalUserCount = 0
    let onlineUserCount = 0;
    for (const channel of channels) {
      const members = (await channel.queryMembers({})).members;
      totalUserCount += members.length;
      for (const memberId in members) if (members[memberId].user?.online) ++onlineUserCount;
    }
 ```   
 
which is terribly inefficient. We're having issues hitting our API quota with `queryMember` calls because we have a lot of channels and making an API request for each and every one to count members. How do we get stats like this - say total number of users online, in a single API call? Can be slightly stale data, say 15 min stale, we don't care for it to be actual live data. We care about this being efficient and not forcing us to bombard Stream API with requests.

gz#8181

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8181'>Zendesk ticket #8181</a>:<br><br>Hi. After checking in with my manager, I need to make some slight changes to this answer. `Watcher_coun`t will return a list of watchers regardless of membership. For members, you will want to use `member_count` from `channel.data,` instead of `channel.members`. Please let me know if I can provide any further help here!

**Comment by saddington** [comment]
thanks @shodgetts — we're very interested in seeing this "work" for us... but, are unsure tbh of the long-term viability for our app. :)

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8181'>Zendesk ticket #8181</a>:<br><br>You're welcome, John - The Stream Chat API is powerful and flexible and could be a great asset to your app. Wishing you luck with the long-term viability factor. Please let us know if you have any further questions!

**Comment by saddington** [comment]
... you literally don't have to sell us. we've been customers for like.. almost a year now. lol.

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8181'>Zendesk ticket #8181</a>:<br><br>For sure! I do see that now. Please let us know if you have any feedback for us! We always appreciate new ideas from customers who have used the chat product as long as you have. Let me know if you have any other questions at the moment as well :)

**Comment by agaace** [comment]
@shodgetts That seems to work, thank you. Just double checking: will it only count members who are currently online, or all members who have ever been added to the channel?

**Comment by agaace** [comment]
@shodgetts I just confirmed that `member_count` returns ALL members inside a channel, regardless of whether they are currently online or not. So this isn't a working solution for me..

**Comment by shodgetts** [comment]
Hello, So watcher count is going to give you a count of the users who are currently watching the channel. I'm guessing in this use case to read the channel a user will need to be a member.

**Comment by agaace** [comment]
@shodgetts Could you provide a code sample? Like the one I provided above, but using the watchers? This code will be executed server-side, so we can expose these counts via our own API. Thanks!

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8181'>Zendesk ticket #8181</a>:<br><br>Hi,

Sure thing. Please see the below code to get the watcher count of a channel.


        const filter = { cid: channelCID };    const sort = { last_message_at: -1 };    const channel = await chatClient.queryChannels(filter, sort, {});    return channel[0].state.watcher_count;


Let me know if you have any other questions here!

Best,
Ryan

**Comment by agaace** [comment]
@shodgetts Thanks, I think that should do the trick. But now that I'm not getting members, how do I get number of all members in all channels (online and offline)? I tried `channel.data.member_count` but it doesn't work. In fact, in Typescript that's not even a field, and it's giving me a 0 if I force it nonetheless..

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8181'>Zendesk ticket #8181</a>:<br><br>Hi,

Thanks. I hear you. Just tried `return channel[0].data.member_count` and recieved accurate numbers on my end. Could you please provide more of your code for more context?

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8181'>Zendesk ticket #8181</a>:<br><br>Hi,

Please reach out if you have any more questions! I am going to close this ticket for now.

Best,
Ryan
