### ISSUE TITLE
Custom events & channel types

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-js#555]
Hello,

It's more for a clarification:
```
Uncaught (in promise) Error: StreamChat error code 18: SendEvent failed with error: "Channel type messaging does not support custom events"
```
I don't see anything in the doc, on the feature announcement I can read "Custom events are enabled by default in all channel types." https://getstream.io/blog/feature-announcement-custom-events/
I saw we can update as well the channel type and with few options.
```
await serverAuthClient.updateChannelType('livestream', {
    custom_events: true,
});
```
A small clarification would be welcome, maybe I missed something? 
Thank you.

gz#8194

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8194'>Zendesk ticket #8194</a>:<br><br>Hi there,

This can be enabled / disabled from your dashboard. Would you mind double checking that custom events are not disabled on the channel types you'd like to utilize this feature on? You can find these like so: Dashboard -> App - Chat Overview -> channel type.

**Comment by lr-mjaouen** [comment]
I will thank you. I never looked at the dashboard.

**Comment by lr-mjaouen** [comment]
Ok thanks, I let a screenshot cause I struggled a bit to find it.
![image](https://user-images.githubusercontent.com/56837954/102929914-74fe2680-4469-11eb-8524-193cc00a3abb.png)

**Comment by lr-mjaouen** [comment]
Ok thank I found it, (first select your app then: chat > overview)

**Comment by lr-mjaouen** [comment]
Same I had to update the permissions,
![image](https://user-images.githubusercontent.com/56837954/102932302-05d70100-446e-11eb-8758-186817b8b81d.png)
