### ISSUE TITLE
QueryChannels method returns instance methods.

### ISSUE THREAD

**Issue by nandakishorebhandari** [GetStream/stream-chat-js#589]
import { StreamChat } from 'stream-chat'
const streamClient = new StreamChat(apiKey, apiSecret, {})

const filter = { type: 'team }

const channels = await streamClient.queryChannels(filter)

console.log(channels)
**Expected**:  JSON formated data.

**Error While sending channels as API response**
  TypeError: Converting circular structure to JSON
      at JSON.stringify (<anonymous>)
      at respond (/Users/nandakishorebhandari/Documents/rejuvenan/member/stream-service/node_modules/koa/lib/application.js:259:15)
      at handleResponse (/Users/nandakishorebhandari/Documents/rejuvenan/member/stream-service/node_modules/koa/lib/application.js:164:34)

**Actual**:
[ Channel {
    _client:
     StreamChat {
       _user: undefined,
       activeChannels: [Object],
       anonymous: false,
       axiosInstance: [Function],
       baseURL: 'https://chat-us-east-1.stream-io-api.com',
       browser: false,
       cleaningIntervalRef: undefined,
       clientID: undefined,
       configs: [Object],
       connecting: undefined,
       connectionEstablishedCount: undefined,
       connectionID: undefined,
       failures: undefined,
       key: '**************',
       listeners: {},
       logger: [Function],
       mutedChannels: [],
       mutedUsers: [],
       node: true,
       options: [Object],
       secret:
        '****************',
       setUserPromise: null,
       state: [ClientState],
       tokenManager: [TokenManager],
       user: undefined,
       userAgent: undefined,
       userID: undefined,
       wsBaseURL: 'wss://chat-us-east-1.stream-io-api.com',
       wsConnection: null,
       wsPromise: null,
       _setupConnection: [Function],
       _hasConnectionID: [Function],
       setUser: [Function],
       _setToken: [Function],
       setAnonymousUser: [Function],
       doAxiosRequest: [Function],
       dispatchEvent: [Function],
       handleEvent: [Function],
       _callClientListeners: [Function],
       recoverState: [Function],
       _isUsingServerAuth: [Function] },
    type: 'community',
    id: 'fever',
    data:
     { id: 'fever',
       type: 'community',
       cid: 'community:fever',
       created_at: '2021-01-18T05:12:17.450504Z',
       updated_at: '2021-01-18T05:12:17.450505Z',
       created_by: [Object],
       frozen: false,
       config: [Object],
       name: 'Fever',
       users: [Array] },
    _data: {},
    cid: 'community:fever',
    listeners: {},
    state:
     ChannelState {
       _channel: [Circular],
       watcher_count: 0,
       typing: {},
       read: {},
       messages: [],
       threads: {},
       mutedUsers: [],
       watchers: {},
       members: {},
       unreadCount: 0,
       membership: {},
       last_message_at: null,
       removeMessageFromArray: [Function] },
    initialized: true,
    lastKeyStroke: undefined,
    lastTypingEvent: null,
    isTyping: false,
    disconnected: false,
    create: [Function],
    _callChannelListeners: [Function],
    _channelURL: [Function] } ]

gz#8669

**Comment by mahboubii** [comment]
hey @nandakishorebhandari,
`queryChannels` method returns an array of enriched Channel class which has some circular object references for ease of use. If you need the raw data returned by API, you can get most of it like this:
```js
const channels = await streamClient.queryChannels(filter)
const rawData = channels.map((ch) => ({
    data: ch.data,
    members: ch.state.members,
    membership: ch.state.membership,
    messages: ch.state.messages,
 }));
```

**Comment by nandakishorebhandari** [comment]
Thanks @mahboubii
