### ISSUE TITLE
queryChannels doesn't return more than 10 channels

### ISSUE THREAD

**Issue by sayginburak** [GetStream/stream-chat-js#598]
I am trying to retrieve channels set for a user. Although docs state that max limit for queryChannels method is 30 it doesn't return more than 10. 
https://getstream.io/chat/docs/query_channels/?language=js#query-options

My code is below. It is returning only 10 channels. But it should be more.
```
const serverClient = new StreamChat(api_key, stream_secret, options)
const filters = { members: { $in: [`${user.id}`] } }
const sort = { last_message_at: -1 }
const channels = await serverClient.queryChannels(filters, sort, {
    watch: true,
    limit: 30
  })
```

gz#8891

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8891'>Zendesk ticket #8891</a>:<br><br>Hi there,

Can you confirm that the user is a member of more than 10 channels?

**Comment by sayginburak** [comment]
I've  tried to sort by created_at descending and ascending. both times I got the same 10 channel_ids. I've actually created 18 channels for this user. Is there any limitations that might be causing this? Such as members can be subscribed to only 10 channels for some reason?
