### ISSUE TITLE
Query users without a limitation

### ISSUE THREAD

**Issue by Lucasdsk** [GetStream/stream-chat-js#603]
Hello!!

I'm trying to query users through the `queryUsers` function but in our App we can not have a limit of users. Currently we have more than 200k users and this number is still increasing. 

For now I've set a limit of 10000:
```javascript
const { users } = await client.queryUsers({ $and: [
    {
      gender: { $in: ["male", "female"] },
    },
    {
      isSubscribed: { $eq: true },
    },
    {
      partnerId: { $ne: null }
    }
  ]}, {last_active: -1}, {limit: 10000});
```

Is there a way to disable this limitation? Setting `-1` for example, something like that.

gz#8972

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8972'>Zendesk ticket #8972</a>:<br><br>Hi

Thanks for reaching out to us.
We will get back to you soon.

Cheers
Stream Team

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8972'>Zendesk ticket #8972</a>:<br><br>Hi

The offset limit is set at 1000. You can paginate through the query.
Is this a one time export of all users from the app? We would like to understand more details as we are talking about 200k+ users. Can you please elaborate your use-case and send out an email to support@getstream.io.

Cheers
Seetha

**Comment by 6ewis** [comment]
@shodgetts We are well on our way to 1M users, We are growing extremely fast. Our users have private conversation with their partners; in other words they can only initiate a two-person chat.(I,e a woman and her husband can chat in private). We occasionally send prompt messages to all our users in their private channels. However, there seem to be a limit in the number of users we can query with `queryUsers`. 

I suspect that we are not approaching it the right way, so would love your guidance on the matter please.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8972'>Zendesk ticket #8972</a>:<br><br>Hi

Thanks for the details.
I think it is better to have a call arranged with your team.
We will reach out to you via email.

Cheers
Seetha
