### ISSUE TITLE
Issues with fetching channels

### ISSUE THREAD

**Issue by fredwilby** [GetStream/stream-chat-js#617]
Hi,

I'm working on a chat app that currently has around 15 public channels as well as a bunch of private ones. Recently we've begun having issues both with the react channel list component and the `queryChannels` API call more generally.

In short, channels which should be showing up are continually going missing, both from the react list and our admin panel powered by the API call.

Investigating this, it seems like the `limit` parameter passed to the SDK is being ignored. 

Here's a snippet from our node.js REPL environment showing the discrepancy:
```
yen>streamApi.queryChannels({}, {}, { limit: 100 }).then(chan => { ch = chan; })
Promise { <pending> }
yen>ch.length
30
yen>streamApi.queryChannels({ type: 'livestream' }, {}, { limit: 100 }).then(chan => { ch = chan; })
Promise { <pending> }
yen>ch.length
15
yen>streamApi.queryChannels({ type: 'lobby' }, {}, { limit: 100 }).then(chan => { ch = chan; })
Promise { <pending> }
yen>ch.length
30
```

(We're using 'livestream' for public channels and 'lobby' for private).

From my understanding of the API we should be able to use the first API call above to fetch the first 100 channels, but it seems we're limited to 30 results. Is 30 a hard limit on this API call?

If it's helpful I can create a separate issue in the react repo for our channel list problems, but since it seems like it might be related, I'll cover it here. 

We're using the `stream-chat-react` `ChannelList` component and passing `options={{ limit: 100 }}` as a prop. Everything seemed to be working fine with it until we started creating private channels. Now we periodically lose stale public channels from the list (it seems to revert to returning 10 channels total when stuff goes missing, but when the missing channels are bumped the list is capable of displaying more than 10). We're not passing any other pagination options down, and I've never seen the channel list render the load more button, so not sure what's going on here. 

gz#9457

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/9457'>Zendesk ticket #9457</a>:<br><br>Hi,

Thanks for reaching out. Let me look into this for you. Will be in touch soon.

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/9457'>Zendesk ticket #9457</a>:<br><br>Hi,

The hard limit is 30 here.

For the first query, please use a filter. This will make things much easier. Here is an article on how to use filters - https://getstream.zendesk.com/hc/en-us/articles/360057461213-Querying-for-Channels-with-the-Stream-Chat-API

For the last query, add members: $in: [userID] to the query if they are direct messages, it’ll be faster.

Please let me know if you have any questions here!

Best,
Ryan

**Comment by fredwilby** [comment]
Hi Ryan,

We can workaround our server-side usage by limiting / filtering, but for the last query we're trying to show users a list of all the channels they're in, public and private, so they can switch between them. Are you saying there's no way to get the out of the box React channel list to support this? It seems like it should be possible given the presence of pagination options.

Thanks
Fred

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/9457'>Zendesk ticket #9457</a>:<br><br>Hi Fred,

Could you please try this filter? It should fetch both channel types for a user.


    const filter = {    $or: [     { type: "livestream" },      {        type: "lobby",        members: {          $in: ["user_id"],        },      },    ],  };


Best,
Ryan
