### ISSUE TITLE
Problem with sendFile method

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-js#62]
Hello i'm having an issue when i try to upload a pdf, the size of the file is 10MB

this is the code:
async function sendFile() {
      try {
            const response = await channel.sendFile(fs.createReadStream('file.pdf'),'file.pdf');
            console.log(response);
      } catch(e) {
          console.log(e)
      }
  }

The process is returning the following
{ FetchError: invalid json response body at https://chat-us-east-1.stream-io-api.com/channels/messaging/XXXXXXX/file?api_key=XXXXXX reason: Unexpected token E in JSON at position 0
    at /Users/user/Desktop/react-stream-chat-nodejs/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://chat-us-east-1.stream-io-api.com/channels/messaging/XXXXXX/file?api_key=XXXXXX reason: Unexpected token E in JSON at position 0',
  type: 'invalid-json' }

It seems its returning a 400 Bad request according with some tests i did, but i don't know why its happening.
My node version is 10.16.0
Any idea? 

Thanks

**Comment by aniciom** [comment]
It seems the service its returning 400 and Error when parsing request output when the files are kinda big, any kind of solution about this?

**Comment by aniciom** [comment]
guys none is going to take care of such issue?

**Comment by tbarbugli** [comment]
we release a fix for this just today, can you test again?

**Comment by aniciom** [comment]
@tbarbugli Thanks for the answer, i'll upload some screenshots from my postman, i just made them, i tried to upload a 4,1mb pdf and the results are the next

Its giving me a 200 OK Response but its an empty one

<img width="818" alt="Captura de Pantalla 2019-06-26 a la(s) 11 14 42" src="https://user-images.githubusercontent.com/5354596/60187348-ca6d5f00-9803-11e9-9d62-84f8f8a04f08.png">

<img width="818" alt="Captura de Pantalla 2019-06-26 a la(s) 11 14 52" src="https://user-images.githubusercontent.com/5354596/60187366-d35e3080-9803-11e9-994a-d62a65bfbff0.png">

**Comment by tbarbugli** [comment]
@thesyncim ^^^

**Comment by aniciom** [comment]
Thanks, i saw 1 thing it appears that the method errorHandler is not declared in the stream-chat-js sdk, so when the response fails it resets the connection but it also throws an error saying that the method _this.errorHandler is not declared.

One last question, i'd like to know if there's any kind of size limit for the files upload and image upload? Because its not clear at all.

Cheers

**Comment by thesyncim** [comment]
@aniciom it looks like the request is timing out on our side. (IO deadline was reached for the upload controller)
we are going to increase the deadline.(i will ping you when this change is deployed)
currently the max upload size is 20MB.

**Comment by aniciom** [comment]
Ok thanks
