### ISSUE TITLE
Typescript typing broken on versions 3.x.x

### ISSUE THREAD

**Issue by BrianLi101** [GetStream/stream-chat-js#623]
On line 250 of `stream-chat/dist/types/types.d.ts` there is a Typescript issue with the following line:

`i18n?: RequireAtLeastOne<Record<`${TranslationLanguages}_text`, string>> & {`

It looks like `Record` is unable to be used with `${TranslationLanguages}_text` and has the error `'>' expected`.

gz#9864

**Comment by vishalnarkhede** [comment]
@BrianLi101 Could you please show the screenshot of error?

**Comment by BrianLi101** [comment]
<img width="817" alt="Screen Shot 2021-03-03 at 10 38 57 PM" src="https://user-images.githubusercontent.com/17527579/110002338-43b09b00-7ce3-11eb-8058-a3682f43f2a8.png">

**Comment by vishalnarkhede** [comment]
@BrianLi101 what version of `tsc` are you on?

**Comment by BrianLi101** [comment]
We were previously on `typescript` version `3.8.0`, just bumped our version to `4.2.3` and it's working now! Thank you for helping me resolve the issue!

Closing this issue now :)
