### ISSUE TITLE
unread_count in message.new event is including unread from other channels

### ISSUE THREAD

**Issue by Fnopster** [GetStream/stream-chat-js#640]
Hi,

The unread_count in message.new is the same as total_unread_count. I was expecting the number of unread count in the channel.

Is there a way to get the number of unread_count in the channel thru the events?

Example of event object from stream chat. In this scenario, there were only 4 unread messages in the channel.
```
{
    "type": "message.new",
    "cid": "messaging:!members-eyWywsfDB-9fLWC74ZbN-Jl5Dot-34CWAqTfcxRHbJ0",
    "channel_id": "!members-eyWywsfDB-9fLWC74ZbN-Jl5Dot-34CWAqTfcxRHbJ0",
    "channel_type": "messaging",
    "message": {
        "id": "bk3YkO5cBlU2Y3E5VymYfOYmQE02-5ec27d56-1bc3-4eb4-ba47-578e77708263",
        "text": "ok",
        "html": "<p>ok</p>\n",
        "type": "regular",
        "user": {
            "id": "bk3YkO5cBlU2Y3E5VymYfOYmQE02",
            "role": "user",
            "created_at": "2021-03-12T01:31:16.955342Z",
            "updated_at": "2021-03-12T02:01:39.685287Z",
            "last_active": "2021-03-12T02:01:39.685287Z",
            "banned": false,
            "online": true,
            "teams": [
                "public",
                "group_HBnJisDfxvckWjnTngN4"
            ],
            "name": "X"
        },
        "attachments": [],
        "latest_reactions": [],
        "own_reactions": [],
        "reaction_counts": null,
        "reaction_scores": {},
        "reply_count": 0,
        "cid": "messaging:!members-eyWywsfDB-9fLWC74ZbN-Jl5Dot-34CWAqTfcxRHbJ0",
        "created_at": "2021-03-12T02:05:41.282281Z",
        "updated_at": "2021-03-12T02:05:41.282282Z",
        "shadowed": false,
        "mentioned_users": [],
        "silent": false,
        "pinned": false,
        "pinned_at": null,
        "pinned_by": null,
        "pin_expires": null
    },
    "user": {
        "id": "bk3YkO5cBlU2Y3E5VymYfOYmQE02",
        "role": "user",
        "created_at": "2021-03-12T01:31:16.955342Z",
        "updated_at": "2021-03-12T02:01:39.685287Z",
        "last_active": "2021-03-12T02:01:39.685287Z",
        "banned": false,
        "online": true,
        "teams": [
            "public", "abc"
        ],
        "name": "X"
    },
    "watcher_count": 2,
    "created_at": "2021-03-12T02:05:41.296019422Z",
    "unread_count": 10,
    "total_unread_count": 10,
    "unread_channels": 2,
    "received_at": "2021-03-12T02:05:41.319Z"
}
```

Kind regards,
Mark

gz#10126

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/10126'>Zendesk ticket #10126</a>:<br><br>Hi Mark

Can you please try to make use of the notification events?

To support updating the unread count in real-time, you can listen to these events:

- `notification.message_new`
- `notification.mark_read`
These two events include the fields `total_unread_count` and `unread_channels`. You can listen to them all at once like this:


    client.on((event) => {  if (event.total_unread_count !== undefined) {          console.log(event.total_unread_count);  }  if (event.unread_channels !== undefined) {          console.log(event.unread_channels);  } });


Notification events - are sent to members of the channel who is not being watched (by those members). e.g., let us say `user1` is a member of 11 channels. He currently has 10 channels (also being watched) in his ChannelList. Now if the 11th channel gets some new message, then in this case user1 will receive a `notification.message_new` event. But if the 10th channel (already being watched by the user1) gets a new message, then he will receive a `message.new` event. (Please note that being a member of the channel is crucial)

Please let us know if this helps.

Cheers
Seetha

**Comment by Fnopster** [comment]
Hi Seetha, 

Thanks for the quick reply!

Unfortunately, I get the same problem with `notification.message_new` and `notification.mark_read` event. 

The `unread_count` and `total_unread_count` in both events include the total unread count across all channels.

**Comment by vishalnarkhede** [comment]
Hey @Fnopster you should use `channel.countUnread()`, to get the latest unread count, after receiving the message

**Comment by vishalnarkhede** [comment]
@Fnopster do you still need any more here?
