### ISSUE TITLE
How to Querying Users - Autocomplete for custom fields?

### ISSUE THREAD

**Issue by nicogelpi** [GetStream/stream-chat-js#641]
Hello All, 
I'm trying to request to queryUsers adding an autocomplete for a custom field. 
Basically what Im trying to do is filter the list of users based on a string field `company_name`
I can do this 
```
client.queryUsers({ 
   $and: [ 
      { name: { $autocomplete: "search_term" } }, 
      { company_name: "search_term" } 
   ], 
});
```

but didn't found a way to apply a `$regex` or `$autocomplete` for `company_name`
to do something like 

```
client.queryUsers({ 
   $and: [ 
      { name: { $autocomplete: "search_term" } }, 
      { company_name: {$regex: ".*search_term*." }} 
   ], 
});
```

Any ideas?

THANKS!

gz#10166

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/10166'>Zendesk ticket #10166</a>:<br><br>Hi,

Thanks for getting in touch. I am looking into this for you as soon as possible. Please let me know if you have any other questions in the meantime.

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/10166'>Zendesk ticket #10166</a>:<br><br>Hi,

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/10166'>Zendesk ticket #10166</a>:<br><br>Hi,

The previous email was a mistake, apologies. I am checking in now to see if we have the functionality to allow autocomplete when searching through custom data fields. Will be in touch as soon as possible.

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/10166'>Zendesk ticket #10166</a>:<br><br>Hi Nico,

Just heard back from another engineer on this. Searching through custom meta data with autocomplete isn't currently possible, but we are passing this info to our product team. When you have a moment, could you please let me know which organization you're with, so I may attach it to the product feedback?

Best,
Ryan

**Comment by nicogelpi** [comment]
Thanks so much, I'm with Convene

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/10166'>Zendesk ticket #10166</a>:<br><br>You bet! Will pass this feedback along now. Have a good day :)
