### ISSUE TITLE
Deactivated Chat User still receiving information

### ISSUE THREAD

**Issue by builtbyproxy** [GetStream/stream-chat-js#642]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version: 
	- `"stream-chat": "^1.7.2"`
	- `"stream-chat-react-native": "^0.10.0"`
- react-native or expo version:
	- `"react-native": "0.61.5"`
- Device/Emulator (android/ios) and OS version
	- `iPhone X - 12.4` 

**To Reproduce**

For this scenario we have two users:
- Terrific Tom (Active)
- Deactivated Richard (Deactivated) 

A little tricky, but we are running stream-chat in our production app which talks to a server using the [stream-chat-ruby gem](https://github.com/GetStream/stream-chat-ruby). When we de-activate a user, we successfully run `deactivate_user(user_id)`. 

I believe this passes because when I then try to send a message to Terrific Tom from Deactivated Richard, everything fails: 
![image](https://user-images.githubusercontent.com/16897508/104667956-e8225200-5722-11eb-81ed-da2b61c4a264.png)

However, we can see the user is still able to receive messages from the active users, along with see the status of their typing.

Our de-activated user looks like this in the stream dashboard.
![image](https://user-images.githubusercontent.com/16897508/104667812-a691a700-5722-11eb-931a-9b5487d0fde5.png)

The response of these failed network requests makes sense:

**sendEvent**
![image](https://user-images.githubusercontent.com/16897508/104668107-359ebf00-5723-11eb-97a6-cf33d692811c.png)

**markRead**
![image](https://user-images.githubusercontent.com/16897508/104668122-3b94a000-5723-11eb-9f0f-afc989bed5ca.png)

**sendMessage**
![image](https://user-images.githubusercontent.com/16897508/104668131-40595400-5723-11eb-94b8-675722c52fca.png)

**Expected behavior**
Since Deactivated Richard is returning an error saying they are deactivated. It makes no sense that they can still contact the server and receive messages. 

**Additional context**
I find it even weirder that I cant see the network requests from when a user is typing. I have no idea what external service that is hitting, but whatever it is, the user isn't de-activated there. Additionally, the markRead action, only marks it read. I do not have a network request that 'receives' a message. It comes out of thin air. 

Thanks for the help!!

**Screenshots**
Attached in the above description ^

gz#8638

**Comment by builtbyproxy** [comment]
Has there been any update on this? 

We may have to remove this library from our product if this isn't addressed soon. Deactivating the user on our server should be enough to solve the problem, yet the users can still receive messages.

**Comment by vishalnarkhede** [comment]
@builtbyproxy this task is in progress right now. Will let you know once it is done!!

**Comment by builtbyproxy** [comment]
Thank you @vishalnarkhede!! Do you have a rough ETA I can work around please?

**Comment by builtbyproxy** [comment]
How is this going?

**Comment by AnatolyRugalev** [comment]
Hey @builtbyproxy 

We addressed this issue in our recent update. After you deactivate or delete a user, their WebSocket connections stop receiving any events.

**Comment by vishalnarkhede** [comment]
@builtbyproxy it was fixed on backend. So upgrade is not necessary for stream-chat-js

**Comment by builtbyproxy** [comment]
Oh phenomenal! Thank you very much @vishalnarkhede for all the help
