### ISSUE TITLE
Bug: `client.user` will never have properties removed

### ISSUE THREAD

**Issue by wmadden** [GetStream/stream-chat-js#655]
The following line means that if a property is removed from a user on the server side, it will never be removed from the client's copy of the user:

https://github.com/GetStream/stream-chat-js/blob/master/src/client.ts#L1199

```ts
    // update the client.state with any changes to users
    if (
      event.user &&
      (event.type === 'user.presence.changed' || event.type === 'user.updated')
    ) {
      if (event.user?.id === this.userID) {
        this.user = this.user && { ...this.user, ...event.user }; // <-- the problem is here
        // Updating only available properties in _user object.
        Object.keys(event.user).forEach(function (key) {
          if (client._user && key in client._user) {
            // @ts-expect-error
            client._user[key] = event.user[key];
          }
        });
      }
      client.state.updateUser(event.user);
      client._updateUserReferences(event.user);
    }
```

To be clear:

* If a property is present on `this.user`
* and a subsequent update on the backend dispatches a `'user.updated'` event with the updated representation of the user in which the property is absent
* the object spread `{...this.user, ` will cause the deleted property to be retained despite it being removed in the serialized user on the event object

gz#10673

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/10673'>Zendesk ticket #10673</a>:<br><br>Hi there,

Thanks for the details, we'll take a look into this just as soon as we're able

**Comment by vishalnarkhede** [comment]
Hey @wmadden thanks for bringing this up. We will handle this soon :)
