### ISSUE TITLE
Events channel.muted and channel.unmuted are not being emitted

### ISSUE THREAD

**Issue by szmitas** [GetStream/stream-chat-js#657]
Hello.

I'd like to perform some actions on events channel.muted and channel.unmuted, but they are not being emitted. There is no problem with hidden/visible - everything works as expected.

I belive I'm doing everything ok, because if I change channel's mute status I'll recieve **notification.channel_mutes_updated** event with correct data, but no channel.muted nor channel.unmuted. If I change channel visibility, I'll recieve channel.hidden/channel.visible events, so I think the subscription works fine.

Is there any thing that I could forget about?

**Comment by vishalnarkhede** [comment]
@szmitas `channel.muted` event is only received by clients from the user that marked the channel as muted. Could you please confirm, if you are only expecting this event for the same user who marked channel as muted?

**Comment by lukasz-modento** [comment]
Let me explain it more precisely:

User A and B have a common channel.

1. When user A sends a message to B, B will receive the message.new event (same when B sends a message to A).
2. When user A hides the channel, user A will receive the channel.hidden event (B won't).
3. When user A mutes the channel neither A nor B will recieve the channel.muted event (same when B mutes the channel). However, user A will receive the notification.channel_mutes_updated event.

Based on this information - it looks my subscirption works fine but channel.muted/channel.unmute events are missing.

**Comment by szmitas** [comment]
Let me explain it more precisely:

User A and B have a common channel.

1. When user A sends a message to B, B will receive the message.new event (same when B sends a message to A).
2. When user A hides the channel, user A will receive the channel.hidden event (B won't).
3. When user A mutes the channel neither A nor B will recieve the channel.muted event (same when B mutes the channel). However, user A will receive the notification.channel_mutes_updated event.

Based on this information - it looks my subscirption works fine but channel.muted/channel.unmute events are missing.

**Comment by yaziine** [comment]
@szmitas thank you for noticing that.

The team is currently working on a fix. Will keep you updated when it will be released.

**Comment by yaziine** [comment]
@szmitas, finally, it appears that the current behaviour is what we want but the documentation was a bit out of date. 

- `channel.muted` event is and should be only sent to webhooks
- `notification.channel_mutes_updated` event is sent to the user who mutes a channel

Concretely, given your example, when user A mutes a channel, user B doesn't have to know that A did that.

Closing this for now, feel free to reopen if needed.
