### ISSUE TITLE
Bug: notification.message_new event not triggering for user who sent message

### ISSUE THREAD

**Issue by dilizarov** [GetStream/stream-chat-js#660]
I'm sending a message on my server to a specific channel. Everyone on the channel gets notified except the user who sent the message.

For example:

On my server I do something like this:

```
const channel = await this.stream.findOrCreateChannel([users]); // my helper

const message = await channel.sendMessage({
  id: "my_message_id",
  text: "This is the message text",
  user_id: "user_sending_message_id"
})
```

In the browser, I am **not watching** the channel. When I do watch, I can confirm the user who **sent** the message receives the "message.new" event.

So anyways, the user who sent the message does not get a notification.message_new event.

Or more explicitly, if user with user_id "user_sending_message_id" sends the message via my server, then on the client, the connected user with user_id "user_sending_message_id" does not get the "notification.message_new" event when not watching the channel.

I need this event for two reasons:

1. When a user has my product open on multiple devices, it should remain updated in realtime.
2. I'm trying to incorporate a robust ChannenList into my product that handles the notification.message_new event unlike your React SDK component so that the ChannelList can update properly even for channels not being watched.

In both cases, I need this event and I believe this is a bug.

gz#11014

**Comment by dilizarov** [comment]
The one hack I have come up for this is sending messages like this:

```
const message = await channel.sendMessage({
  text: "this is a message text",
  user_id: `${userId}-random-string-which-makes-this-id-not-associated-with-any-user-so-it-triggers-the-notification-for-all-channel-members`
I})
```

Obviously, the hack is less than ideal and I don't think it'll work because I don't always send messages from my server - sometimes I want to use your SDK on the client-side.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11014'>Zendesk ticket #11014</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and come back to you soon.

Cheers
Stream Team

**Comment by nhannah** [comment]
This is fixed now for members in a channel, if you are a member you will get the event even if you sent the message.
