### ISSUE TITLE
Push notifications are not sent to mentioned users

### ISSUE THREAD

**Issue by cjmconie** [GetStream/stream-chat-js#663]
## Issue

Push notifications are not being sent to mentioned users. 

## Code

The simple server-side test function below sends a message and mentions user `rnMXiqQweWPvWhFLKGMfXbvJRw62`. I would expect user `rnMXiqQweWPvWhFLKGMfXbvJRw62` to receive a push notification.

```javascript
// create client in server mode
const serverClient = StreamChat.getInstance(
    streamCredentials.key,
    streamCredentials.secret
);

// test sending a message with a mentioned user
export const _testSendMessage = async () => {
    
    const cid = 'post_BKcepDYFefaJwyrpK7Qe';

    const channel = serverClient.getChannelById(
        "post_comments", // custom channel
        cid,
        {}
    );

    const res = await channel.sendMessage(
        {
            user_id: 'sFRvBHsju2bpzx0dkf7E7v5xlDo1',
            text: 'Server-side mention @admin',
            mentioned_users: ['rnMXiqQweWPvWhFLKGMfXbvJRw62'], // this user should receive a push?
        },
        { skip_push: false } // defaults to false, but set it anyway for good measure
    );

    console.log('res', res);
};
```

Response

200 OK

```text
res {
>    message: {
>      id: 'e4ed1608-1ea3-4ed7-b755-81bee4a034a6',
>      text: 'Server-side test @admin',
>      html: '<p>Server-side test @admin</p>\n',
>      type: 'regular',
>      user: {
>        id: 'sFRvBHsju2bpzx0dkf7E7v5xlDo1',
>        role: 'user',
>        created_at: '2021-03-17T14:26:32.507859Z',
>        updated_at: '2021-04-19T07:03:27.732126Z',
>        last_active: '2021-04-19T05:26:48.274418Z',
>        banned: false,
>        online: false,
>        image: 'https://<redacted>',
>        username: 'test_1', // custom extra data
>        name: 'Test 1'
>      },
>      attachments: [],
>      latest_reactions: [],
>      own_reactions: [],
>      reaction_counts: null,
>      reaction_scores: {},
>      reply_count: 0,
>      cid: 'post_comments:post_BKcepDYFefaJwyrpK7Qe',
>      created_at: '2021-04-19T07:03:27.740134Z',
>      updated_at: '2021-04-19T07:03:27.740134Z',
>      shadowed: false,
>      mentioned_users: [ [Object] ],
>      silent: false,
>      pinned: false,
>      pinned_at: null,
>      pinned_by: null,
>      pin_expires: null
>    },
>    duration: '25.11ms'
>  }
```

### Testing

Note that I have tested push notifications using the CLI with the command below. The push is delivered to the iOS device correctly. So I am sure APNS is setup correctly.

```console
stream chat:push:test --user_id 'rnMXiqQweWPvWhFLKGMfXbvJRw62'
```

### Use Case

We are using an open channel as a commenting system. Sending messages and @mentioning users (triggering push notifications so they know they were @'d) is our main use case.

gz#11211

**Comment by SeniYG** [comment]
Hi there, 

Thanks for reaching out. 
Can I ask if your admin user `rnMXiqQweWPvWhFLKGMfXbvJRw62` is a member of this channel? 
According to the [API push delivery logic](https://getstream.io/chat/docs/javascript/push_introduction/#push-delivery-logic), only channel members can receive push messages. 
Best,

**Comment by shodgetts** [comment]
Hello @cjmconie, It does looks like @SeniYG has probably got this right, but the Issue section of this Github repo is reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at [support@getstream.io](support@getstream.io) with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.

In case our understanding is incorrect and you are describing a bug, we apologise, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.

**Comment by cjmconie** [comment]
Thank you, yes that is indeed the case. My custom channel type is based off of the 'livestream' channel type which allows users to send messages without being channel members.
