### ISSUE TITLE
`user.presence.changed` event not firing

### ISSUE THREAD

**Issue by jackherizsmith** [GetStream/stream-chat-js#666]
Can anyone confirm this, or explain what I should be doing differently.

```
// import
import * as chat from 'stream-chat';
import KEY from 'secrets';
import user from 'user';

// get instance
const chatClient = chat.StreamChat.getInstance(KEY);

// get user
const user_id = user.id;

// connect
await chatClient.connectUser({ id: user.id }, window.localStorage.getItem(c.CHAT_TOKEN));

// query channels
const filter = { type: 'messaging', members: { $in: [ user_id ] }};
const sort = { last_message_at: -1 };
const userChannels = await chatClient.queryChannels(filter, sort, { presence: true });

// listen
chatClient.on(console.log) // logs message.new, message.read, user.watching.start, user.watching.stop, others
```

So everything is logging as it should, I just can't get updates when members have logged in or out. Does anyone else have this issue, or what I might be missing here?

(if there are any glaring code errors here, I've quickly pulled bits together that are either in different files are have different names, but this is functionally how it works at the moment)

gz#11233

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/11233'>Zendesk ticket #11233</a>:<br><br>Hey, thanks for getting in touch. I am looking into this for you now and will get back to you shortly. Please let me know if you have any other questions in the meantime.

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/11233'>Zendesk ticket #11233</a>:<br><br>Hello and thanks for submitting an issue to our GithHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
In case our understanding is incorrect and you are describing a bug, we apologise, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
