### ISSUE TITLE
Typing broken for TypeScript 4.0.2

### ISSUE THREAD

**Issue by pjpscriv** [GetStream/stream-chat-js#669]
I'm getting this same error as issue #623 in an Angular 10.2.3 project using TypeScript 4.0.2. 

```
ERROR in ../../../../node_modules/stream-chat/dist/types/types.d.ts:275:37 - error TS1005: '>' expected.

275     i18n?: RequireAtLeastOne<Record<`${TranslationLanguages}_text`, string>> & {
                                        ~~~
```

![image](https://user-images.githubusercontent.com/16329923/116167190-d30e8380-a753-11eb-86e0-a3844b2fe9d9.png)

Upgrading my whole project to the most recent typescript may be breaking, is it possible to do it just for this package? 

gz#11397

**Comment by pjpscriv** [comment]
Some approaches I've tried:
- Played around with the `"resolutions"` field in `package.json` to no avail. Adding `stream-chat/**/typescript: "4.2.3"` had no effect.
- Upgraded the global typescript version to 4.2.3 but this didn't work because the Angular 10.2.3 compiler has hard limit of typescript 4.0.7.

I currently have it working by using stream-chat @ `2.11.2`, but if there are any better solutions to this let me know. 🙂🙏

**Comment by shodgetts** [comment]
Agent comment from Amin Mahboubi in <a href='https://getstream.zendesk.com/agent/tickets/11397'>Zendesk ticket #11397</a>:<br><br>Have you tried adding `skipLibCheck: true` to your typescript config file?<br><p><em><small>°°°</small></em></p>

**Comment by pjpscriv** [comment]
> Have you tried adding `skipLibCheck: true` to your typescript config file?

@shodgetts yep it's set to true. 

I'll close this issue as I have a workaround for now and it looks like the real solution is upgrading Angular + TypeScript to their latest versions.

**Comment by gilbertl** [comment]
> > Have you tried adding `skipLibCheck: true` to your typescript config file?
> 
> @shodgetts yep it's set to true.
> 
> I'll close this issue as I have a workaround for now and it looks like the real solution is upgrading Angular + TypeScript to their latest versions.

What's the workaround?

**Comment by gilbertl** [comment]
I found a work around. Just patched my local module with

```
diff --git a/node_modules/stream-chat/dist/types/types.d.ts b/node_modules/stream-chat/dist/types/types.d.ts
index 5284549..8d057d6 100644
--- a/node_modules/stream-chat/dist/types/types.d.ts
+++ b/node_modules/stream-chat/dist/types/types.d.ts
@@ -303,9 +303,7 @@ export declare type MessageResponseBase<AttachmentType = UnknownType, ChannelTyp
     };
     created_at?: string;
     deleted_at?: string;
-    i18n?: RequireAtLeastOne<Record<`${TranslationLanguages}_text`, string>> & {
-        language: TranslationLanguages;
-    };
+    i18n?: any;
     latest_reactions?: ReactionResponse<ReactionType, UserType>[];
     mentioned_users?: UserResponse<UserType>[];
     own_reactions?: ReactionResponse<ReactionType, UserType>[] | null;
```

Apologies in advance for not knowing what the proper fix is
