### ISSUE TITLE
queryChannels type doesn't accept joined or invite, but documentation says it should.

### ISSUE THREAD

**Issue by dilizarov** [GetStream/stream-chat-js#680]
https://getstream.io/chat/docs/react/query_channels/

The "Channel Queryable Built-In Fields" shows:

invite: string, must be one of these values: (pending, accepted, rejected)
joined | boolean

in the table

When I do the following, I get type errors:

```ts
const queryResponse = await this.client.queryChannels(
      {
        type: "messaging",
        members: {
          $in: [identifier],
        },
        joined: true,
      },
      [{ last_message_at: -1 }],
      {
        watch: true,
        state: true,
        limit: 30,
      }
    );

```

"Argument of type '{ type: string; members: { $in: string[]; }; joined: boolean; }' is not assignable to parameter of type 'ChannelFilters<ChannelType, LiteralStringForUnion, UserType>'.
  Object literal may only specify known properties, and 'joined' does not exist in type 'ChannelFilters<ChannelType, LiteralStringForUnion, UserType>'."

If I swap `joined: true` with `invite: "pending"`, then I get:

"Argument of type '{ type: string; members: { $in: string[]; }; invite: string; }' is not assignable to parameter of type 'ChannelFilters<ChannelType, LiteralStringForUnion, UserType>'.
  Object literal may only specify known properties, but 'invite' does not exist in type 'ChannelFilters<ChannelType, LiteralStringForUnion, UserType>'."

gz#11983

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11983'>Zendesk ticket #11983</a>:<br><br>Hi

Thanks for reaching out to us.
Can you please let us know the value of the `identifier` from  $in: [identifier]?

Wanted to check if it aligns with LiteralStringForUnion
`export type LiteralStringForUnion = string & {};`

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by dilizarov** [comment]
`identifier` is a `string`

**Comment by shodgetts** [comment]
Agent comment from Dan Carbonell in <a href='https://getstream.zendesk.com/agent/tickets/11983'>Zendesk ticket #11983</a>:<br><br>You need to add to the `ChannelType` generic so TypeScript knows to extend the default channel object with your custom data. You can follow our TypeScript wiki for more information, https://github.com/GetStream/stream-chat-react/wiki/TypeScript-Support. You'll need to pass something similar to `{ joined: boolean, invite: 'pending' | 'accepted' | 'rejected' }` into the generic for `ChannelType`
<br><p><em><small>°°°</small></em></p>

**Comment by nhannah** [comment]
Also please note our internal membership system uses a different set of keys: 

```
  invite_accepted_at?: string;
  invite_rejected_at?: string;
  invited?: boolean;
```
