### ISSUE TITLE
Getting issue with queryChannel

### ISSUE THREAD

**Issue by muhammadirfanu** [GetStream/stream-chat-js#684]
I am trying to query channels based on user '1'. Here is the error I am getting: 

`{"code":4,"message":"QueryChannels failed with error: "expected number for field "sort[0].direction" but got number `0`"","StatusCode":400,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response"}`

This is the code (pasted from getstream tutorial section).

```
const filter = { type: 'messaging', members: { $in: ['1'] } }; 
const sort = [{ last_message_at: -1 }]; 
 
const channels = await authClient.queryChannels(filter, sort, { 
    watch: true, // this is the default 
    state: true, 
}); 

```
The payload is following:
`{"filter_conditions":{"members":{"$in":["1"]}},"sort":[{"field":"0","direction":{"last_message_at":-1}}],"state":true,"watch":true,"presence":false}`

gz#12066

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/12066'>Zendesk ticket #12066</a>:<br><br>Hi, thanks for reaching out. Did you also open a support ticket related to this issue?
<br><p><em><small>°°°</small></em></p>

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/12066'>Zendesk ticket #12066</a>:<br><br>Hi

Please change the sort field like this -

`"sort": [{"field":"name", "direction": -1}],`

Your query would be like this -


    {
    "filter_conditions":{"members":{"$in":["1"]}},
    "sort": [{"field":"last_message_at", "direction": -1}],
    "state":true,"watch":true,"presence":true,
    }


Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by muhammadirfanu** [comment]
No success, still having the same issue.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/12066'>Zendesk ticket #12066</a>:<br><br>Hi

Sure, we can look at this for you, would you mind sending your code snippet along with your API-Key to support@getstream.io Thanks.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by shodgetts** [comment]
Closing this support request, please email support@getstream.io to continue the conversation. We prefer to reserve Github issues to feature requests and bugs. 
-Stephen
