### ISSUE TITLE
Typescript Error at connection.d.ts

### ISSUE THREAD

**Issue by ryanhanwu** [GetStream/stream-chat-js#687]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `stream-chat@3.10.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/stream-chat/dist/types/connection.d.ts b/node_modules/stream-chat/dist/types/connection.d.ts
index 500e927..cc5902c 100644
--- a/node_modules/stream-chat/dist/types/connection.d.ts
+++ b/node_modules/stream-chat/dist/types/connection.d.ts
@@ -104,6 +104,7 @@ export declare class StableWSConnection<ChannelType extends UnknownType = Unknow
      * @param {Event} event Event with type online or offline
      *
      */
+    // @ts-ignore
     onlineStatusChanged: (event: Event) => void;
     onopen: (wsID: number) => void;
     onmessage: (wsID: number, event: WebSocket.MessageEvent) => void;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Original error
```
node_modules/stream-chat/dist/types/connection.d.ts:107:34 - error TS2304: Cannot find name 'Event'.

107     onlineStatusChanged: (event: Event) => void;
                                     ~~~~~

```

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/12172'>Zendesk ticket #12172</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and come back to you soon.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by nhannah** [comment]
You tsconfig need's to include `"lib": ["DOM"]`, this `Event` type comes from the DOM types.
