### ISSUE TITLE
Chrome timers throttling causing missed events when tab in background for longer time

### ISSUE THREAD

**Issue by tomaszpaczesny** [GetStream/stream-chat-js#694]
We are experiencing an issue, for quite some time already, where when our application (using GetStream chat) is in background tab in Chrome for a longer time (10-15 min at least) connection starts to go off and on (`online` state) and during that time, if a new event comes in (e.g. new message), it is usually not delivered to our callback. When tab is moved to foreground, connection restores correctly and events are delivered fine again.

In our investigations we noticed that most likely it is related to background timer throttling in Chrome:
https://developers.google.com/web/updates/2017/03/background_tabs

E.g. when we play audio all the time in our app (app is considered foreground), the above does not occur. It seems that GetStream is using timers/intervals heavily and this is being affected by the throttling. Since getstream is websocket-based I think the assumption is it should be able to deliver events even when in background.

Happens for versions of `stream-chat` `1.8.0` and `3.9.0`. 

gz#12358

**Comment by vishalnarkhede** [comment]
@tomaszpaczesny we are working on patch to fix this issue. It should be released early next week!!

**Comment by vishalnarkhede** [comment]
This issue has been fixed as part of `v3.11.0`!!

**Comment by tomaszpaczesny** [comment]
Thank you!

**Comment by vishalnarkhede** [comment]
@tomaszpaczesny please let us know if you see the issue fixed on your end after upgrading!!
