### ISSUE TITLE
verifyWebhook failed with express request

### ISSUE THREAD

**Issue by Martin-J-Lee** [GetStream/stream-chat-js#695]
We are trying to consume the chat events via the webhook.
After monitoring the logs, We have discovered that `verifyWebhook` failed on `message.new` event.
cid of a sample message is `Comments:5ba71ce5-5015-4e7d-9568-2123fe2ed058`

We are using express and `JSON.stringify(req.body)` to parse body to string before calling `verifyWebhook`.
Other event type seems working correctly, can confirm - `channel.created` & `message.read`

This is a blocker, for now, please address it ASAP or provide a workaround.

gz#12378

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/12378'>Zendesk ticket #12378</a>:<br><br>Hi

Thanks for reaching out to us.
Can you please try calling `verifyWebhook` with the raw body?

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by Martin-J-Lee** [comment]
> Agent comment from Seetha in [Zendesk ticket #12378](https://getstream.zendesk.com/agent/tickets/12378):
> 
> Hi
> 
> Thanks for reaching out to us.
> Can you please try calling `verifyWebhook` with the raw body?
> 
> Cheers
> Seetha
> 
> 
> _°°°_

It won't work due to the following error
```
{"level":"error","time":"2021-06-02T03:11:23.260Z","pid":784,"hostname":"068cab251d23","error":{"type":"NodeError","message":"The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
```
the method signature is
 `verifyWebhook(requestBody: string, xSignature: string)`

**Comment by Martin-J-Lee** [comment]
similar issue with
```
"type": "message.flagged",
    "cid": "Comments:93b3fda3-dda2-4688-9b00-baa8576942b1",
```

**Comment by Martin-J-Lee** [comment]
any update on this? It appears to be there are more types that are failing on the `verifyWebhook`.
I've also tried to call with body buffer or string, not parsing it from the json object, which fails every verification, not only the type I have mentioned above.

**Comment by ferhatelmas** [comment]
You need to pass the raw body bytes to verification as received in the request. 

If you do any kind of manipulation like parsing into json and then stringification, there is no guarantee, you will generate the same payload.
