### ISSUE TITLE
Shadow banned users still sending push notifications

### ISSUE THREAD

**Issue by jamesdunay** [GetStream/stream-chat-js#702]
We're working on implementing the new shadow ban moderation feature and ran into an issue where users that have been globally shadow banned, i.e. shadowed:true are still generating push notifications when they message other users. 

Was wondering if there was a way to exclude them from sending push notifications, since those are handled by stream?

gz#12834

**Comment by shodgetts** [comment]
Agent comment from Zachery Converse in <a href='https://getstream.zendesk.com/agent/tickets/12834'>Zendesk ticket #12834</a>:<br><br>Hi James,

Thanks for reaching out about the shadow ban feature. So you would like messages from users that are shadow banned to not generate push notifications?

This can be done using the skip_push field on the message object - docs

    const message = await channel.sendMessage({
        text: '@Josh I told them I was pesca-pescatarian',
        skip_push: true,
    });

The API just updates the `shadowed` field to `true` and leaves the decisions on how to handle shadow banned users up to you.

Feel free to let me know if you have any questions!

Cheers,
-Zachery
 Getstream.io
<br><p><em><small>°°°</small></em></p>

**Comment by ferhatelmas** [comment]
There is a mistake in the snippet though. 

Control flags are passed separately not to conflict with custom properties.

```js
const message = await channel.sendMessage({
    text: '@Josh I told them I was pesca-pescatarian'
}, {
    skip_push: true
});
```

**Comment by shodgetts** [comment]
Agent comment from Zachery Converse in <a href='https://getstream.zendesk.com/agent/tickets/12834'>Zendesk ticket #12834</a>:<br><br>Hello James,

I'll go ahead and close this ticket, but feel free to open it back up by responding with any further questions or comments.

Have a beautiful day!

Cheers,
-Zachery
 Getstream.io
<br><p><em><small>°°°</small></em></p>
