### ISSUE TITLE
client.partialUpdateMessage does not work for custom fields.

### ISSUE THREAD

**Issue by nicebro** [GetStream/stream-chat-js#703]
Hey guys, seems I have bug with client.partialUpdateMessage, it does not work with custom fields for me.
This is example from docs

```js
let originalMessage = (await channel.sendMessage({ 
        text: 'this message is about to be partially updated', 
        color: 'red', 
        details: { 
            status: 'pending' 
        }, 
    }) 
).message; 
```

When I do something like this
```js
await client.partialUpdateMessage(
    originalMessage.id,
    {
      set: {
        color: 'does not work',
        moreCustomData: '...',
      },
    }
);
```
I does not update any of fields

If request looks like this with additional changes for text field It does works.
```js
await client.partialUpdateMessage(
    originalMessage.id,
    {
      set: {
        text: 'if add change here update works',
        color: 'works',
        moreCustomData: '...',
      },
    }
);
```

gz#12896

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/12896'>Zendesk ticket #12896</a>:<br><br>Hello,

Thanks for getting in touch. I'll take a look into this just as soon as I can. In the meantime, would you mind also letting me know which version of the JS SDK you're using here?
<br><p><em><small>°°°</small></em></p>

**Comment by nicebro** [comment]
It's 3.11.0

**Comment by ferhatelmas** [comment]
I tested this and it works as expected. Could you share the whole snippet you are testing?

**Comment by nicebro** [comment]
@ferhatelmas 
```js
/* eslint-disable */
const { StreamChat } = require('stream-chat');

const STREAM_KEY = '';
const STREAM_SECRET = '';
const stream = new StreamChat(STREAM_KEY, STREAM_SECRET);

const main = async () => {
    const [channel] = await stream.queryChannels({}, {}, {});
    const { message } = await channel.sendMessage({
        text: 'this message is about to be partially updated',
        color: 'red',
        details: {
            status: 'pending',
        },
        user_id: channel.data.created_by.id
    });

    const messageId = message.id;

    await stream.partialUpdateMessage(
        messageId,
        {
          set: {
            color: 'blue'
          },
        },
        { id: channel.data.created_by.id },
    );

    const updatedMessage = await stream.getMessage(messageId);
    console.log(updatedMessage);
};

main().catch(console.log);
```

Color should be blue but I'm getting red

**Comment by ferhatelmas** [comment]
@nicebro checking it further, thanks for the snippet /cc @yaziine

**Comment by yaziine** [comment]
@nicebro thank you for reporting this, it was a bug on our side actually. 

It has been fixed and you can expect it to be released by next week.

Closing this, don't hesitate to reopen if needed.
