### ISSUE TITLE
Multi-tenant/teams settings seem to be missing

### ISSUE THREAD

**Issue by zperlo** [GetStream/stream-chat-js#704]
https://github.com/GetStream/stream-chat-js/issues/701 is one part of this. 

Additionally, I was previously using `Client.Event.team` to get the team on new message events, and it is no longer in the types. What happened to these values? Do you know the last version that supported this?

gz#12945

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/12945'>Zendesk ticket #12945</a>:<br><br>Hi,

Thanks for reaching out to us.
We will check this and come back to you soon.

Best,
<br><p><em><small>°°°</small></em></p>

**Comment by mahboubii** [comment]
@zperlo Could you provide more details? I don't see any related changes to the type in the last few months.

**Comment by zperlo** [comment]
@mahboubii Happy to, sorry I didn't have them in my first message. My team is upgrading chat in our app, as we are petty far behind. We were on version 2.1.2 and upgraded to 3.11.0. I had looked through the changelog, and I don't see any references to changes of these fields, which is why I was confused, given that we use them. Most of the changes seemed like they wouldn't affect us negatively, but we extensively use the teams api and need that in our events. I'm not sure why this wasn't listed as a breaking change/what version would be safe to upgrade to. Thanks for taking a look!

**Comment by zperlo** [comment]
Any further info on this @mahboubii ?

**Comment by zperlo** [comment]
Seems like https://github.com/GetStream/stream-chat-js/pull/716 will fix this issue

**Comment by vishalnarkhede** [comment]
This has been merged and will be released today
