### ISSUE TITLE
The getRateLimits method returns a 500 error every time

### ISSUE THREAD

**Issue by Chochek** [GetStream/stream-chat-js#708]
When I try calling `client.getRateLimits()` I get a 500 error

```
{
  "code": -1,
  "message": "GetRateLimits failed with error: \"\"",
  "StatusCode": 500,
  "duration": "0.00ms",
  "more_info": ""
}
```

The same thing happens when I try to limit it to specific endpoints or platforms

gz#13008

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/13008'>Zendesk ticket #13008</a>:<br><br>Hi,

Thanks for reaching out. After some experimenting, I noticed I had the same error when I instantiated the client before calling this endpoint. Can you check that this is the case in your code? The follow worked just fine as a server side function and without connectUser().


    const test = async () => {
       const chatClient = new StreamChat(appKEY, secret);
       const userID = "ryan";
       limits = await chatClient.getRateLimits();
       return limits;
    }



Best,
Ryan
<br><p><em><small>°°°</small></em></p>

**Comment by Chochek** [comment]
Hi, thanks for the reply but I'm not sure I understand. You're saying I can't call the rate limits endpoint after I instantiate the client?

I should have mentioned that I am using JS (React) and in the docs it says that I need to do this to connect to Stream Chat

```
import { StreamChat } from 'stream-chat'; 
 
const chatClient = StreamChat.getInstance(apiKey); 

chatClient.connectUser({ id: userId }, userToken);
```
 
Which I am doing, and after that I try calling `chatClient.getRateLimits()` and get the above mentioned error.
If I try calling this endpoint before `chatClient.connectUser(...)` I get an error but that is to be expected IMO

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/13008'>Zendesk ticket #13008</a>:<br><br>Hi,

Thanks for your patience. I noticed this method works when using server side credentials (i.e. key and secret) as shown above. Checking in with the team now to learn more. Can you please tell me a bit more about your use case here?

Best,
Ryan
<br><p><em><small>°°°</small></em></p>

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/13008'>Zendesk ticket #13008</a>:<br><br>Hi,

To follow up here, getRateLimits() is only going to be available server-side at the moment. Please let me know if you have any questions here. I've provided a code sample of how to do this below for convenience.


    const chatClient = new StreamChat.getInstance(appKEY, secret);
    const limits = await chatClient.getRateLimits();
    return limits;


Best,
Ryan
<br><p><em><small>°°°</small></em></p>
