### ISSUE TITLE
Incorrect documentation for best practices on disconnectUser???

### ISSUE THREAD

**Issue by smaccoun** [GetStream/stream-chat-js#709]
The documentation for best practices on disconnectUser is extremely confusing to me. Maybe I'm missing something

In the example of what *not* to do, it says the following

```
// ❌ This will keep on creating new websocket connection 
// everytime useEffect hook gets executed (on changes to `currentUser`) 
```

However, it is in this example that `useEffect` does *not* change with `currentUser`, whereas for the example of what to do it does. Is this backward?

See this

![Screen Shot 2021-06-27 at 9 54 25 AM](https://user-images.githubusercontent.com/4641989/123547173-b7146780-d72d-11eb-9ffe-61e83bbf0488.png)

VS

![Screen Shot 2021-06-27 at 9 55 00 AM](https://user-images.githubusercontent.com/4641989/123547182-c72c4700-d72d-11eb-8b0f-514bfc676917.png)

Further, apart from this, the only other difference is in the teardown logic. This here is also very confusing. For the "correct" teardown logic it says

```
return () => { 
        await chatClient.disconnectUser(); 
    } 
```

Whereas the incorrect version is

```
return () => chatClient.disconnectUser(); 
```

Maybe my JS skills are choppy, but in the correct version I don't believe that's even legal javascript, since the return on useEffect is not async. If anything, shouldn't it be

```
return () => { 
        chatClient.disconnectUser().then(_ => {console.log("DISCONNECTED")})
    } 
```

gz#13051

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/13051'>Zendesk ticket #13051</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and get back to you soon.

Best,
<br><p><em><small>°°°</small></em></p>

**Comment by nhannah** [comment]
Hi I am currently cleaning up issues, looks like the docs on this have [since been fixed](https://getstream.io/chat/docs/javascript/instantiating_the_client/?language=javascript&q=This%20will%20keep%20on%20creating%20new%20websocket%20connection).
