### ISSUE TITLE
stream-chat node client.updateChannels method

### ISSUE THREAD

**Issue by fearless23** [GetStream/stream-chat-js#710]
I can see there is batch channel update method for JAVA
https://getstream.io/chat/docs/java/batch_channel_update/

Is there same feature for stream-chat Node 3.11.0

gz#13097

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out.
Unfortunately, this endpoint you mentioned isn't available yet. Actually, this docs section shouldn't be accessible to the public. 
I will report this issue to our documentation team so it can be fixed. Sorry for the inconvenience.

Best,
