### ISSUE TITLE
[multi-tenant] creating a channel returns an error when it already exists for another team

### ISSUE THREAD

**Issue by danychi** [GetStream/stream-chat-js#711]
There is a problem when creating a channel when multitenancy is enabled.

Imagine you have team A that has a channel with the name "general", now if team B decides to create a channel with the same name, this returns the following error:

```js
{
  StatusCode: 403,
  code: 17,
 duration: "0.00ms",
  message: "GetOrCreateChannel failed with error: \"user from teams [\"5a3cb0ad457dfc0196c2ab7c\"] cannot query a 
  channel for team \"a\"\""
  more_info: "https://getstream.io/chat/docs/api_errors_response",
}
```

The call is being made using the `client.channel`

```js
  const { client, setActiveChannel } = useChatContext<
    TeamAttachmentType,
    TeamChannelType,
    TeamCommandType,
    TeamEventType,
    TeamMessageType,
    TeamReactionType,
    TeamUserType
  >()

const newChannel = await client.channel(createType, channelName, {
  name: channelName,
  members: selectedUsers,
  team: teamID
})
```

gz#13189

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/13189'>Zendesk ticket #13189</a>:<br><br>Hi there,

Thanks for getting in touch. This seems like expected behavior from my understanding. As per the docs:


    Channel teams allows you to ensure proper permission checking for a multi tenant application. Keep in mind that you will still need to enforce that channel IDs are unique. A very effective approach is to include the team name as a prefix to avoid collisions. (ie. "red-general" and "blue-general" instead of just "general")


https://getstream.io/chat/docs/javascript/multi_tenant_chat/?language=javascript
<br><p><em><small>°°°</small></em></p>
