### ISSUE TITLE
unread_messages count missing in type

### ISSUE THREAD

**Issue by statico** [GetStream/stream-chat-js#718]
Re: https://github.com/GetStream/stream-chat-js/blob/master/src/channel_state.ts#L48

This is missing `unread_messages: number`, so after calling `client.queryChannels()`, accessing `channels[...].state.read[...].unread_messages` causes a type error.

See also: https://github.com/GetStream/stream-chat-js/issues/336

gz#13624

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/13624'>Zendesk ticket #13624</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and come back to you soon.

Best,
<br><p><em><small>°°°</small></em></p>

**Comment by zacheryconverse** [comment]
Hi @statico,

I believe [this PR](https://github.com/GetStream/stream-chat-js/pull/871) fixes this issue for you. I'll go ahead and close this, but please reach out if you have any questions.

Cheers,
