### ISSUE TITLE
UpSertUser

### ISSUE THREAD

**Issue by elemanhillary** [GetStream/stream-chat-js#719]
can we `upsertUser` with image?

for-example:
```javascript
  await streamChat.upsertUser({
      id: existingUser.username,
      name: existingUser.username,
      role: "user",
      image: existingUser.profileDetails.profileImage,
  })
```

gz#13665

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/13665'>Zendesk ticket #13665</a>:<br><br>Hi

Thanks for reaching out to us.
Yes, possible. If you are seeing any issues, we would suggest emailing our Customer Success and Engineer support team with your application key or ID and we’ll be able to help you out

We would request you to direct any such technical questions to support@getstream.io as the issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions.

Thanks for your understanding.

Best,
<br><p><em><small>°°°</small></em></p>
