### ISSUE TITLE
Usage with nestjs fails with type errors

### ISSUE THREAD

**Issue by heromiyo** [GetStream/stream-chat-js#738]
import {StreamChat} from "stream-chat";

 async getStreamChatToken(user: UserPayload) {
    const serverClient = StreamChat.getInstance(this.configService.get(ConfigKey.STREAM_CHAT_API_KEY),
        this.configService.get(ConfigKey.STREAM_CHAT_SECRET_KEY));
    let token: string = "";
    if (user.user_entity != null) {
      token =  await serverClient.createToken(user.uid)
    }
    return {
      token: token
    }

  }

Nestjs project fails to compile with the following errors:

node_modules/stream-chat/dist/types/types.d.ts:309:37 - error TS1005: '>' expected.

309     i18n?: RequireAtLeastOne<Record<`${TranslationLanguages}_text`, string>> & {
                                        ~~~

node_modules/stream-chat/dist/types/types.d.ts:309:78 - error TS1109: Expression expected.

309     i18n?: RequireAtLeastOne<Record<`${TranslationLanguages}_text`, string>> & {
                                                                                 ~

node_modules/stream-chat/dist/types/types.d.ts:310:39 - error TS1005: ',' expected.

310         language: TranslationLanguages;
                                          ~

node_modules/stream-chat/dist/types/types.d.ts:312:22 - error TS1109: Expression expected.

312     latest_reactions?: ReactionResponse<ReactionType, UserType>[];
                         ~

node_modules/stream-chat/dist/types/types.d.ts:313:21 - error TS1109: Expression expected.

313     mentioned_users?: UserResponse<UserType>[];
                        ~

node_modules/stream-chat/dist/types/types.d.ts:314:19 - error TS1109: Expression expected.

314     own_reactions?: ReactionResponse<ReactionType, UserType>[] | null;
                      ~

**Comment by vishalnarkhede** [comment]
Hey @heromiyo what version of typescript are you using? Also if you could share a codesandbox link reproducing the issue, that would be great.

Seems to be working fine here - https://codesandbox.io/s/nest-forked-vdvmt?file=/src/main.ts

**Comment by vishalnarkhede** [comment]
Please upgrade to later versions of typescript which supports string templates, it should fix this issue for you.
