### ISSUE TITLE
channel.state.unreadCount always returns 0 if current user is not returned in channel.read

### ISSUE THREAD

**Issue by alinenko** [GetStream/stream-chat-js#749]
### BUG
When there are more than 100 channel members and the current user is not returned in the _**channel.read**_ than **_channel.state.unreadCount_** is always 0.

### DETAILS
Seems like this [line ](https://github.com/GetStream/stream-chat-js/blob/d796ebf95a45cf833028b74fc55e274cf9a2679d/src/channel.ts#L1771) is never executed if the member is not returned in **_channel.read_**. The possible fix is to always return the member we make request form to **_channel.read_**

Thanks in advance!

**Comment by wildebeast** [comment]
This is a fairly large issue for us, since it's preventing us from showing when a channel has unread messages.

**Comment by yaziine** [comment]
Actually, we don't support unread count for channels with +100 members. This is not trivial to fix as it implies a lot of performance impact but we are working hard to fix this issue currently.

Closing the ticket for now, we will let you know once it's fixed.
