### ISSUE TITLE
Get unread messages count including messages in threads

### ISSUE THREAD

**Issue by jsruvi** [GetStream/stream-chat-js#756]
Getstream allows to send messages in thread

https://getstream.io/chat/demos/team/

![Screenshot_1](https://user-images.githubusercontent.com/8143049/130189620-91c6c2c3-96b2-4d0b-b884-5a55c8458d16.png)

I want to show 'unread messages indicator' even when there are some unread messages in thread

For regular messages I can do something like this 
https://getstream.io/chat/docs/react/unread/

```js
client.on((event) => { 
     if (event.total_unread_count !== undefined) { 
         console.log(event.total_unread_count); 
     } 
 
     if (event.unread_channels !== undefined) { 
         console.log(event.unread_channels); 
     } 
});
```

But it doesn't work for messages in thread

**Comment by ferhatelmas** [comment]
This isn't supported at the moment but we're working on it to support it. When there are updates, will drop a note here. 

For now, closing this ticket.

**Comment by lucaswhitman** [comment]
@ferhatelmas any update?

**Comment by ferhatelmas** [comment]
It's still being worked on. It seems it will be hard to include into the first enhanced version but clearly in the scope to support cc @bokan

**Comment by lucaswhitman** [comment]
@ferhatelmas is there a rough date on that piece of the roadmap? We're getting ready to build this ourselves if it's too far out.

**Comment by ferhatelmas** [comment]
It's difficult to give an exact timeline and commit to it since it's a drastic work but I can guarantee it's heavily worked on at the moment.

**Comment by lucaswhitman** [comment]
@ferhatelmas totally fair. Is there a ballpark estimate by chance? Weeks, months, year?

**Comment by ferhatelmas** [comment]
Months. Target is more or less by this quarter.
