### ISSUE TITLE
TypeError: 'image' property is missing on client.user object

### ISSUE THREAD

**Issue by gio-shara-code** [GetStream/stream-chat-js#766]
I am getting client instance as following:

`const client = StreamChat.getInstance('key')`

I want to grab `client.user.image` which suppose to be there (Because I logged out the user object in the console and it was there as expected) but the type is missing the property 'image' on user object.

**User Object in the console**
![user object console logged](https://user-images.githubusercontent.com/74867549/132818937-ebea9e73-7bc3-43f1-bef0-6bc865d399e1.PNG)

**Dependecies:**
"stream-chat": "^4.1.0",

**Comment by vishalnarkhede** [comment]
Hey @gio-shara-code `image` is a custom property on user object. So it needs to be explicitely set as part of User generic type. Please check this sample app as an example -  https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/SampleApp/src/types.ts#L15
 
Here is the documentation for typescript implementation for this js client - https://github.com/GetStream/stream-chat-js#typescript-v2xx
