### ISSUE TITLE
window.removeEventListener is not a function

### ISSUE THREAD

**Issue by racsmith277** [GetStream/stream-chat-js#773]
We are developing stream chat on React Native and are getting an error every time the app goes to background mode: 
![Simulator Screen Shot - iPhone 12 - 2021-09-17 at 15 33 08](https://user-images.githubusercontent.com/51767570/134090247-e262a0ad-449e-4e11-bc02-a8690dbd2c74.png)

I believe the source of the error lies in this library, not in the react native sdk. The useIsOnline hook in the RN library calls client.closeConnection() when app is sent to background ([link](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Chat/hooks/useIsOnline.ts#L50)), which triggers the websocket to disconnect. 

the error arises when _removeConnectionListeners function in connection.ts library attempts to call window.removeEventListener, which is not defined. There seems to be a typo in the check on this line: https://github.com/GetStream/stream-chat-js/blob/f56a58a9502e34a248051b0d787571c3b51a0b4d/src/connection.ts#L721

I believe it should be checking if window.removeEventListener is not null, instead of window.addEventListener. This would fix the bug we are experiencing in the RN SDK.

**Comment by vishalnarkhede** [comment]
Hey @racsmith277 this has been fixed and be part of next release.
