### ISSUE TITLE
Search messages sort not affecting results

### ISSUE THREAD

**Issue by dariuscosden** [GetStream/stream-chat-js#776]
Following the docs [here](https://getstream.io/chat/docs/react/search/), I would like to return the first message for a user in a channel. However, the sorting seems to have no effect on the results returned.

Here is the query I am calling
```javascript
const search = await ChatState.client?.search(
  { id: { $eq: this.channel.id! } },
  { 'user.id': userId },
  { limit: 1, offset: 0, sort: { created_at: 1 } },
);
```

The above will always return the most recent message even though `created_at` is set to 1, which should order it by ascending. What's even more curious is that changing it to `createdAt: -1` will return the same results.

I have also tried `updated_at`, and even returning more than one result to inspect the order they come in. The order is always the same regardless of what sorting I have provided. Am I missing something or is this a bug?

`stream-chat 4.0.0`
`stream-chat-react-native 3.7.2`

**Comment by vishalnarkhede** [comment]
Hey @dariuscosden `sort` feature on message search is part of search version 2. To enable it for your application, please drop us an email for this request along with your appId support@getstream.io
