### ISSUE TITLE
[Error: StreamChat error code 17: GetOrCreateChannel failed with error - Error on creating a new channel multi tenant config

### ISSUE THREAD

**Issue by ANIBIT14** [GetStream/stream-chat-js#778]
Getting this error on creating a channel in stream, the code is
    const newChannel = client.channel('messaging', {
                                          team: 'team_id',
                                           members,
                                           });
    await newChannel?.watch();

  
  The error is 
  ERROR [Error: StreamChat error code 17: GetOrCreateChannel failed with error: "User '60b79b95ac956f00712066a7' with roles ['user', 'channel_member'] from teams ['7fdfce50-ba02-4a4d-976a-247ef95a6d50', '02659a2a-8dc1-4604-99e7-ca90e24b59e3'] cannot access resource in scope 'messaging' because requested resource does not belong to any team"]
  
  can someone explain why this might be happening?

gz#15413

**Comment by luisgereda** [comment]
Hello and thanks for submitting an issue to our GitHub repository.  The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.

**Comment by tiarnanalexander** [comment]
Hi, was this error fixed? I have the same error

**Comment by amy-r** [comment]
same error. has this been fixed?

**Comment by tiarnanalexander** [comment]
> same error. has this been fixed?

Yes, the getstream support helped me fix this issue. It was mostly down to how I created the channels server-side.

**Comment by razak1104** [comment]
please has the error been fixed I'm having a similar issue
