### ISSUE TITLE
Mark as unread?

### ISSUE THREAD

**Issue by kyriacos** [GetStream/stream-chat-js#797]
Any way we can mark a channel and/or message as unread?

Thanks!

**Comment by theweiweiway** [comment]
This would be amazing to have for us as well!

**Comment by whiplash00** [comment]
I second this. Had received request for "mark as unread". This is pretty much standard feature for modern chat apps.

**Comment by giacogiaco** [comment]
We would appreciate this too!
@shodgetts can you provide any information on when to expect this feature?

**Comment by miagilepner** [comment]
Thanks for reporting this. This is a good idea and we've added this as a feature request to our backlog with your user stories attached. We don't yet have an estimate of when we will be able to release this.

Because this issue describes a backend feature and is not specific to the javascript SDK, I'm going to close this issue.

**Comment by tappking** [comment]
Definitely something that my test users would like to see from a consumer perspective. Thanks -- hopefully in 2023!

**Comment by nvahalik** [comment]
What's the difference between this and using a custom tag?

**Comment by aayushagrawal135** [comment]
I would be interested in this feature too, please post when this is available!

**Comment by tispratik** [comment]
We're also very interested in this feature. Thank you!

**Comment by gwesterman** [comment]
Also requesting this feature as it is pretty standard for any chat application.

**Comment by jckyeh** [comment]
Also requesting this!

**Comment by gimurpe** [comment]
@miagilepner is there a place where we can keep track of the decisions on this matter. Our clients are asking for this feature and I would like to see if it's ever going to be possible

**Comment by szuperaz** [comment]
Hi,

This has been implemented in stream-chat@8.15.0. The [documentation](https://getstream.io/chat/docs/javascript/unread_messages/?language=javascript) has the details about the feature.

**Comment by gimurpe** [comment]
@szuperaz we noticed that the channel preview is not being highlighted as the other other channels that have unread message when the message is marked as unread using the channel.markUnread method. Even tried clicking on another channel to see if moving the focus to another preview would allow that to happen but no luck. Do you know if this is expected or is there another way to achieve this? Thanks in advance
