### ISSUE TITLE
Typescript errors in Node.js

### ISSUE THREAD

**Issue by AlexRypun** [GetStream/stream-chat-js#834]
I was using `stream-chat` `v1.10.2` on the server-side. It worked fine.
Now I want to upgrade to the latest version (5.0.0) which already uses typescript. But typescript compiler fails with errors:
`Cannot find name 'File'`, `Cannot find name 'Event'`, `Cannot find name 'AbortSignal'`. This is right because the library uses browser's objects that don't exist in Node.js environment.
![image](https://user-images.githubusercontent.com/62097553/144480255-6b9dc63e-4bb5-446f-b673-1d9a268688e2.png)

How can I fix that?

**Comment by mahboubii** [comment]
You can fix this by either adding `DOM` lib to your typescript config or enabling `skipLibCheck`:
```
// tsconfig.json

{
  "compilerOptions": {
    "lib": ["DOM"],
    "skipLibCheck": true
  }
}

```

**Comment by AlexRypun** [comment]
Thanks, I've already added `"skipLibCheck": true` and it works. But is it nice solution?

**Comment by mahboubii** [comment]
It is quite standard, you don't necessarily need the compiler to check all the types of libraries you use, it would increase your build time drastically.
