### ISSUE TITLE
Typescript error w TS 3.9.10 and latest package - cannot build

### ISSUE THREAD

**Issue by bityardigans** [GetStream/stream-chat-js#841]
Getting 29+ type errors in types.d.ts, same error over and over:
node_modules/stream-chat/dist/types/types.d.ts:339:16 - error TS1109: Expression expected.

tried going back to 4.4.3 and same issue. any workaround/fix?

**Comment by ferhatelmas** [comment]
You might see this issue: https://github.com/GetStream/stream-chat-js/issues/834

cc @mahboubii

**Comment by mahboubii** [comment]
@bityardigans what is the version of `typescript` you're using? we have some errors on the recent versions that we have not resolved yet.
Ideally, you should activate [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) in your tsconfig file so your compiler skips verifying internal types of the dependencies.
