### ISSUE TITLE
member_limit doesn't exist in type 'ChannelOptions' in queryChannels

### ISSUE THREAD

**Issue by akasuv** [GetStream/stream-chat-js#846]
<img width="1165" alt="CleanShot 2021-12-17 at 10 51 28@2x" src="https://user-images.githubusercontent.com/30253166/146481200-480f2e63-46cb-4b00-9037-c7fa8d8d3786.png">

**Comment by petyosi** [comment]
@akasuv you need to upgrade to the latest version of the `stream-chat-js` package, [which includes the `member_limit` definition](https://github.com/GetStream/stream-chat-js/blob/d9d8e5722379041cc9f7e99e251a429bec0efa50/src/types.ts#L700).
