### ISSUE TITLE
channel.updatePartial isn't live updating watched channels.

### ISSUE THREAD

**Issue by izakfilmalter** [GetStream/stream-chat-js#852]
I am doing the following to toggle a boolean in the channel:

```ts
const setCallActive = async (callActive: boolean) => {
  console.log(channel.initialized) // true

  const update = await channel.updatePartial({ set: { callActive: true } });

  console.log({
    updateValue: update.channel.callActive // true
    channelValue: channel.data?.callActive // false
  })
}
```

I am only seeing the updated data within the the `update`. This means I need to track it in local state, but this breaks because another client might change the value, and I can't update it then.

**Comment by vanGalilea** [comment]
@izakfilmalter [Closed](https://github.com/GetStream/stream-chat-js/pull/1033) and will be released soon
