### ISSUE TITLE
channel.truncate({hard_delete:true}) does not actually remove the messages (GDPR)

### ISSUE THREAD

**Issue by andreibarabas** [GetStream/stream-chat-js#906]
According to the docs, putting {hard_delete} should completely remove the messages, which it currently does not. Here is a small repro you can use and you will see the final call raises an error ` 'SendMessage failed with error: "a message with ID 1234 already exists"',`

```
import {StreamChat} from 'stream-chat';

// add your own
const apiKey = '';
const apiSecret = '';
const adminId = '';



const serverClient = StreamChat.getInstance(apiKey, apiSecret);

async function run() {
  const channel = serverClient.channel('messaging', 'dummy-id', {
    created_by_id: adminId,
  });
  await channel.create();

  await channel.sendMessage({
    id: '1234',
    text: 'This message should be inserted',
    user_id: adminId,
  });

  //now trunctate with message deletion
  await channel.truncate({hard_delete: true});

  // send the same message again. since it was deleted by hard_delete, it should be possible to do so
  await channel.sendMessage({
    id: '1234',
    text: 'This message should be inserted',
    user_id: adminId,
  });
}

run();

```

**Comment by ferhatelmas** [comment]
This operation is async and can take some time to complete according to the number of messages to be deleted.

**Comment by andreibarabas** [comment]
I thought so, but that async is stuck somewhere.
I tested the same code with channel.delete({hard_delete: true}) and it works like magic.

**Comment by ferhatelmas** [comment]
This call `channel.delete({hard_delete: true})` isn't async.

**Comment by ferhatelmas** [comment]
I would close this ticket since it's async and I would suggest adding some sleep before checking if you care about completion.

**Comment by andreibarabas** [comment]
I understand, but how much "sleep" is the right amount?

If it's sync, the SDK should then return a taskId that we can check periodically and see if it has indeed been truncated, no?

**Comment by andreibarabas** [comment]
Even a 1 minute sleep is not enough. tried it out now.

**Comment by ferhatelmas** [comment]
> I understand, but how much "sleep" is the right amount?

job is kicked instantly but processing depends on what this job needs to do and the backend load at that moment. It can take couple of 30 sec processing batches.
