### ISSUE TITLE
ChannelSort<StreamChatGenerics> looks at the wrong fields

### ISSUE THREAD

**Issue by andreibarabas** [GetStream/stream-chat-js#915]
If we have a channel with custom props, those props are not recognised anymore due to the fact that ChannelSort now looks at the  generic instance instead of the 'channelType' field

**Comment by petyosi** [comment]
@khushal87 can you take a look?

**Comment by khushal87** [comment]
Sure @petyosi

**Comment by khushal87** [comment]
@andreibarabas Just to be sure, are you trying to use the property inside `ChannelSort`?
