### ISSUE TITLE
401 - Chat is not enabled for your account

### ISSUE THREAD

**Issue by g-apparence** [GetStream/stream-chat-js#917]
Hi, 
how can I activate chat?
I don't get why I click on a free trial button, make everything, and cannot make anything without any explanation. 
So I suspected that's a bug. 

```
Error: {"code":2,"StatusCode":401,"message":"WS failed with code 2 and reason - Chat is not enabled for your account, your trial is either expired or not activated. Check https://getstream.io/pricing/chat/ or reach out to support","isWSFailure":false}
```

Here is a just created account from the trial button telling that all should be ok...
<img width="1344" alt="Capture d’écran 2022-03-02 à 14 05 36" src="https://user-images.githubusercontent.com/48241546/156367566-92b351cc-c59d-4a1b-91a3-b687a16040f1.png">

Note: I followed your angular documentation. Maybe it's outdated and doesn't work anymore?

**Comment by g-apparence** [comment]
contacted support. 
I don't understand but maybe that's related. (just created my account a
<img width="788" alt="Capture d’écran 2022-03-02 à 14 38 27" src="https://user-images.githubusercontent.com/48241546/156372412-2590c8da-b392-4176-8b31-f07fce9f53a1.png">
nd I have this).

**Comment by g-apparence** [comment]
It seems I had to do another click to activate trial on another page... 
Don't really understand why I should access an another page with "activate tryal" when I subscribe with the button "Try it". 
Also this page wasn't linked anywhere in the admin so you are just banging your head on your keyboard feaguring why this doesn't work. 

I let you this open as I think this could really make a better developper experience...

**Comment by shodgetts** [comment]
Hello, 

Can you please send an email to support@getstream.io? We'll help you out there, it should not take long at all. If you could include the app_id that you are trying to access Chat with then that would be even better! 

Thanks! 
Stephen
