### ISSUE TITLE
Upsert seems to check if user is available

### ISSUE THREAD

**Issue by elemanhillary** [GetStream/stream-chat-js#924]
I have user A in my app am using, and they are in my stream dashboard in users (explorer on dashboard)
Then i tried to update the user A through the app and upsert throws "user is deleted error" which shouldn't be the case, it should create/ update the user whether deleted / new user

**Comment by miagilepner** [comment]
Hi @elemanhillary, once a user is deleted it is not possible to use the user_id of that user again or to re-create the user. Our documentation has more information about deleting a user: https://getstream.io/chat/docs/javascript/update_users/?language=javascript#delete-a-user.
