### ISSUE TITLE
Documentation to migrate from 5.x.x to 6.x.x

### ISSUE THREAD

**Issue by mathieuSal** [GetStream/stream-chat-js#926]
Hi 👋 

Starting the migration process, I'm looking for a documentation explaining how to handle the changes.
For example, I'm not sure to understand how to transform the following code to be a valid 6.x.x version code:
`export type Attachment = StreamAttachment<{
  thumb_url: string
  name: string
  asset_url: string
  type: AttachmentTypes
}>`

The error I get 
`Type '{ thumb_url: string; name: string; asset_url: string; type: AttachmentTypes; }' does not satisfy the constraint 'ExtendableGenerics'.
  Type '{ thumb_url: string; swile_security: string; name: string; asset_url: string; type: AttachmentTypes; }' is missing the following properties from type 'ExtendableGenerics': attachmentType, channelType, commandType, eventType, and 3 more.`

Do you have a documentation explaining how to handle the breaking changes? 
Thanks

**Comment by khushal87** [comment]
Hey @mathieuSal, you are using the client directly or using it within an SDK(React, React Native, Angular, etc)?

**Comment by mathieuSal** [comment]
I am using it with React and I manage to do the upgrade thanks to the information I found there :)
