### ISSUE TITLE
Access denied after trying to display images from exportChannel

### ISSUE THREAD

**Issue by sergeyzhukov** [GetStream/stream-chat-js#937]
Hello. 

I'm using `exportChannel` call from our node.js backend to export all channel data and found that URL for fields `asset_url` and `thumb_url` inside `message.attachments` are incorrect, access denied. When I trying to display such URL error looks like this

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>
```

`"stream-chat": "6.3.0"`

Any ideas how to display attachments from `exportChannel` without access denied issue?

**Comment by miagilepner** [comment]
Hi @sergeyzhukov, this should be fixed so I'm going to close the issue.
