### ISSUE TITLE
ASC sorting/pagination for messages

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-js#957]
Hi

is it possible to sort messages or paginate from oldest to newest, instead of newest to oldest? Right now there is no way to get the first message in the channel without getting all messages, afaik.

**Comment by vishalnarkhede** [comment]
@plandem currently this is not possible. But please get in touch with support@getstream.io with your detailed product requirement where you need this sort behaviour. So that we can assess and in future add it to our roadmap.
