### ISSUE TITLE
Is there any way to get total number of messages?

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-js#964]
The task is simple, we need to check if there are more messages to load. If it would be possible to know it after getting the channel via `client.channel(type, id, options);`, but there is no such information. Any ideas? Or manually calling `channel.query()` to check is the only way?

**Comment by vishalnarkhede** [comment]
@plandem currently there is no way to get this count. Whats the product requirement exactly, for which you need the total message count? So that we can discuss internally to add it to our roadmap

**Comment by vishalnarkhede** [comment]
Also the Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out.
