### ISSUE TITLE
Where is the supposed deactivate method?

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-js#968]
https://getstream.io/chat/docs/react-native/channel_delete/?language=javascript

> Deleting a Channel

> You can delete a single Channel using the delete method. This marks the channel as deleted and hides all the messages.

> const destroy = await channel.delete();
> If you recreate this channel, it will show up empty. Recovering old messages is not supported. Use the deactivate method if you want a reversible change

There is mention of a deactivate method in the docs but the sdk does not offer this.

Is `channel.delete({ hard_delete: false })` the equivalent of deactivate?

**Comment by ferhatelmas** [comment]
You can find them in following links:
code: https://github.com/GetStream/stream-chat-js/blob/master/src/client.ts#L1882=
docs: https://getstream.io/chat/docs/node/update_users/?language=javascript#deactivate-a-user

**Comment by ferhatelmas** [comment]
You're right, wording there is a bit. It was trying to say disabled: https://getstream.io/chat/docs/react-native/disabling_channels/

**Comment by ferhatelmas** [comment]
Please create a ticket in support for it since it's not a bug in SDK then customer success/docs teams can follow up. Thanks!
