### ISSUE TITLE
Getting Axios error when updating grants of roles on a channel type

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-js#975]
stream-chat version: `6.5.1`

I recently migrated our permissions version of stream chat to v2. I programmatically created new roles for our use case. Next I wanted to nullify all current role grants in specific channel types and from scratch only add permissions for our custom roles. I followed the documentation to nullify it with:
```
await client.updateChannelType(customChannelType, {
    grants: null
});
```

And add grants for custom roles using:
```
await client.updateChannelType(customChannelType, {
    grants: [
        "customRole": [
            "add-links",
            ....
        ],
        ....
    ]
});
```

But everytime I run even any one of the above code blocks, they both throw error. There are existing channels with many members of the channel type that I am trying to update here.

Error response when I try to give grant to custom roles using above code block:
Keys of the `error` object: 
```
[
  'config',
  'code',
  'request',
  'response',
  'isAxiosError',
  'toJSON',
  'client_request_id'
]
```

Value of:
Code - "ECONNABORTED"
isAxiosError - true
response - undefined
Some part of `toJSON`:
```
{
  message: 'timeout of 3000ms exceeded',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: timeout of 3000ms exceeded\n' +
    '    at createError (/Users/.../MyApiProject/node_modules/stream-chat/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at RedirectableRequest.handleRequestTimeout (/Users/.../MyApiProject/node_modules/stream-chat/node_modules/axios/lib/adapters/http.js:328:16)\n' +
    '    at RedirectableRequest.emit (events.js:210:5)\n' +
    '    at RedirectableRequest.EventEmitter.emit (domain.js:475:20)\n' +
    '    at Timeout.<anonymous> (/Users/.../MyApiProject/node_modules/follow-redirects/index.js:164:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)',
  code: 'ECONNABORTED',
  status: null
}
```

This is occuring everytime. I have a stable internet connection so it shouldn't be caused because of that.
Have I misunderstand any of the steps for updating these roles?

**Comment by JayMehta97** [comment]
Hi, is anyone looking into this issue, this is a p0 for us as a lot of other stream SDK updates are dependent on this.

Thanks.

**Comment by AnatolyRugalev** [comment]
Hi Jay,

Thanks for bringing this up. It is likely that 3 seconds is not enough to perform an update of the application settings. When application settings, which include `grants` field are updated, our backend needs some time to distribute this data globally. I suggest to you increase timeout configuration of the client and see if this fixes the issue:

```
// create new client with specified timeout
const client = new StreamChat(key, secret, { timeout: 10000 });

// use singletone client with specified timeout
const client = StreamChat::getInstance(key, secret, { timeout: 10000 });
```

Timeout increase is only required for **write** operations on application configuration, so if you don't want to increase it for your whole application, you can keep dedicated client instance with higher timeout value specifically for these updates.

Also, you can check out GUI permission configuration if you want to set them up manually.

I hope this helps
