### ISSUE TITLE
Removed users are not removed after re-watching a channel

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-js#988]
1. Create and watch a channel (logged in as Alice)
2. Invite Bob (as Alice)
3. Unwatch the channel (as Alice)
4. Bob rejects the invite / leaves the channel
5. Watch the channel again (as Alice)
6. Bob is still listed in state.members as invited

The issue is that this line is only additive https://github.com/GetStream/stream-chat-js/blob/master/src/channel.ts#L1356 and never removes users.

**Comment by madsroskar** [comment]
Thanks for reporting this, I've reproduced this with a test. I'll look into fixing this.
