### ISSUE TITLE
Truncated event handler does not respect `truncated_at` 

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-js#990]
The [handler clears all messages](https://github.com/GetStream/stream-chat-js/blob/f70de60662a372607bd1fabe0651d1c86b90a6a9/src/channel.ts#L1247-L1257) regardless of the [`truncated_at`](https://getstream.io/chat/docs/javascript/truncate_channel/?language=javascript&q=truncated_at) parameter passed.

**Comment by arnautov-anton** [comment]
Addressed in #991 and #996.
