### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by nayebare** [GetStream/stream-chat-js#992]
Hi, i need someone to kindly look into this error.

```
let  StreamChat = require("stream-chat").StreamChat;

../node_modules/stream-chat/dist/index.js:1284
    return crypto.getRandomValues.bind(crypto);
                                  ^

TypeError: Cannot read properties of undefined (reading 'bind')
    at ../node_modules/stream-chat/dist/index.js:1284:35
    at Object.<anonymous> (../node_modules/stream-chat/dist/index.js:1290:2)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/index.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

**Comment by madsroskar** [comment]
Hi, @nayebare. I'm not able to reproduce this, would you be able to provide a minimal example that reproduces the issue? Any more information you could give about the specific environment would help as well. For example, which version of `stream-chat` are you using? Which version of NodeJS are you using?

**Comment by nayebare** [comment]
@madsroskar kindly replicate the error using this code the goal is to run the code as serverless while testing it locally

**Comment by vanGalilea** [comment]
@nayebare does this issue still occur? 
If yes we would like to pinpoint this issue as fast as possible, we would like to ask you to share a minimalistic repo where the problem is reproduced.
The fastest way to achieve this is with the following command to create a new RN project with Stream chat in it:

`npx react-native init MyApp --template stream-chat-react-native-template`

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by nayebare** [comment]
@vanGalilea kindly replicate the error using this code the goal is to run the code as serverless while testing it locally https://github.com/nayebare/create-getstream-node-test

**Comment by khushal87** [comment]
Hey @nayebare the code you have shared takes us to a 404 not found page. Still facing this issue?

**Comment by nayebare** [comment]
hey @khushal87 i have made the repository thank you

**Comment by vanGalilea** [comment]
@nayebare, thanks for sharing this repo. We've managed to reproduce this issue and currently working on a fix that will support node v16 and higher versions. 

Until then, you can use node v17.4.0 or higher.
