### ISSUE TITLE
Unable to set apns-collapse-id in remote notifications

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-js#999]
AFICS, there is no option to set apns-collapse-id. Ideally this should be set to `message.id` as otherwise duplication push notifications will not de-dupe.

Note I'm using APNS v1 configuraiton.

**Comment by miagilepner** [comment]
Thanks for reporting this. This is a good idea and we've added this as a feature request to our backlog.

In the meantime, because this issue describes a backend feature and is not specific to the javascript SDK, I'm going to close this issue.

**Comment by mfbx9da4** [comment]
Where is this tracked, has this been done @miagilepner ?
